### ISSUE TITLE
Version 5.0.0 causing permission error reading .config files on Azure

### ISSUE THREAD

**Issue by dargavin** [dotnet/SqlClient#1717] opened 2022-08-15 16:58 UTC
### Describe the bug
Updating NuGet package from 4.1.0 to 5.0.0 in a .Net 6.0 project, and then deploying to Azure, the web site get a 500 error.

Digging into the app logs it is a generic security error reading config files with the app service principle.  (Using the system generate principle option)

Downgrading just this package back to 4.1.0 in Azure allowed app to function again.
```
Exception message:
Stack trace:
Connecting...
2022-08-15T16:52:02  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>IIS Detailed Error - 500.0 - Internal Server Error</title><style type="text/css"><!--body{margin:0;font-size:.7em;font-family:Verdana,Arial,Helvetica,sans-serif;}code{margin:0;color:#006600;font-size:1.1em;font-weight:bold;}.config_source code{font-size:.8em;color:#000000;}pre{margin:0;font-size:1.4em;word-wrap:break-word;}ul,ol{margin:10px 0 10px 5px;}ul.first,ol.first{margin-top:5px;}fieldset{padding:0 15px 10px 15px;word-break:break-all;}.summary-container fieldset{padding-bottom:5px;margin-top:4px;}legend.no-expand-all{padding:2px 15px 4px 10px;margin:0 0 0 -12px;}legend{color:#333333;;margin:4px 0 8px -12px;_margin-top:0px;font-weight:bold;font-size:1em;}a:link,a:visited{color:#007EFF;font-weight:bold;}a:hover{text-decoration:none;}h1{font-size:2.4em;margin:0;color:#FFF;}h2{font-size:1.7em;margin:0;color:#CC0000;}h3{font-size:1.4em;margin:10px 0 0 0;color:#CC0000;}h4{font-size:1.2em;margin:10px 0 5px 0;}#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS",Verdana,sans-serif;color:#FFF;background-color:#5C87B2;
}#content{margin:0 0 0 2%;position:relative;}.summary-container,.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}.content-container p{margin:0 0 10px 0;}#details-left{width:35%;float:left;margin-right:2%;}#details-right{width:63%;float:left;overflow:hidden;}#server_version{width:96%;_height:1px;min-height:1px;margin:0 0 5px 0;padding:11px 2% 8px 2%;color:#FFFFFF;background-color:#5A7FA5;border-bottom:1px solid #C1CFDD;border-top:1px solid #4A6C8E;font-weight:normal;font-size:1em;color:#FFF;text-align:right;}#server_version p{margin:5px 0;}table{margin:4px 0 4px 0;width:100%;border:none;}td,th{vertical-align:top;padding:3px 0;text-align:left;font-weight:normal;border:none;}th{width:30%;text-align:right;padding-right:2%;font-weight:bold;}thead th{background-color:#ebebeb;width:25%;}#details-right th{width:20%;}table tr.alt td,table tr.alt th{}.highlight-code{color:#CC0000;font-weight:bold;font-style:italic;}.clear{clear:both;}.preferred{padding:0 5px 2px 5px;font-weight:normal;background:#006633;color:#FFF;font-size:.8em;}--></style>
</head><body><div id="content"><div class="content-container"><h3>HTTP Error 500.0 - Internal Server Error</h3><h4>The page cannot be displayed because an internal server error has occurred.</h4></div><div class="content-container"><fieldset><h4>Most likely causes:</h4><ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul></fieldset></div><div class="content-container"><fieldset><h4>Things you can try:</h4><ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul></fieldset></div>
<div class="content-container"><fieldset><h4>Detailed Error Information:</h4><div id="details-left"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;AspNetCoreModuleV2</td></tr><tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr><tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;aspNetCore</td></tr><tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x00000000</td></tr>
</table></div><div id="details-right"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://oha-survey-dev:80/</td></tr><tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;C:\home\site\wwwroot</td></tr><tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr><tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr>
</table><div class="clear"></div></div></fieldset></div>
<div class="content-container"><fieldset><h4>More Information:</h4>This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error.<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,0,0x00000000,14393">View more information &raquo;</a></p><p>Microsoft Knowledge Base Articles:</p>
</fieldset></div></div></body></html>

### To reproduce
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="6.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="6.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.8" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

### Expected behavior
Expected no permission issues reading configs with update from 4.1.0 to 5.0.0

### Further technical details
Microsoft.Data.SqlClient version: 5.0.0
.NET target: 6.0
SQL Server version: 2017
Operating system: Azure

**Additional context**
Add any other context about the problem here.

**Comment by dargavin** [comment] 2022-08-15 17:53
I have one Azure app which is working with SQLClient 5.0.   There are some differences form the two where 5.0 causes a perm issue.  But the notable one is in the Authentication libraries.  So maybe the issue related to a combo of 5.0 and Authentication?

The project with the following nuget's functions okay at 5.0:

<ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.96.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="6.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="6.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.8" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="6.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.8" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />
    <PackageReference Include="OHADST.Common.AspNetCore.Extensions" Version="5.0.2" />
    <PackageReference Include="OHADST.Common.Edi" Version="1.6.2" />
    <PackageReference Include="OHADST.EFCore.AuditLogging" Version="5.0.4" />
  </ItemGroup>

**Comment by JRahnama** [comment] 2022-08-15 20:58
@dargavin can you provide more detail such as sample app or a repo or an inner exception that indicates this is a M.D.SqlClient issue? We have upgraded the version numbers in our latest release for `Azure.Identity` and `Microsoft.Identity.Client`. Is it possible for you to overwrite those versions in your application and see what happens?

**Comment by dargavin** [comment] 2022-08-16 15:13
@JRahnama The MS Azure team had me open a support ticket on this,   Support request number:	2208160010004040

Hopefully they'll be able to get more diagnostics out of Azure then I can.   The issue is happening at app startup so the stack track I posted is all I was able to get out of Azure.  Far as i could see no inner exception.  It acted similar to a 500.19 error like a bad config file, but was a permission issue instead of cannot read issue.

I am checking with management about releasing the code, however initial feedback is asking if a MS Teams meeting might be possible instead.   Some of our Databases and Code dealt with HIPAA compliant data so just cannot release them, 

On the package version if you look at first post the Authentication packages were at 6.0.8 already, so at latest version.  The app having the issue doesn't use MS IDentity, but OpenIDConnect.

**Comment by JRahnama** [comment] 2022-08-18 18:34
@dargavin can you guide me step by step to make a simple application similar to what you have so I can start investigating it?

**Comment by dargavin** [comment] 2022-08-23 15:41
@JRahnama With Help of MS Azure support got the issue figured out.  What was happening is the version 4.1 was allowing DB connection string with a typo in the user id (App serv user did not match app name) to still function somehow.  

The 5.0.0 package actually corrected that, and it was throwing a ManagedIdendity not found error behind the scenes.  

So issue is resolved, though why 4.1 version was accepting a bad user ID on connections is a bit past me.

**Comment by JRahnama** [comment] 2022-08-23 16:23
@dargavin we are glad to here that the issue is solved. I will look into the PRs for v5.0 and also fixes in Azure.Identity and Microsoft.Identity.Client as well to see where the issue got addressed and will comment it here.

I am closing this issue as it is solved. Feel free to comment here if the issue still exists.

**Closed by JRahnama** 2022-08-23 16:23 UTC

**Comment by ErikEJ** [comment] 2022-08-23 16:30
@dargavin can you give an example of a "bad" connection string?

**Comment by dargavin** [comment] 2022-09-01 17:09
@ErikEJ 
Server=tcp:oha-hsd-sqldb-dev-01.database.usgovcloudapi.net,1433;Database=CompassSurvey;User ID=oha-survey-dev;Authentication=Active Directory Managed Identity

where ;User ID=oha-survey-dev needs to be removed in 5.0.0 even though that matches the app service name/system assigned principle.  Worked okay 4.1, but also ntoices that in 4.1 it accepted a typo in user id.  So 4.1 seemed to be ignoring it.
