### ISSUE TITLE
error occurred during the pre-login handshake error:success

### ISSUE THREAD

**Issue by RagingPuppies** [dotnet/SqlClient#690] opened 2020-08-13 14:40 UTC
Hi,
maybe someone here can enlighten me, i receive once or twice in a day the following messages (lets say 1\100000 calls):

A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - Success)
or
A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - Unknown error)

The service running on Linux machine in a docker container (Rancher) and making calls to mssql 2016, i do know that the call is not completed and there is an error, it's just that "success"  doesn't tell me much about how to solve it...
i randomly get that from all my services..

- no pod restarts
- I have no events correlating in the DB servers

and have rad the whole internet and usually the error is more informative in other people posts...
can someone help me here?

**Comment by ErikEJ** [comment] 2020-08-13 14:45
Which client version??

**Comment by RagingPuppies** [comment] 2020-08-13 15:15
@ErikEJ System.Data.SqlClient, Version=4.5.0.1

**Comment by JRahnama** [comment] 2020-08-13 15:40
@RagingPuppies Can I ask for detail? What version of netcore is installed on your machine? we did have some [similar issues](https://github.com/dotnet/runtime/issues/26388) in the past.

**Comment by RagingPuppies** [comment] 2020-08-13 17:23
@JRahnama  yeah sure,
Machine Ubuntu 18.04 with Kubernetes v1.17.2
Docker: 5:18.09
Container with .netcore 3.1
Windows 2016 with MSSQL 2016 CU7 (13.0.5337.0)

anything else?

**Comment by JRahnama** [comment] 2020-08-13 17:34
@RagingPuppies Thanks for the quick response. If possible, have you tried using the [latest version of System.Data.SqlClient](https://www.nuget.org/packages/System.Data.SqlClient/) or  [Microsoft.Data.SqlClient V2.0.0.0](https://www.nuget.org/packages/Microsoft.Data.SqlClient/)? Also one last thing, is it possible to share us a repro of your code? we will try to reproduce the issue here and follow from there.

**Comment by RagingPuppies** [comment] 2020-08-17 08:12
@JRahnama 
i would also like to add the it happens for 2 sec several time while we have heavy load  on our servers, 2.
you can use the following to repreduce
`async Task<List<CurrenciesDO>> ICurrenciesDal.GetCurrencies()
        {
            List<CurrenciesDO> result = new List<CurrenciesDO>();

            IBaseDal thisIBaseDal = this as IBaseDal;

            using (SqlConnection conn = new SqlConnection(thisIBaseDal.ConnectionString))
            {
                DynamicParameters parameters = new DynamicParameters();

                ErrorDbParameters.AddErrorDbParams(parameters);

                CommandDefinition command = new CommandDefinition(GET_CURRENCIES_STORED_PROCEDURE_NAME, parameters, commandType: CommandType.StoredProcedure);

                using (var reader = await conn.ExecuteReaderAsync(command))
                {
                    while (await reader.ReadAsync())
                    {
                        CurrenciesDO plRowData = await GetDataFromReader(reader);

                        result.Add(plRowData);
                    }
                }

               ErrorDbParameters.ValidateErrorDbParams(parameters, new int[] { ErrorCodes.ERROR_GENERAL_NOROWS });
            }

            return result;
        }
`

**Comment by JRahnama** [comment] 2020-09-03 19:04
@RagingPuppies based on the sample code you sent me I made an application and let it ran for a dayand a night, could not see the issue happening. Is it possible for you to run your application with Microsoft.Data.Sqlclient V2.0.0 or the latest preview ( we do not have that support in System.Data.Sqlclient) and run PerfView on your Windows container to capture EventSource Traces for Microsoft.Data.SqlClient.EventSource? This could be done either in command line or interface. If the answer is yes,

you need to run the command as `perfview /onlyProviders=*Microsoft.Data.SqlClient.EventSource run <Your_Application.exe> `

and set the path to the folder that has the executive file of your project. 

you either can generate a [secrete gist ](https://docs.github.com/en/enterprise/2.13/user/articles/creating-gists)and send me the link in a private conversation if you are concerned about your information or even easier email me the link or the file itself.

Doing this will give us more information about the issue and its occurrences.

**Comment by RagingPuppies** [comment] 2020-09-06 17:55
So the error code was solved, it was a network component (linkerd) answering to tcp even tho the sqlserver is not responding, skipping sql port will reveal the true error... Thank you all

**Comment by JRahnama** [comment] 2020-09-08 15:37
@RagingPuppies I am glad the issue is resolved. Feel free to close the issue if there is no related topic to discuss here.

**Closed** 2020-09-10 12:34 UTC
