### ISSUE TITLE
Different behaviors between System.Data.SqlClient and Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by qizu0302** [dotnet/SqlClient#2368] opened 2024-02-23 06:34 UTC
I force SQL Server to encrypt connection, I use SSMS 18 and SSMS 19 to connect to database, both are configured as below, that is "Encrypt=False;TrustServerCertificate=False"
![image](https://github.com/dotnet/SqlClient/assets/103396968/e61627ac-351d-45dd-95a6-d667558b005c)

I don't import SQL Server self-signed certificate into trust CA store, the result is SSMS 18 can connect to database while SSMS 19 fails to connect to database. 

I know SSMS 18 uses the legacy library, and SSMS 19 uses the new one, I wonder is this discrepancy by design?

**Comment by David-Engel** [comment] 2024-02-26 18:59
> I know SSMS 18 uses the legacy library, and SSMS 19 uses the new one, I wonder is this discrepancy by design?

Yes.

In System.Data.SqlClient, Encrypt defaults to false. When Encrypt = false in SDS, the server certificate is never validated, regardless of what TrustServerCertificate is set to.

Security has been tightening in Microsoft.Data.SqlClient. Starting with MDS 2.0 (SSMS 19 uses MDS 3.1), the server certificate will be validated based on the value of TrustServerCertificate if the client (Encrypt = true) or the server (Force Encryption on the server config) requires encryption. Most likely, your server is configured with Force encryption. Since your self-signed certificate is not part of a trusted chain on your client, the certificate validation fails. (As a furthering of the security tightening, starting with MDS 4.0, Encrypt defaults to true. So, in the next major version of SSMS, you'll probably see that Encrypt connection checkbox start defaulting to checked.)

**Comment by kf-gonzalez** [comment] 2024-02-27 19:04
Closing issue as this behavior is by design

**Closed by kf-gonzalez** 2024-02-27 19:04 UTC
Labels: untriaged
