### ISSUE TITLE
Rebuild of a solution with multiple references to the SqlClient fails with Unable to delete file "bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x86.dll". Access to the path 'bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x86.dll' is denied.

### ISSUE THREAD

**Issue by kosinsky** [dotnet/SqlClient#2464] opened 2024-04-12 19:51 UTC
### Describe the bug
We have solution with 60+ projects and 30+ of them reference Microsoft.Data.SqlClient. Rebuild from VS 2022 fails with error like:
```
C:\Users\<username>\.nuget\packages\microsoft.data.sqlclient.sni\5.1.1\buildTransitive\net462\Microsoft.Data.SqlClient.SNI.targets(151,5): error
 MSB3061: Unable to delete file "<solution>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x86.dll". 
Access to the path '<solution>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x86.dll' is denied.
```
`Microsoft.Data.SqlClient.SNI.targets(151,5)` which is part of the SNI NuGet package looks like:
```xml
  <Target Name="CleanSNIFiles"
          Condition="'$(CleanSNIFiles)' != 'false' And
                     '$(OutDir)' != '' And
                     HasTrailingSlash('$(OutDir)') And
                     Exists('$(OutDir)')">
    <!--
        NOTE: Delete "Microsoft.Data.SqlClient.SNI.dll" and all related files, for every
              architecture that we support, from the build output directory.
    -->
    <Delete Files="@(SNIFiles -> '$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')" /> -- Line 151
  </Target>
```
My guess is that VS 2022 runs build of multiple projects in parallel and hits race condition: 
1. `SNIFiles` calculated for multiple projects at the same time as not empty
2. Build for one project deletes files and build from other projects fail to build as file was already deleted

I ran VS 2022 with verbose logging and see multiple places like:
```
11>    Target CleanSNIFiles:
11>      Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.arm64.dll".
11>      Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.arm64.pdb".
11>      Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x64.dll".
11>      Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x64.pdb".
11>      Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x86.dll".
11>      Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x86.pdb".

14>  Target CleanSNIFiles:
14>    Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.arm64.dll".
14>    Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.arm64.pdb".
14>    Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x64.dll".
14>    Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x64.pdb".
14>    Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x86.dll".
14>    Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x86.pdb".


19>  Target CleanSNIFiles:
19>    Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.arm64.dll".
19>    Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x64.dll".
19>    Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x64.pdb".
19>    Deleting file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x86.pdb".
19>    C:\Users\<username>\.nuget\packages\microsoft.data.sqlclient.sni\5.1.1\buildTransitive\net462\Microsoft.Data.SqlClient.SNI.targets(151,5): error MSB3061: Unable to delete file "<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x86.pdb". Access to the path '<solution path>\bin\Debug\net48\Microsoft.Data.SqlClient.SNI.x86.pdb' is denied.
19>  Done building target "CleanSNIFiles" in project "StateMachine.csproj" -- FAILED.
```

Notice that `CleanSNIFiles` executed from multiple parallel builds (11, 14, 19)

I think `TreatErrorsAsWarnings="true"` show solve that issue. At least it's how it's done in `Microsoft.Common.CurrentVersion.targets`:
```xml
    <!-- Delete those files. -->
    <Delete
        Files="@(_CleanPriorFileWritesInOutput);@(_CleanPriorFileWritesInIntermediate)"
        TreatErrorsAsWarnings="true">

      <Output TaskParameter="DeletedFiles" ItemName="_CleanPriorFileWritesDeleted"/>

    </Delete>
```

### Expected behavior
Clean rebuild without errors.

### Further technical details
Microsoft.Data.SqlClient version: 5.1.5 (tried with 5.2 and got the same error)
.NET target: net48
SQL Server version: 2022
Operating system: Windows 11

**Comment by DavoudEshtehari** [comment] 2024-04-15 18:24
The MSB3061 error can be tricky because it’s often related to environmental issues, such as files being locked by other processes or antivirus software. Can you try forcing MSBuild to use only one thread by setting the environment variable `MSBUILD_PROCESSES` to 1 or by passing the `-maxCpuCount:1` flag directly to MSBuild?

**Comment by kosinsky** [comment] 2024-04-16 14:08
>Can you try forcing MSBuild to use only one thread by setting the environment variable MSBUILD_PROCESSES to 1 or by passing the -maxCpuCount:1 flag directly to MSBuild?

Running it single threaded eliminates that issue, however it's huge slow down.

>The MSB3061 error can be tricky because it’s often related to environmental issues, such as files being locked by other processes or antivirus software. 

It observable for multiple machines and multiple developers.

**Comment by JRahnama** [comment] 2024-04-23 18:29
@kosinsky the fix is merged in SNI package and will be available in next SNI release, v6.0-preview1.

Closing as the issue is addressed.

**Closed by JRahnama** 2024-04-23 18:29 UTC

**Comment by cts-tradeit** [comment] 2024-05-03 15:15
@JRahnama Was this issue present in older version? So we can resolve it other way than lowering paralelization to 1 or that local modification above.

**Comment by JRahnama** [comment] 2024-05-03 16:19
@cts-tradeit I think so. The fix is the exact implementation described here, adding `TreatErrorsAsWarnings="true"`. That does not exist in previous versions.

**Comment by Deathrage** [comment] 2024-05-06 19:58
@JRahnama Hi, when is the new version gonna be available at least as preview on nuget org?

**Comment by jakubsuchybio** [comment] 2024-12-03 09:24
When the [6.0.0-preview1.24226.4](https://www.nuget.org/packages/Microsoft.Data.SqlClient.SNI.runtime/6.0.0-preview1.24226.4) will be released as stable version? We are hitting this issue as well on our 250+projects solution.........

**Comment by MichelZ** [comment] 2024-12-03 09:29
The current due date seems to be `December 9th`:
https://github.com/dotnet/SqlClient/milestone/64

**Comment by Bebo2345** [comment] 2025-02-27 22:37
Amy chance this will be added to 5.2.2? 😏
