### ISSUE TITLE
Different SQL server connection behavior for native and managed SNI on Windows

### ISSUE THREAD

**Issue by antarisnsk** [dotnet/SqlClient#2297] opened 2024-01-15 08:44 UTC
### Describe the bug
When trying to connect to remote sql server using sql authentication with UseManagedNetworkingOnWindows set to true, I get the following exception

```
A connection was successfully established with the server, but then an error occurred during the login process. 
(provider: TCP Provider, error: 0 - The operation completed successfully.)
```
But if I remove the UseManagedNetworkingOnWindows switch, SqlClient connects without issue.
When connecting to local db, no errors in either case.
My environment is .Net 6.0 / SqlClient 5.1.4, but I've tried .Net 7.0 / SqlClient 5.2.0-preview4 and got the same result.
### To reproduce

```c#
AppContext.SetSwitch("Switch.Microsoft.Data.SqlClient.UseManagedNetworkingOnWindows", true);

using (SqlConnection connection = new("Data Source=10.3.111.25,1433;Initial Catalog=name;User Id=;Password=;TrustServerCertificate=True;Encrypt=False;"))
{
    await connection.OpenAsync();
}
```
Username/password are correct.

### Expected behavior
Connect without error when using native SNI.

### Further technical details
Microsoft.Data.SqlClient version: 5.1.4
.NET target: .Net 6.0 / .Net 7.0
SQL Server version: 14.0.1000.169
Operating system: Windows 11

**Comment by JRahnama** [comment] 2024-01-15 20:39
@antarisnsk the issue is not reproduceable on my end. I have tested with SQL Server 2017(14), net6.0, net7.0 and net8.0 with and without the switch. Also I have tried with sync and async.

```C#
static async Task Main(string[] args)
{
    AppContext.SetSwitch("Switch.Microsoft.Data.SqlClient.UseManagedNetworkingOnWindows", true);
    SqlConnectionStringBuilder builder = new()
    {
        DataSource = "tcp:****\\MSSQLSERVER17",
        UserID = "sa",
        Password = "****",
        Encrypt = SqlConnectionEncryptOption.Optional,
        TrustServerCertificate = true
    };
    using SqlConnection conn = new(builder.ConnectionString);
    await conn.OpenAsync();
    Console.WriteLine(conn.State);
}
```
Have I missed anything here?

**Comment by antarisnsk** [comment] 2024-01-16 04:30
Turns out I was connecting to sql server 2008 (10.50), and there is indeed no error when using versions 14 and up. Sorry for bad info. Ok to close if 2008 is not supported.

**Comment by JRahnama** [comment] 2024-01-16 06:09
SQL Server 2008 is not supported anymore. [SQL Server v2016 and after are supported](https://learn.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-end-of-support-overview?view=sql-server-ver16#resources).
Closing the issue since the version of the server is not supported anymore.

**Closed by JRahnama** 2024-01-16 06:09 UTC
Labels: untriaged
