### ISSUE TITLE
The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception.

### ISSUE THREAD

**Issue by ainsleybernard** [dotnet/SqlClient#1460] opened 2022-01-10 23:58 UTC
Hello, I am creating Azure Function from the project templates VS 2019. I am trying to create a simple connection in the function to Dynamic 365 TDS endpoint using `Active Directory Service Principal` which requires me to use `Microsoft.Data.SqlClient` (using version 4.0.0) versus `System.Data.SqlClient `. When running the project locally I am getting the below error message. Ive tried to include the require package, but no luck, could you please try and reproduce, thanks! 

![image](https://user-images.githubusercontent.com/17305314/148857023-21a22652-225a-4cae-b438-635d9ce2b672.png)

![image](https://user-images.githubusercontent.com/17305314/148857688-8e288fcc-cd65-4f68-be06-a4e3b48a9f4c.png)

Exception message:
` The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception.`

Stack trace: 
`
   at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()

`

Inner Exception:
`Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.`

Stack trace:
`   at Microsoft.Data.SqlClient.SqlAuthenticationProviderManager..cctor()`

### Here is code sample of Im trying to do

```c#
using System;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Microsoft.Data.SqlClient;
namespace FunctionAppTestNetCore
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");



            try
            {
                // Use your own server, database, app ID, and secret.
                string ConnectionString = @"Server=demo.database.windows.net; Authentication=Active Directory Password; Database=testdb; User Id=user@domain.com; Password=***";

                using (SqlConnection conn = new SqlConnection(ConnectionString))
                {
                    conn.Open();
                }

            }
            catch (Exception e)
            {
                log.LogInformation(e.ToString());

            }


            string name = req.Query["name"];

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            string responseMessage = string.IsNullOrEmpty(name)
                ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
                : $"Hello, {name}. This HTTP triggered function executed successfully.";

            return new OkObjectResult(responseMessage);
        }
    }
}

```

### Expected behavior
I expect dependencies to resolved and connection attempt made.

### Further technical details
Microsoft.Data.SqlClient version: 4.0.0
.NET target: ( Core 3.1)

**Comment by JRahnama** [comment] 2022-01-11 01:52
@ainsleybernard can you check the version of `Microsoft.Identity.Client`. If it is anything less than `4.22.0` can you try overwriting it in your csproj please?

**Comment by ainsleybernard** [comment] 2022-01-11 02:45
@JRahnama  thanks for reply, it is 4.22.0
![image](https://user-images.githubusercontent.com/17305314/148872156-6a325937-9fb8-427b-81c7-79ce53da0adb.png)

**Comment by JRahnama** [comment] 2022-01-12 04:58
@ainsleybernard can you share the runner class for the posted code? I need a repro. What is the Microsoft.NetCore.App version in your project? I also checked to see if System.Configuration.dll is available for my project here and it was. Can you check that please?

**Comment by JRahnama** [comment] 2022-01-13 17:47
Seems the issue is with dotnet runtime. You can follow and find workarounds at [this link](https://github.com/dotnet/runtime/issues/54642#issuecomment-947985175).

**Comment by JRahnama** [comment] 2022-01-14 04:22
I am closing this issue as this is not related to SqlClient driver.

**Closed by JRahnama** 2022-01-14 04:22 UTC
Labels: :link: External
