### ISSUE TITLE
SELECT SqlCommand (async) never finishes for 100 MB file in EF Core 6 but finishes fine in SSMS

### ISSUE THREAD

**Issue by janseris** [dotnet/SqlClient#1765] opened 2022-09-16 23:28 UTC
### Describe the bug
Setup:

Sample project: https://github.com/janseris/EFCoreTest

"Image" table with Data of FILESTREAM (varbinary(max)).
Table cotains 1 item with 100 MB file.
![image](https://user-images.githubusercontent.com/64279914/190830448-054b85d3-8f67-432e-8707-477d7246bba0.png)

[CancellationTokenTestDB.sql.txt](https://github.com/dotnet/SqlClient/files/9590553/CancellationTokenTestDB.sql.txt) 
(sorry, GitHub "doesn't support" files with names ending with `.sql`)

Select all query takes 1 minute 31 seconds on 1,5 MB/s download in SSMS (expected).

Select all query called with EF Core never finishes (I wanted 5 and then another attempt 10 minutes) and no exception is thrown. 
The finally block after the try block with the query never executes.

Also, cancelling for the query never finishes (I waited for 2 minutes):

```
info: 17.09.2022 01:36:18.015 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (123ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [i].[ID], [i].[Name], [i0].[Data]
      FROM [IMAGE] AS [i]
      LEFT JOIN [IMAGE_DATA] AS [i0] ON [i].[ID] = [i0].[ImageID]
Operation cancel request submitted at 01:36:19.695
```

Code:

```
private async Task LoadAll()
        {
            try
            {
                cts = new CancellationTokenSource();
                var token = cts.Token;
                loadAllButton.Enabled = false;
                cancelLoadingButton.Enabled = true;
                var items = await DAO.LoadAllAsync(token);  //takes 1m 31s to execute in SSMS
                Trace.WriteLine($"Loaded {items.Count} items, total size: {items.Sum(i => i.Data.Length / 1024*1024)} MB");
            }
            catch (Exception ex)
            {
                Trace.WriteLine(ex.GetType() + ex.Message);
            }
            finally
            {
                Trace.WriteLine($"Operation was really cancelled at {GetTime()}");
                cts.Dispose();
                cts = null;
                loadAllButton.Enabled = true;
                cancelLoadingButton.Enabled = false;
            }
        }
```

EF Core 6 log claims that the command had already finished in 130 milliseconds.
Network activity is fine first ~10 seconds but then starts slowing down and running randomly (approx 5 to 10 seconds 0 Kb/s and then half speed for 1 second and then again nothging for 5 to 10 seconds and the interval length is raising progressively).

```
dbug: 17.09.2022 01:25:13.276 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection) 
      Opened connection to database 'devRemin' on server 'myServer'.
dbug: 17.09.2022 01:25:13.287 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [i].[ID], [i].[Name], [i0].[Data]
      FROM [IMAGE] AS [i]
      LEFT JOIN [IMAGE_DATA] AS [i0] ON [i].[ID] = [i0].[ImageID]
info: 17.09.2022 01:25:13.425 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (137ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [i].[ID], [i].[Name], [i0].[Data]
      FROM [IMAGE] AS [i]
      LEFT JOIN [IMAGE_DATA] AS [i0] ON [i].[ID] = [i0].[ImageID]
```

The EF query:

```
public async Task<List<Image>> LoadAllAsync(CancellationToken token = default) 
        {
            using var db = factory.CreateDbContext();
            var query = from image in db.IMAGE.Include(image => image.IMAGE_DATA)
                        select new Image
                        {
                            ID = image.ID,
                            Name = image.Name,
                            Data = image.IMAGE_DATA.Data
                        };
            return await query.ToListAsync(token);
        }
```

### Expected behavior
Query uses all network capacity and runs similar to SSMS

### Further technical details
"Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.9"
Microsoft Windows 10 Home 10.0.19043 N/A Build 19043

**Comment by roji** [comment] 2022-09-17 08:36
Duplicate of https://github.com/dotnet/SqlClient/issues/593

**Comment by roji** [comment] 2022-09-17 08:37
Try using synchronous APIs instead of asynchronous APIs - there's a known issue where SqlClient's async support has some severe performance issues (https://github.com/dotnet/SqlClient/issues/593). In any case, this is unrelated to EF itself, which is just built on top of SqlClient.

**Comment by roji** [comment] 2022-09-17 08:38
There is a known performance issue with SqlClient's async I/O and large values. Try switching to the sync API.

**Comment by janseris** [comment] 2022-09-17 15:45
@roji Thanks. Is this documented somewhere so I can read more what to pay attention to (e.g. the suggested limit or does it happen also for query with a lot of small items?).
Also, I remembered that SQL Server Management Studio sort of has cancel function for queries as well. 
Does the cancellation there work differently than here?

**Comment by ErikEJ** [comment] 2022-09-17 15:57
SSMS does not use this driver (,yet). It uses System.Data.SqlClient with some magic sprinkled on top.

**Comment by lcheunglci** [comment] 2022-09-20 18:14
We currently don't have a known issue document, but we are aware of the performance issue with async on non-windows platform.  We can consider adding a known issues section in the Wikis section. 

Closing it as a duplicate of #593

**Closed by lcheunglci** 2022-09-20 18:14 UTC

**Comment by janseris** [comment] 2022-09-20 19:35
@lcheunglci OK. BTW this is Windows platform.

**Comment by lcheunglci** [comment] 2022-09-20 20:50
I mean it's not an issue with .NET Framework version of MDS, but with .NET Core version of MDS.
