### ISSUE TITLE
Active Directory Managed Identity authentication method not working

### ISSUE THREAD

**Issue by Yangsh-w** [dotnet/SqlClient#1072] opened 2021-05-14 05:55 UTC
### Describe the bug
While using the Active Directory Managed Identity authentication method in .NET 4.7, the connection is not working.
Same connection is working in Core 3.1.

```
Exception message:
No Managed Identity found for specified ClientId/ResourceId/PrincipalId.
Stack trace:
Microsoft.Data.SqlClient.SqlException: Received a non-retryable error. Identity Response Code: BadRequest, Response: {"StatusCode":400,"Message":"No Managed Identity found for specified ClientId/ResourceId/PrincipalId.","CorrelationId":"2744aeb6-881e-4f69-b9c0-7151a107607f"}at Microsoft.Data.SqlClient.AzureManagedIdentityAuthenticationProvider.<AcquireTokenAsync>d__13.MoveNext()
```

### To reproduce
Create a .NET 4.7 function app with the code below and publish it to Azure V1 function app.

```c#
using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Data.SqlClient;

namespace FunctionApp2
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log)
        {
            log.Info("C# HTTP trigger function processed a request.");

            var str = Environment.GetEnvironmentVariable("sqldb_connection");

            try {
                using (SqlConnection conn = new SqlConnection(str))
                {
                    conn.Open();
                    string t = DateTime.Now.ToString();
                    var text = "INSERT INTO timetest VALUES('"+t+"');";

                    using (SqlCommand cmd = new SqlCommand(text, conn))
                    {
                        // Execute the command and log the # rows affected.
                        var rows = await cmd.ExecuteNonQueryAsync();
                        log.Info("1 row" + t + " inserted");
                    }
                }
            }
            catch (Exception ex)
            {
                log.Info(ex.ToString());
            }

            return null;
        }
    }
}
```
Add User assigned managed Identity to that azure function app, assign owner role of the azure SQL database to that Identity.
Add the app setting sqldb_connection with the connection string as its value to the azure function app.
Connection string:
```
Server=mysqlserver.database.windows.net,1433;database=mydatabase;User Id=object id of the Identity;Authentication=Active Directory Managed Identity;
```

### Expected behavior
A new record get inserted into my database table.

### Further technical details
.NET version: 4.7
Microsoft.Data.SqlClient version: 2.1.2

**Comment by cheenamalhotra** [comment] 2021-05-14 16:38
Hi @Yangsh-w 

Could you test the same with latest preview [v3.0.0-preview2](https://www.nuget.org/packages/Microsoft.Data.SqlClient/3.0.0-preview2.21106.5)? We are now using Azure.Identity to fetch token.

**Starting v3.0.0-preview2**, we accept "Client Id" instead. Plz ensure to pass "Client Id" of User-Assigned Managed Identity to connection string with new driver:

```
Server=**;database=**;User Id=CLIENT ID of the Identity;Authentication=Active Directory Managed Identity;
```

Let us know your results.

**Comment by Yangsh-w** [comment] 2021-05-17 02:33
Hi @cheenamalhotra ,

Thanks for your reply!

I tried the [3.0.0-preview2.21106.5](https://www.nuget.org/packages/Microsoft.Data.SqlClient/3.0.0-preview2.21106.5) and encountered a new error:
_System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.at System.Threading.Tasks.ValueTask`1.get_IsCompleted()at Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider.<AcquireTokenAsync>d__19.MoveNext()_

I've installed the `System.Runtime.CompilerServices.Unsafe` in NuGet package management, both version 5.0.0 and 4.6.0, the error persists.

Could you please help check on that?

Many thanks!

**Comment by cheenamalhotra** [comment] 2021-05-17 17:30
Hi @Yangsh-w,

Could you try referencing System.Runtime.CompilerServices.Unsafe **v4.5.1** or add a binding redirect?

**Comment by Yangsh-w** [comment] 2021-05-18 01:44
Thanks @cheenamalhotra!

I tried to update the `System.Runtime.CompilerServices.Unsafe` to lower version(`4.5.1,2,3`), but the build will not pass because of the dependencies link:
![image](https://user-images.githubusercontent.com/76461730/118577415-f1005e80-b7bc-11eb-84c0-d58342eef7bb.png)
Seems the lowest version of  `System.Runtime.CompilerServices.Unsafe` we could use for` Microsoft.Data.SqlClient 3.0.0-preview2.21106.5` is `v4.6.0`.

I was also trying to implement the[ binding redirect](https://nickcraver.com/blog/2020/02/11/binding-redirects/#the-fix-if-youre-using-net-framework), but since this is an azure function, we [do not have web.config file](https://stackoverflow.com/a/43242579), the binding redirects is also not working.

Is there any other resolution regarding this issue for a .NET framework function app?

Much appreciated!

**Comment by Yangsh-w** [comment] 2021-05-20 08:09
Hello @cheenamalhotra ,
Good day! Hope you are doing well!
May I know if there is any other approaches we could try to make this work?

**Comment by cheenamalhotra** [comment] 2021-05-20 23:42
Hi @Yangsh-w 

I'm going to try this myself and will let you know as I find a solution. Would you like to share your repro to compare if anything strikes as an obvious factor?

**Comment by Yangsh-w** [comment] 2021-05-21 04:41
Hi @cheenamalhotra, thanks for your update!

I have uploaded the project that could reproduce this issue at [my repo](https://github.com/Yangsh-w/sqlclienttest). It's just a demo project without any sensitive information in it.
Here is the .csproj I am currently using,
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AzureFunctionsVersion>v1</AzureFunctionsVersion>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="3.0.0-preview1.21075.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.24" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```
If more information is required, please let me know. Thanks!

**Comment by ErikEJ** [comment] 2021-05-21 04:51
You can manage binding redirects from code...

**Comment by Yangsh-w** [comment] 2021-05-21 04:57
Hi @ErikEJ , thank you for your insights! Is it possible we can have a sample about binding redirects from code?
I've shared my current function code in the original post, may I know how should I modify it to enable binding redirects? Thanks a lot!

**Comment by Yangsh-w** [comment] 2021-05-21 06:21
Hi @cheenamalhotra , @ErikEJ ,

I tried following this [article ](https://codopia.wordpress.com/2017/07/21/how-to-fix-the-assembly-binding-redirect-problem-in-azure-functions/)and enabled binding redirects in the function code.

After a redeployment, the error about 'Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1,' is still there. 
I have also tried the latest release [3.0.0-preview3.21140.5](https://www.nuget.org/packages/Microsoft.Data.SqlClient/3.0.0-preview3.21140.5), but the issue persists.
_System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.at System.Threading.Tasks.ValueTask`1.get_IsCompleted()at Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider.<AcquireTokenAsync>d__19.MoveNext()_

I have also updated [my repo](https://github.com/Yangsh-w/sqlclienttest).

**Comment by ErikEJ** [comment] 2021-05-21 09:41
Try adding an explicit reference to a package that contains that version

**Comment by Yangsh-w** [comment] 2021-05-25 01:40
Hi @ErikEJ , according to [this thread](https://stackoverflow.com/a/62770487), the 4.0.4.1 assembly version corresponds to the NuGet package Version 4.5.3. While the lowest NuGet package version of `System.Runtime.CompilerServices.Unsafe` that `Microsoft.Data.SqlClient 3.0.0-preview2.21106.5` could accept is 4.6.0, as mentioned [here](https://github.com/dotnet/SqlClient/issues/1072#issuecomment-842759896). So I am not sure how I can add that reference in the project,,, 

Hi @cheenamalhotra , any luck with your test? If there is anything else needed, please let me know.

**Comment by ErikEJ** [comment] 2021-05-25 04:38
O thought you were using 2.1.2?

**Comment by Yangsh-w** [comment] 2021-05-25 04:48
For 2.1.2, I do not have the `System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1` issue. It was just saying `No Managed Identity found for specified ClientId/ResourceId/PrincipalId.`.
It was suggested by @cheenamalhotra to use the preview version instead, where I encountered the `System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1` issue.

**Comment by cheenamalhotra** [comment] 2021-05-25 17:28
Hi @Yangsh-w 

I agree with your findings and repro and I'm able to reproduce the issues you described above. But given that, we're merely a mediator between **Azure.Identity and Azure Functions SDK** in a .NET Framework App.

If you take SqlClient APIs out of the picture, the issue persists with these libraries being not compatible. e.g you can test with this simple API call from **Azure.Identity** library in the same program:
```cs
AccessToken token = new DefaultAzureCredential().GetToken(new TokenRequestContext());
```
and install only these 2 packages in your csproj:
```xml
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.3.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.38" />
  </ItemGroup>
```
Due to this, I would recommend opening issues with your repro and findings with either or both [Azure.Functions SDK](https://github.com/Azure/Azure-Functions/issues) and [Azure.Identity - Azure SDK for .NET](https://github.com/Azure/azure-sdk-for-net/issues) teams to discuss further and reach a solution.

**Comment by Yangsh-w** [comment] 2021-05-26 02:44
Thank you @cheenamalhotra for the tests and information shared!

As I just tested, with only **Azure.Identity 1.3** and **Azure function v1 SDK**, the function will also throw the exception `System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.`

So as I understand, to fix the original issue `No Managed Identity found for specified ClientId/ResourceId/PrincipalId.`, I need to use the preview version of the **Microsoft.Data.SqlClient**.
But the preview version **Microsoft.Data.SqlClient** requires **v1.3 Azure.Identity**  which has compatibility issue with **Azure function v1 SDK**, it will cause the 4.0.4.1 issue.

Is that correct?

**Comment by Yangsh-w** [comment] 2021-05-26 03:32
Azure.Identity issue created https://github.com/Azure/azure-sdk-for-net/issues/21361

**Comment by Yangsh-w** [comment] 2021-05-28 08:49
Hi @cheenamalhotra ,

Sorry to bother again! After I consulted with the Azure Identity team, I now have enabled the binding redirects properly. The 4.0.4.1 issue is not showing anymore.

But we are facing another new issue - **Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.Status: 400 (Bad Request)**. 
Seems the SqlClient is not properly passing the client Id for authentication.

I have updated [my repo](https://github.com/Yangsh-w/sqlclienttest), you could download for test if needed.

The current connection string I am using:
`Server=myserver.database.windows.net,1433;database=mydb;User Id=<client Id of my identity>;Authentication=Active Directory Managed Identity;`

My identity has owner access to the SQL Server.
![image](https://user-images.githubusercontent.com/76461730/119957028-4b2acc00-bfd4-11eb-9dea-4b5b0b206587.png)

We are trying to implement Active Directory Managed Identity authentication method, but we've been facing new issues while resolving them..

Really appreciate if you could have a check on this. 

Thanks in advance!

**Comment by cheenamalhotra** [comment] 2021-05-28 17:32
@Yangsh-w 

Do you also see your identity registered as a Login on the **database** "mydb" that  you're connecting to? 
If not already done, please execute this query on your **Azure SQL Database** (not master db):
```
CREATE LOGIN [NameOfFunctionApp] FROM EXTERNAL PROVIDER; -- systemassigned
CREATE LOGIN [NameOfManagedIdentity] FROM EXTERNAL PROVIDER;  -- userassigned (Identity registered to Function App)

```

You can then grant access to this Login account as you need to access resources.

Alternatively, you can also try to execute below Azure.Identity API directly in your app that we do to investigate if there's an issue with setup. If you do get access token, please provide the Token to SqlConnection.AccessToken property to connect in this case:
https://github.com/dotnet/SqlClient/blob/f3515917c053c3ee6783beaff3901df5c0f0dfe6/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs#L145

**Comment by Yangsh-w** [comment] 2021-05-31 06:00
Thank you @cheenamalhotra for your update!

I'm using user assigned identity and the identity is not registered as a Login for my Azure database.
I was trying to run the T-SQL command shared with my admin account connected to the DB, but it's failing for error - **Failed to execute query. Error: Incorrect syntax near 'PROVIDER'.**. Same error in SSMS connecting to this Azure DB.
![image](https://user-images.githubusercontent.com/76461730/120146550-da73f180-c217-11eb-8de8-cff449992188.png)

And sorry I don't get which Azure.Identity API we are talking about.. I tried the code to get AccessToken in my function, but there are too many parameters(like tokenCredentialOptions, tokenRequestContext and cts) missing in it, so I guess we cannot execute it directly?

**Comment by ErikEJ** [comment] 2021-05-31 06:19
It is "CREATE USER" (not CREATELOGIN) https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi#use-managed-identity-connectivity

**Comment by Yangsh-w** [comment] 2021-05-31 06:49
Hi @ErikEJ, Thanks for checking!

I have registered my identity as the Users at the beginning, sorry not mentioning that before.
![image](https://user-images.githubusercontent.com/76461730/120150357-8c61ec80-c21d-11eb-935f-c60d292291bb.png)

But unfortunately, the function is not working. It is throwing the error **'Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.Status: 400 (Bad Request)'**.

Allow me clarify our current situation as below:
**Background:**
I have a v1 Azure function(dotnet framework 4.7) and an Azure SQL DB.
I am using Microsoft.Data.SqlClient in the function code with authentication method = Active Directory Managed Identity to connect to the SQL DB.
The function app is integrated with a user assigned identity which has owner access to the Azure SQL DB.
The connection string for the function is `Server=mysqlserver.database.windows.net,1433;database=mysqldb;User Id=<client_id of the identity>;Authentication=Active Directory Managed Identity;`
**Issues:**
At first, with Microsoft.Data.SqlClient version = 2.1.2, the function is throwing error - **No Managed Identity found for specified ClientId/ResourceId/PrincipalId.**
Then I changed  the version of this package to 3.0.0-preview2.21106.5 as suggested, and I'm now seeing a different new error - **'Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.Status: 400 (Bad Request)'**.

I will build new resources to test all things again, just in case I messed anything during previous tests.

**Comment by cheenamalhotra** [comment] 2021-06-02 19:44
It seems like a setup issue to me.
Could you test the same steps in a .NET Core function app? Just to ensure you're doing the right steps and it might be something related to application environment?

**Comment by Yangsh-w** [comment] 2021-06-03 08:16
Thank you @cheenamalhotra for the suggestion!

The same process is working in .NET core function app. For core app, the Microsoft.Data.SqlClient v2.1.2 is working well, no need to use preview version. This was tested before, I could make another test if required.

Also, the new test I mentioned in my last post, it is not working too. But with a different error - **Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.**.. I tried to use the same binding redirect to fix this but not working. Still working on this...

The test steps:
1. Create a new Azure SQL Server and a new dotnet function app in Azure portal.
2. Connect to Azure SQL DB and create a custom table for test, so that my function could insert some value to the DB.
3. Create a User Assigned Identity, add owner access to the SQL Server for this identity and bind it to the function app.
4. In the SQL DB, use **CREATE USER [NameOfManagedIdentity] FROM EXTERNAL PROVIDER;** to create a user for identity in the database.
5. Create a dotnet 4.7 function app locally, add code to use Microsoft.data.SqlClient(3.0.0-preview2.21106.5) to accessing the Azure DB, add code for binding redirect to avoid unsafe 4.0.4.1 issue and publish to the Azure Function app.
6. Configure the app setting for Azure Function app, add connection string **Server=mytestsqlserver.database.windows.net,1433;database=mytestsqldb;User Id=Client_Id of my test user identity;Authentication=Active Directory Managed Identity;** and binding redirect setting.
7. Test the function in Azure portal.

**Comment by cheenamalhotra** [comment] 2021-06-03 17:33
Hi @Yangsh-w this has to be do with the nature of Function App environment. Managed Identity based tokens are acquired from environment where IMDS service runs. And if the service cannot identify the identity, it's probably an environment issue.

Your code and steps seems to be correct and if they work in .NET Core function app, they should work with .NET Framework function app too.

Just to mention, it does work with a Console app targeting .NET Framework as we run our tests daily in Azure VMs. This problem is specific to Function App targeting .NET Framework and for that I'd recommend reaching to [Azure Function SDK](https://github.com/Azure/Azure-Functions/issues) team.

There's nothing driver library can do here.

**Comment by Yangsh-w** [comment] 2021-06-04 07:03
Thank you @cheenamalhotra for your test and advice!

I will consult with the Azure Function side as suggested.

**Comment by cheenamalhotra** [comment] 2021-07-08 17:59
Closing as query resolved from our end.

**Closed by cheenamalhotra** 2021-07-08 17:59 UTC

**Comment by ClassyCircuit** [comment] 2024-06-03 11:53
> Thank you @cheenamalhotra for your test and advice!
> 
> I will consult with the Azure Function side as suggested.

@Yangsh-w did you ever get this resolved? I am facing the same issue.
