### ISSUE TITLE
PlatformNotSupportedException on Locally executing function app.

### ISSUE THREAD

**Issue by zippy1981** [dotnet/SqlClient#115] opened 2019-05-31 16:04 UTC
### Describe the bug
Upon invoking the SqlConnection("connection string") constructor in an Azure Function running in .net core 22 I get  `System.PlatformNotSupportedException: 'Microsoft.Data.SqlClient is not supported on this platform.'`

```
System.PlatformNotSupportedException
  HResult=0x80131539
  Message=Microsoft.Data.SqlClient is not supported on this platform.
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at FunctionApp2.Function1.<Run>d__4.MoveNext() in C:\Users\Justin Dearing\source\repos\FunctionApp2\FunctionApp2\Function1.cs:line 38
```

Before that exception I get  `System.IO.FileNotFoundException`:

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.Data.SqlClient, Version=1.0.19128.1, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5'. The system cannot find the file specified.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.Azure.WebJobs.Script.Description.FunctionAssemblyLoadContext.TryLoadRuntimeAssembly(AssemblyName assemblyName, Assembly& assembly) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\FunctionAssemblyLoadContext.cs:line 235
```

The exception is  thrown in the azure function runtime [FunctionAssemblyLoadContext.TryLoadRuntimeAssembly() line 235](https://github.com/Azure/azure-functions-host/blob/04f8d662c3ebcec28433b08399873bf8b94f8a70/src/WebJobs.Script/Description/DotNet/FunctionAssemblyLoadContext.cs#L235)

Using procmon.exe, its definitely finding the file.
![image](https://user-images.githubusercontent.com/146930/58718610-e237fb80-839b-11e9-99e6-d682811d9fa9.png)

### To reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Microsoft.Azure.Services.AppAuthentication;
using System.Text;

namespace FunctionApp2
{
    public static class Function1
    {
        private const string ConnectionStringKey = "SqlConnectionString";
        private const string SqlTokenTenantKey = "SqlTenant";
        private const string AzureSqlDbResource = "https://database.windows.net/";

        private static string ConnectionString =>
            Environment.GetEnvironmentVariable(ConnectionStringKey, EnvironmentVariableTarget.Process);

        private static string SqlTokenTenant =>
            Environment.GetEnvironmentVariable(SqlTokenTenantKey, EnvironmentVariableTarget.Process);

        private static async Task<string> GetAccessTokenAsync()
        {
            var azureServiceTokenProvider = new AzureServiceTokenProvider();
            return await azureServiceTokenProvider.GetAccessTokenAsync(AzureSqlDbResource, SqlTokenTenant);
        }

        [FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            var sb = new StringBuilder();
            log.LogTrace("Creating Database connection object.");
            //using (var cn = new System.Data.SqlClient.SqlConnection(ConnectionString))
            using (var cn = new Microsoft.Data.SqlClient.SqlConnection(ConnectionString))
            {
                log.LogTrace("Accquiring Access Token", cn.AccessToken);
                cn.AccessToken = await GetAccessTokenAsync();
                log.LogTrace("Accquired Access Token {token}", cn.AccessToken);
                using (var cmd = cn.CreateCommand())
                {
                    cn.Open();
                    cmd.CommandText = "SELECT * FROM sys.tables";
                    using (var sqlRdr = cmd.ExecuteReader())
                    while (sqlRdr.Read())
                    {
                            for (var i= 0; i < sqlRdr.FieldCount; i++)
                            {
                                sb.AppendFormat("{0},", sqlRdr[i]);
                            }
                            sb.AppendLine();
                        }
                    cn.Close();
                }
            }

            var result = new ContentResult();
            result.Content = sb.ToString();
            return result;
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.60.6" />
    <PackageReference Include="FlatFiles" Version="4.5.0" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.0.3" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="1.0.19128.1-Preview" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.28" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

### Expected behavior
I expect to instantiate the sqlconnection object.

### Further technical details
Microsoft.Data.SqlClient version: 1.0.19128.1-Preview
.NET target: Core 2.2
SQL Server version: Azure v12
Operating system: Windows 10.0.17134.765
Azure Function Tools: 2.22.0
Azure Functions Core Tools (2.7.1158 Commit hash: f2d2a2816e038165826c7409c6d10c0527e8955b)
Function Runtime Version: 2.0.12438.0

**Additional context**

Created the project in VS 2017 and moved it to 2019.

**Comment by AfsanehR** [comment] 2019-05-31 16:08
Thank you for providing repro and complete information. Will investigate this and get back to you. In the meantime, could you share if you are getting the same exception with using System.Data.SqlClient or is this only happening when using Microsoft.Data.SqlClient?

**Comment by zippy1981** [comment] 2019-05-31 17:43
@AfsanehR Thank you for your incredibly quick response!

When I use System.Data.SqlClient 4.6.1 it actually does work.

Secondly, I updated the code in the issue to fix some bugs that occurred after that line, and to reflect having System.Data.SqlClient as a nuget package.

**Comment by ErikEJ** [comment] 2019-05-31 19:08
I looks like fun.exe loads System.Data.SqlClient. have you tried removing the Dapper and System.Data.SqlClient dependencies?
And you request Alway Encrypted in ypur connection string?

**Comment by zippy1981** [comment] 2019-06-01 05:54
@ErikEJ I removed Dapper and System.Data.SqlClient. System.Data.Sqlclient.dll is not in the bin folder anymore. It is in the func.exe folder though (C:\Users\Justin Dearing\AppData\Local\AzureFunctionsTools\Releases\2.22.0\cli).

One other interesting thing I noticed. It tries to load an assembly called Microsoft.Data.Sqlclient.resources. Could that be part of the problem?

**Comment by jeffhollan** [comment] 2019-06-01 09:00
I assume 2.7.0 may depend on .NET Core runtime >= 2.2.4?  Right now we [are using 2.2.3](https://github.com/Azure/azure-functions-host/issues/4006#issuecomment-482226609) and the local tools use a self-contained build targeting that version as that's what's running in the service.  2.2.5 is just rolling out so we should be able to update tools to match and potentially unblock this, but would be good to confirm a dependency on newer than 2.2.3 that would explain this

**Comment by zippy1981** [comment] 2019-06-01 12:33
@jeffhollan thank for looking at this. Since the System.Data.SqlClient version 4.6.X has similar issues (not locally, but only when you deploy the code, I'd like to contribute some integration tests so that both the Azure Functions team, and the SqlClient team knows if SqlClient breaks on Azure functions. 

In what repo do these tests belong? Basically I'm envisioning three tests:

* Run a func.exe with code similar to mine from inside the CI, and make GET calls to it.
* Deploy that to a function to Azure and make GET calls to it.
* Deploy the function to azure on a function docker container and make GET calls to it. 

Also, if someone can figure out WHERE the exception is generated, I'll try to contribute a patch to make the exception more useful (e.g. say what version of what component isn't compatible).

**Comment by peterbae** [comment] 2019-07-29 22:25
Hi @zippy1981,

This looks like the issue is stemming from how Azure Functions doesn't copy the dll to the output directory, details of which can be found here: [issue #4304](https://github.com/Azure/azure-functions-host/issues/4304). They've suggested a "workaround" for which the discussion is still ongoing. I've added the below snippet to my `.csproj` and saw that the error is no longer reproducible in my local Azure function app environment. Could you try the same and let me know if this solves your issue / is an acceptable solution? Thanks.

```
  <ItemGroup>
    <None Include="$(USERPROFILE)\.nuget\packages\microsoft.data.sqlclient\1.0.19189.1-preview\runtimes\win\lib\netcoreapp2.1\Microsoft.Data.SqlClient.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="CopyToBin" BeforeTargets="Build">
    <Copy SourceFiles="$(USERPROFILE)\.nuget\packages\microsoft.data.sqlclient\1.0.19189.1-preview\runtimes\win\lib\netcoreapp2.1\Microsoft.Data.SqlClient.dll" DestinationFolder="$(OutputPath)\bin" />
  </Target>
```

**Comment by peterbae** [comment] 2019-08-14 22:29
Hi @zippy1981, were you able to test out the details I provided above?

**Comment by cheenamalhotra** [comment] 2019-08-20 22:19
Closing this issue as it appears to be Azure Function problem.

**Closed by cheenamalhotra** 2019-08-20 22:19 UTC
Labels: External

**Comment by AidanTfL** [comment] 2019-08-24 00:36
Can anyone give an update on this, and any known workarounds in the meantime?

I have the same issue in a .NET Core Service Bus Queue Triggered Azure Function with Microsoft.Data.SqlClient Version 1.0.19221.1-Preview installed.

**Comment by AidanTfL** [comment] 2019-08-24 00:38
> Closing this issue as it appears to be Azure Function problem.

Hi @cheenamalhotra I have the same issue with Microsoft.Data.SqlClient Version 1.0.19221.1-Preview installed. Can you please give an update? Are there any known workarounds?

**Comment by cheenamalhotra** [comment] 2019-11-27 23:10
FYI, uploaded example to verify:
https://github.com/cheenamalhotra/azurefunctions-sqlclient-example

**Comment by ngg** [comment] 2019-11-30 06:09
We're using .NET Core 2.1 with Functions v2 and have the same issue when switching to Microsoft.Data.SqlClient. Should that work?

**Comment by cheenamalhotra** [comment] 2019-11-30 06:17
@ngg 

Yes that works too, the culprit is "Microsoft.Net.SDK.Functions" **v1.0.29**, if you may upgrade to later versions in your package reference, please do so.

Tested versions are **1.0.30-beta4** and **3.0.0-preview2**.

**Comment by ngg** [comment] 2019-12-02 15:26
@cheenamalhotra Thanks, but updating from 1.0.29 to 1.0.30-beta4 breaks my function even without updating to Microsoft.Data.Sqlclient. I've reported an issue about that here: https://github.com/Azure/azure-functions-vs-build-sdk/issues/356
