### ISSUE TITLE
Azure Cloud Service (classic) with EF Core 3.1 => sni.dll not found

### ISSUE THREAD

**Issue by VeselovAndrey** [dotnet/SqlClient#407] opened 2020-02-04 10:13 UTC
### Describe the bug
Using EF Core 3.1 with Azure Cloud Service (worker role) ends with 
Failed to load ...\SniBugDemo\EFCore31Demo.Azure\csx\Debug\roles\EFCore31Demo.WorkerRole\approot\x64\SNI.dll

Stack trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at EFCore31Demo.WorkerRole.WorkerRole.Run() in D:\Projects\GitHub\SniBugDemo\EFCore31Demo.WorkerRole\WorkerRole.cs:line 21
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.StartRoleInternal()
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<StartRole>b__2()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

As I can say looks like x64\SNI.dll and x86\SNI.dll were not copied into Azure Cloud Service project.
For example: This is Worker Role DLL "bin" project folder
![image](https://user-images.githubusercontent.com/13725003/73735043-35efb580-4771-11ea-8b4a-d1b1ae5a2ab3.png)

And this is Azure project folder.
![image](https://user-images.githubusercontent.com/13725003/73735091-4d2ea300-4771-11ea-9864-e2c9ab825616.png)

As you can see x64 and x86 folders are missing.

### To reproduce
I put source code here:
https://github.com/VeselovAndrey/SniBugDemo

Run "EFCore31Demo.Azure" to reproduce error (you even don't need DB to see an error)
Console app here just to make sure that code is working.

Same happens on publishing to Azure Cloud (it fails in cloud with same message).

### Expected behavior
DLLs must be copied to Azure project and package

### Further technical details
Microsoft.Data.SqlClient package version: both 1.0.19235.1 and 1.1.0
.NET target: .NET Framework 4.7.2
SQL Server version: LocalDB, SQL Server Azure
Operating system: Windows 10 (dev PC) Windows Server in Azure

**Comment by cheenamalhotra** [comment] 2020-02-04 23:45
Hi @VeselovAndrey 

I am able to reproduce the problem and can see why it's happening.

Looks like you're using "Microsoft.WindowsAzure.targets" which is responsible to copy your Worker files from `EFCore31Demo.WorkerRole\bin\Debug` folder to intermediate path `\EFCore31Demo.Azure\obj\Debug\EFCore31Demo.WorkerRole\`. But it leaves out SNI DLLs in x86 and x64 folders, and copies the rest.

In order to support this, we have to add support to copy SNI files within target "CopyRoleFiles".
We're working on adding the same, could you verify by appending below targets in your "EFCore31Demo.Azure.ccproj" file:

```proj
<Import Project="..\packages\Microsoft.Data.SqlClient.SNI.1.1.0\build\net46\Microsoft.Data.SqlClient.SNI.targets" Condition="Exists('..\packages\Microsoft.Data.SqlClient.SNI.1.1.0\build\net46\Microsoft.Data.SqlClient.SNI.targets')" />
<Target Name="CopySNIRoleFiles"
        Condition="'@(WorkerRoleReferences)' != ''"
        Inputs="@(SNIFiles)"
        Outputs="@(SNIFiles -> '$(_IntermediateWorkerOutputPath)%(RecursiveDir)%(Filename)%(Extension)')">
  <PropertyGroup>
    <_IntermediateWorkerOutputPath>%(WorkerRoleReferences.OutputDir)</_IntermediateWorkerOutputPath>
  </PropertyGroup>
  <Copy SourceFiles="@(SNIFiles)"
        DestinationFiles="@(SNIFiles -> '$(_IntermediateWorkerOutputPath)%(RecursiveDir)%(Filename)%(Extension)')" />
</Target>
<PropertyGroup>
  <CollectRoleFilesDependsOn>
    $(CollectRoleFilesDependsOn);
    CollectSNIFiles;
  </CollectRoleFilesDependsOn>
  <CopyRoleFilesDependsOn>
    $(CopyRoleFilesDependsOn)
    CopySNIRoleFiles;
  </CopyRoleFilesDependsOn>
</PropertyGroup>
```

**Comment by VeselovAndrey** [comment] 2020-02-05 10:10
@cheenamalhotra Thanks for response! 

I tested your proposal on test project and it works. I also tested same fix with deployment to Azure - it also works. 

Thanks for this fix. I hope new NuGet package will be released soon. :)

**Comment by cheenamalhotra** [comment] 2020-02-11 18:41
Hi @VeselovAndrey 

[Microsoft.Data.SqlClient.SNI v1.1.1](https://www.nuget.org/packages/Microsoft.Data.SqlClient.SNI/1.1.1) has been released, please add reference to the same to get support for Azure Cloud SDK targets.

Closing the issue as fixed and delivered.

**Closed by cheenamalhotra** 2020-02-11 18:41 UTC
Labels: Enhancement

**Comment by marisks** [comment] 2020-02-14 16:46
I have the same issue and the fix doesn't work for me. But there are a few differences:
1. I am using the new project format:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.ServiceBus" Version="2.2.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="1.1.0" />
    <PackageReference Include="Microsoft.Data.SqlClient.SNI" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.27" />
  </ItemGroup>
  <Import Project="..\..\packages\Microsoft.Data.SqlClient.SNI.1.1.1\build\net46\Microsoft.Data.SqlClient.SNI.targets" Condition="Exists('..\..\packages\Microsoft.Data.SqlClient.SNI.1.1.1\build\net46\Microsoft.Data.SqlClient.SNI.targets')" />
</Project>
```
2. This is Azure Function project.

Is there anything else I should do to fix it?

**Comment by cheenamalhotra** [comment] 2020-02-14 17:43
@marisks 

I think you might be using `dotnet build` where another "bin" directory is created inside "bin\Debug\net472" whereas if you perform `msbuild` there is no additional "bin" folder and x86 and x64 folders are in sync with other dlls.

I think this is an inconsistency from the msbuild and dotnet build tools, but in order to support the same we'd have to consider this "DestinationSubDirectory" attribute as well. For now, I'd recommend using `msbuild` instead, while we investigate if there are more such cases. I'll open a different issue to track this case.

Let us know if find any more such behaviors, by opening a new ticket.

**Comment by marisks** [comment] 2020-02-15 09:37
@cheenamalhotra Thanks! This sounds like the case I have. I will try with MSBuild.

**Comment by marisks** [comment] 2020-02-17 08:35
@cheenamalhotra Using `msbuild` didn't help. It still creates bin folder inside "bin\Debug\net472" and SNI.dll folders are not copied there.
I will try to upgrade to Azure Functions v2.

**Comment by VeselovAndrey** [comment] 2020-03-06 09:22
@cheenamalhotra Sorry for late response but I just have time to update package. And its look like it not works. Can you explain what I did wrong? Example update to 1.1.1
https://github.com/VeselovAndrey/SniBugDemo (branch master-1-1-1)
