### ISSUE TITLE
Unable to load DLL 'Microsoft.Data.SqlClient.SNI.x86.dll'

### ISSUE THREAD

**Issue by jonathan-timothy-mason** [dotnet/SqlClient#727] opened 2020-09-16 16:12 UTC
Hi,

I have migrated our .NET 4.7.2 x86 solution to Microsoft.Data.SQLClient v2.0.1 using Nuget.

When running our program in Windows 10 64-bit, the error below occurs:
Unable to load DLL 'Microsoft.Data.SqlClient.SNI.x86.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

If I look at the bin folder of our project that deals with the database, which has a dependency on Microsoft.Data.SQLClient, I find:
Microsoft.Data.SqlClient.dll
Microsoft.Data.SqlClient.SNI.x86.dll
Microsoft.Data.SqlClient.SNI.x64.dll

However, if I look at the bin folder of our executable project, which does not have a dependency on Microsoft.Data.SQLClient, but only on our database project, I only find:

Microsoft.Data.SqlClient.dll

If I copy the missing assemblies into the executable bin folder, the problem is solved.

I assume this is a problem with Nuget. What is the best way to solve this without manually copying the missing dependecnies. We have several exeutables.

Upgrading to Nuget 5 didn't help.

Thanks
Jon

**Comment by ErikEJ** [comment] 2020-09-16 16:19
Reference the MDS package directly in the .exe projects.

**Comment by karinazhou** [comment] 2020-09-16 16:46
Hi @jonathan-timothy-mason , as what @ErikEJ  suggested, you need reference the Microsoft.Data.SqlClient nuget package directly in your executable project so the nuget manager is able to copy SNI dlls to the target bin folder. Please feel free to try it and see whether it works.

**Comment by jonathan-timothy-mason** [comment] 2020-09-17 08:33
Thanks for your replies @ErikEJ  and @karinazhou. To sum up, anything with a dependency on a project using Microsoft.Data.SQLClient doesn't get Microsoft.Data.SqlClient.SNI.xxx.dll copied to it's bin folder. Is that right?

Do you think unit test projects that have a dependency on our database project would also need to be made to directly referebce Microsoft.Data.SQLClient too?

Thanks a lot.
@jonathan-timothy-mason

**Comment by ErikEJ** [comment] 2020-09-17 09:04
>> To sum up, anything with a dependency on a project using Microsoft.Data.SQLClient doesn't get Microsoft.Data.SqlClient.SNI.xxx.dll copied to it's bin folder. Is that right?

No, that is not right. This works as expected in most scenarios, so please provide a repro solution.

**Comment by jonathan-timothy-mason** [comment] 2020-09-24 09:48
Our projects typically reference our data access project, which itself directly references Microsoft.Data.SQLClient. I've included a document, which lists all our top-level projects, and says which experience the "Unable to load DLL 'Microsoft.Data.SqlClient.SNI.x86.dll'" error.

Our solution has 66 projects and I don't think it would be possible to simplify it into a form that I can send to you, which would still accurately reproduce the same problem.

[Top-Level Projects and “Unable to load DLL 'Microsoft.Data.SqlClient.SNI.x86.dll'” Error.pdf](https://github.com/dotnet/SqlClient/files/5274995/Top-Level.Projects.and.Unable.to.load.DLL.Microsoft.Data.SqlClient.SNI.x86.dll.Error.pdf)

**Comment by ErikEJ** [comment] 2020-09-24 12:00
Please provide a .csproj file of a failing "top level" project.

**Comment by jonathan-timothy-mason** [comment] 2020-09-24 15:32
Hi @ErikEJ, attached is the project file for our main Windows Forms project that does not reference Microsoft.Data.SQLClient directly, but does reference the other projects MatrixDAL, MatrixBLL, MatrixBLLBase, MatrixBllDalShared, which do directly reference it directly.

[UI - Windows.zip](https://github.com/dotnet/SqlClient/files/5277249/UI.-.Windows.zip)

**Comment by karinazhou** [comment] 2020-09-30 23:54
@jonathan-timothy-mason   I looked at the pdf file you attached and all the failing scenarios, except for the VSTest one, can be fixed by directly adding driver's Nuget reference to the top-level project. 

This is the known issue for native SNI.dll. I think, for now, you may have to directly reference driver nuget in your main project as a workaround.

**Comment by jonathan-timothy-mason** [comment] 2020-10-01 08:27
OK, thanks for your help @karinazhou, we'll probably wait until it's been fixed to avoid all the unnecessary references.

**Comment by cheenamalhotra** [comment] 2020-10-07 01:27
Hi @jonathan-timothy-mason 

As I replied here: https://github.com/dotnet/SqlClient/issues/446#issuecomment-704516208
The same applies to any .NET Framework application, could you verify and confirm the feasibility to import SNI targets?

**Comment by aibrahim2020** [comment] 2020-11-08 10:02
> @jonathan-timothy-mason I looked at the pdf file you attached and all the failing scenarios, except for the VSTest one, can be fixed by directly adding driver's Nuget reference to the top-level project.
> 
> This is the known issue for native SNI.dll. I think, for now, you may have to directly reference driver nuget in your main project as a workaround.

I'm facing the same issue but with visio Add-in project!! there is no Bin folder when you publish the add-in

**Comment by gaganpandey1977** [comment] 2021-02-13 22:47
I tried all these options nothing work for me. I see when i am compiling or publishing the web Application to a folder i see Microsoft.Data.SqlClient.SNI.x86.dll and Microsoft.Data.SqlClient.SNI.x86.pdb inside Bin folder. However when i publish this to Cloud this file i missing. 
I added these lines to .csproj file too. 


  <ItemGroup>
	<SNIFiles Condition="'$(MSBuildThisFileDirectory)' != '' And HasTrailingSlash('$(MSBuildThisFileDirectory)')" 	Include="$(MSBuildThisFileDirectory)**\SNI.*" />
   </ItemGroup>

 <Import Project="..\..\packages\Microsoft.Data.SqlClient.SNI.2.1.1\build\net46\Microsoft.Data.SqlClient.SNI.targets" Condition="Exists('..\..\packages\Microsoft.Data.SqlClient.SNI.2.1.1\build\net46\Microsoft.Data.SqlClient.SNI.targets')" />

**Comment by gaganpandey1977** [comment] 2021-02-18 05:00
@cheenamalhotra any thoughts why my web app is not copying this dll into Bin folder . I explicitly added reference as mention above in .csproj file too.

**Comment by cheenamalhotra** [comment] 2021-02-18 05:06
If you could upload a repro app, we can take a look and get back to you!

**Comment by norcisa-andy** [comment] 2021-03-03 01:37
I have experienced the same issue but with the x64 version.

**Comment by sliddington** [comment] 2021-03-10 03:38
Just added a "better" workaround on the other thread https://github.com/dotnet/SqlClient/issues/446#issuecomment-794816156

**Comment by jgcjoec** [comment] 2021-04-02 17:22
I had the same issue and used a post-build event to copy the missing DLL. That worked fine, until Windows file locking put up a roadblock. For reasons unknown, IIS had the file locked. Is there any way to disable Windows file locking entirely or to disable it in certain use-cases?

**Comment by benmccallum** [comment] 2021-08-02 15:05
I'm hearing from our team we have the a similar issue, but on a couple of ASP.NET MVC 5 projects and an ASP.NET Web API 2 project, all targeting net472. 

Unfortunately, even with the proposed workaround, we still don't get the SNI files into our nupkg produced by Octopack, so they don't get deployed.

I can even see the SNI files copy step in the build log, but the Octopack one after it never copies them over, I imagine because the existence of them is not being passed along to it.
![image](https://user-images.githubusercontent.com/157336/127881019-884ef601-17db-44d9-a24d-95f413d6dff3.png)

I resolved it by forcing those to be picked up by Octopack by explicitly declaring them as files in the nuspec...
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <files>
    <!-- https://github.com/dotnet/SqlClient/issues/727 -->
    <file src="bin\Microsoft.Data.SqlClient.SNI.*.*" target="bin" />
```

Would running `dotnet msbuild` make any difference? I do have a backlog item to get us off the deprecated TeamCity VS Solution build step, so I could try that if someone thinks it will.

**Comment by cheenamalhotra** [comment] 2021-08-03 16:22
Hi @benmccallum 

`dotnet msbuild` internally executes using MSBuild, so it should give you the same experience as `msbuild`. It may not change anything in regards to whether the files are copied or not. Unless the copy targets are included in your csproj, they are native DLLs and will not be identified by Dotnet SDK.

**Comment by benmccallum** [comment] 2021-08-05 12:59
Thanks for confirming @cheenamalhotra , I figured as much.

**Comment by jzabroski** [comment] 2022-04-22 13:04
What does SNI stand for ? Can probably put together several repros if I understand what's special about this dll

**Comment by jzabroski** [comment] 2022-04-22 15:22
To elaborate, https://github.com/dotnet/SqlClient/labels does not even have a description for "Native SNI"

It looks like this document explains it: https://docs.microsoft.com/en-us/sql/connect/ado-net/sqlclient-troubleshooting-guide?view=sql-server-ver15

> # Unable to load native SNI (Server Name Indication) library
> 
> SNI is the native C++ library that SqlClient depends on for various network operations when running on Windows. **In .NET Framework applications that are built with the MSBuild Project SDK, native DLLs aren't managed with restore commands. So a ".targets" file is included in the "Microsoft.Data.SqlClient.SNI" NuGet package that defines the necessary "Copy" operations.**

**Comment by swePeso** [comment] 2022-12-26 09:24
SSMS 19.4 have the same problem. 19.3 did not have this problem.

**Comment by brain246** [comment] 2023-01-18 13:02
and the same here. since updating SSMS to preview 4 i cannot connect to any sql instances anymore.

**Comment by reinaldokibel** [comment] 2023-01-23 22:34
same here with SSMS 19 Preview 4 on some servers, not all the servers

**Comment by asamaras** [comment] 2023-01-24 10:32
Same here, with ssms 19 preview 4, no connection to any server via IP address.

**Comment by cheenamalhotra** [comment] 2023-01-24 19:20
@swePeso @brain246 @reinaldokibel @asamaras 

Could you please provide more info to help us reproduce the issues you're facing with SSMS? Is that something you also reproduce from a .NET Framework Console app with Microsoft.Data.SqlClient?

cc @shueybubbles

**Comment by brain246** [comment] 2023-01-24 20:25
@cheenamalhotra Sorry, can't be of any help anymore regarding this issues, as it is now not solved on my machine (after de-installing and reinstalling it....).

**Comment by asamaras** [comment] 2023-01-25 08:05
> 
Hi @cheenamalhotra ,
Steps to reproduce:
1. PC with Windows 10/64 bit 19045.2486
2. Download and install SSMS-Setup-ENU.exe from https://go.microsoft.com/fwlink/?linkid=2219772&clcid=0x409 (version 19.4 preview)
3. Install the application
4. Connect to a local DB instance via windows authentication, the connection should be successful
5. Connect to a server via IP and you get the error message.

Update: 
After uninstalling, rebooting and re-installing SSMS managed to connect to DB server without issues.

**Comment by JRahnama** [comment] 2023-01-25 17:16
@asamaras have you tried using FQDN or server name instead of IP address? This could be due to the new feature [HostNameInCertificate](https://learn.microsoft.com/en-us/sql/connect/ado-net/connection-string-syntax?view=sql-server-ver16#hostnameincertificate)

**Comment by asamaras** [comment] 2023-01-25 19:09
@JRahnama That indeed could explain it, the server name is set to a local domain but the terminal is not consulting it, I use host file, so there is a possibility that it could not get the certificate from the server. I use IP to connect. 
Most likely I need to setup an AD domain.

**Comment by Ahmad-Hamdeen** [comment] 2023-02-20 13:31
This method had worked with me if the file "Microsoft.Data.SqlClient.SNI.x86.dll" ✔
is not exists in this path 
"C:\Program Files (x86)\Microsoft SQL Server Management Studio 19\Common7\IDE"
1. Download the file from this link **https://www.mediafire.com/file/z2wjnd8vzg9vdf4/Microsoft.Data.SqlClient.SNI.x86.dll/file**
2. Copy and Past it to "C:\Program Files (x86)\Microsoft SQL Server Management Studio 19\Common7\IDE"
3. Run the SQL Server Management Studio Management Studio 19 (Worked with me ✔)

**Comment by vladrobilko** [comment] 2023-12-16 06:35
https://stackoverflow.com/questions/45382993/unable-to-load-dll-sni-dll-entity-framework-core/45992774#45992774 - It helped me.

**Comment by David-Engel** [comment] 2024-06-11 21:17
Closing this issue as it appears to be external and has no specific fix to be made in MDS.

**Closed by David-Engel** 2024-06-11 21:17 UTC
Labels: :page_facing_up: Native SNI
