### ISSUE TITLE
Bump Microsoft.Identity.Client to remove CVE

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/SqlClient#2590] opened 2024-06-18 12:18 UTC
### Is your feature request related to a problem? Please describe.
I want  my software to be free from CVE's

### Describe the solution you'd like
A newer version of: Microsoft.Identity.Client is used ie 4.61.3

### Describe alternatives you've considered
Transitive pinning in all my projects to remove it.

### Additional context
Add any other context about the feature request here.

**Comment by ErikEJ** [comment] 2024-06-18 12:20
Duplicate of #2568

**Comment by ErikEJ** [comment] 2024-06-18 12:41
Azure.Identity depends on Microsoft.Identity.Client and 1.11.4 uses 4.61.3

**Comment by thompson-tomo** [comment] 2024-06-18 12:46
- Bur there is however an explicit dependency on the mackage.

**Comment by ErikEJ** [comment] 2024-06-18 12:51
@thompson-tomo I have a PR to remove the explicit dependency #2568

**Comment by kf-gonzalez2** [comment] 2024-06-18 18:50
Closing as duplicate of #2568 Please follow that thread for updates

**Closed by kf-gonzalez2** 2024-06-18 18:50 UTC
Labels: Duplicate
