### ISSUE TITLE
System.AccessViolationException at SNIOpenSyncExWrapper

### ISSUE THREAD

**Issue by joe-green-uk** [dotnet/SqlClient#1741] opened 2022-08-25 10:31 UTC
### Description
When connecting to a SQL instance in Azure App Services if the connection fails we don't get a graceful connection error but we recieve the following exception.

This code is .NET Framework 4.8
Deployed to Azure App Services

```
Application: w3wp.exe
Framework Version: v4.0.30319
Description: System.AccessViolationException
Exception message: The process was terminated due to an unhandled exception.
Stack trace:

Exception Info: System.AccessViolationException
   at <Module>.SNIOpenSyncExWrapper(SNI_CLIENT_CONSUMER_INFO*, SNI_ConnWrapper**)
   at SNINativeMethodWrapper.SNIOpenSyncEx(ConsumerInfo, System.String, IntPtr ByRef, Byte[], Byte[], Boolean, Boolean, Int32, Boolean, Int32, Int32, Boolean)
   at System.Data.SqlClient.SNIHandle..ctor(ConsumerInfo, System.String, Byte[], Boolean, Int32, Byte[] ByRef, Boolean, Boolean, Boolean, System.Data.SqlClient.TransparentNetworkResolutionState, Int32)
   at System.Data.SqlClient.TdsParserStateObject.CreatePhysicalSNIHandle(System.String, Boolean, Int64, Byte[] ByRef, Byte[], Boolean, Boolean, Boolean, System.Data.SqlClient.TransparentNetworkResolutionState, Int32)
   at System.Data.SqlClient.TdsParser.Connect(System.Data.SqlClient.ServerInfo, System.Data.SqlClient.SqlInternalConnectionTds, Boolean, Int64, Boolean, Boolean, Boolean, Boolean, Boolean, System.Data.SqlClient.SqlAuthenticationMethod, Boolean, System.Data.SqlClient.SqlAuthenticationProviderManager)
   at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(System.Data.SqlClient.ServerInfo, System.String, System.Security.SecureString, Boolean, System.Data.ProviderBase.TimeoutTimer, Boolean, Boolean, Boolean)
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(System.Data.SqlClient.ServerInfo, System.String, System.Security.SecureString, Boolean, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, System.Data.ProviderBase.TimeoutTimer)
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(System.Data.ProviderBase.TimeoutTimer, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, System.String, System.Security.SecureString, Boolean)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(System.Data.ProviderBase.DbConnectionPoolIdentity, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, System.Object, System.String, System.Security.SecureString, Boolean, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SessionData, System.Data.ProviderBase.DbConnectionPool, System.String, Boolean, System.Data.SqlClient.SqlAuthenticationProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(System.Data.Common.DbConnectionOptions, System.Data.Common.DbConnectionPoolKey, System.Object, System.Data.ProviderBase.DbConnectionPool, System.Data.Common.DbConnection, System.Data.Common.DbConnectionOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(System.Data.ProviderBase.DbConnectionPool, System.Data.Common.DbConnection, System.Data.Common.DbConnectionOptions, System.Data.Common.DbConnectionPoolKey, System.Data.Common.DbConnectionOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(System.Data.Common.DbConnection, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(System.Data.Common.DbConnection, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(System.Data.Common.DbConnection, UInt32, Boolean, Boolean, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal ByRef)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(System.Data.Common.DbConnection, System.Threading.Tasks.TaskCompletionSource`1<System.Data.ProviderBase.DbConnectionInternal>, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal ByRef)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(System.Data.Common.DbConnection, System.Threading.Tasks.TaskCompletionSource`1<System.Data.ProviderBase.DbConnectionInternal>, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal, System.Data.ProviderBase.DbConnectionInternal ByRef)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(System.Data.Common.DbConnection, System.Data.ProviderBase.DbConnectionFactory, System.Threading.Tasks.TaskCompletionSource`1<System.Data.ProviderBase.DbConnectionInternal>, System.Data.Common.DbConnectionOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(System.Threading.Tasks.TaskCompletionSource`1<System.Data.ProviderBase.DbConnectionInternal>)
   at System.Data.SqlClient.SqlConnection.TryOpen(System.Threading.Tasks.TaskCompletionSource`1<System.Data.ProviderBase.DbConnectionInternal>)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

```

### To reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
private static bool TestConnection(string connectionString)
{
    const string SqlQuery = "SELECT TOP 1 message_id FROM sys.messages";
	
    try
    {
        using (var connection = new SqlConnection(connectionString))
        {
            connection.Open();

            using (var sqlCommand = new SqlCommand(SqlQuery, connection) {CommandType = CommandType.Text})
            {
                return sqlCommand.ExecuteReader().HasRows;
            }
        }
    }
    catch (Exception ex)
    {
        _logger.LogError(ex);
        throw;
    }
}
```

### Expected behavior
I'd expect if we're having issues connecting to a SQL instance that a sensible error is returned. As the System.AccessViolationException bypasses the try { } catch { } due to [behaviour changes in .NET Framework 4](https://docs.microsoft.com/en-us/dotnet/api/system.accessviolationexception?redirectedfrom=MSDN&view=netframework-4.8#accessviolationexception-and-trycatch-blocks)  we don't want to set [legacyCorruptedStateExceptionsPolicy](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/legacycorruptedstateexceptionspolicy-element) due to the impact it would have on other exceptions.

Correct handling of the connection error and appropriate SQL exception raised back to the caller.

### Further technical details
Microsoft.Data.SqlClient version: (found on the nuget or Microsoft.Data.SqlClient.dll)
.NET target: Framework 4.8
SQL Server version: SQL Server 2017 (Distributed Availability Group)
Operating system: App Services Windows

**Comment by ThreeSevenths** [comment] 2022-08-25 12:04
Also receiving a similar AccessViolation exception connecting to Local SQL 2019 Developer Edition installation. .NET Framework 4.7.2 using nuget package version 2.1.4. SNI package version 4.0.0

```
   at Microsoft.Data.SqlClient.SNINativeManagedWrapperX64.SNIOpenSyncExWrapper(SNI_CLIENT_CONSUMER_INFO& pClientConsumerInfo, IntPtr& ppConn)
   at Microsoft.Data.SqlClient.SNINativeMethodWrapper.SNIOpenSyncEx(ConsumerInfo consumerInfo, String constring, IntPtr& pConn, Byte[] spnBuffer, Byte[] instanceName, Boolean fOverrideCache, Boolean fSync, Int32 timeout, Boolean fParallel, Int32 transparentNetworkResolutionStateNo, Int32 totalTimeout, Boolean isAzureSqlServerEndpoint, SQLDNSInfo cachedDNSInfo)
   at Microsoft.Data.SqlClient.SNIHandle..ctor(ConsumerInfo myInfo, String serverName, Byte[] spnBuffer, Boolean ignoreSniOpenTimeout, Int32 timeout, Byte[]& instanceName, Boolean flushCache, Boolean fSync, Boolean fParallel, TransparentNetworkResolutionState transparentNetworkResolutionState, Int32 totalTimeout, SQLDNSInfo cachedDNSInfo)
   at Microsoft.Data.SqlClient.TdsParserStateObject.CreatePhysicalSNIHandle(String serverName, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Byte[]& instanceName, Byte[] spnBuffer, Boolean flushCache, Boolean async, Boolean fParallel, TransparentNetworkResolutionState transparentNetworkResolutionState, Int32 totalTimeout, String cachedFQDN)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, Boolean isFirstTransparentAttempt, SqlAuthenticationMethod authType, String certificate, ServerCertificateValidationCallback serverCallback, ClientCertificateRetrievalCallback clientCallback, Boolean useOriginalAddressInfo, Boolean disableTnir)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover, Boolean isFirstTransparentAttempt, Boolean disableTnir)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, ServerCertificateValidationCallback serverCallback, ClientCertificateRetrievalCallback clientCallback, DbConnectionPool pool, String accessToken, SqlClientOriginalNetworkAddressInfo originalNetworkAddressInfo, Boolean applyTransientFaultHandling)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by joe-green-uk** [comment] 2022-08-25 14:19
This looks to be an issue when I use a DNS instead of an IP address. For example when I connect to a random IP address and port combination (e.g. 192.168.2.50,5122) I get the anticipated exception of 

`System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections.`

However if I use a DNS (e.g. "mylistener.someaddress.local") address instead of an IP address I would expect the following exception:

`System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - No such host is known.) ---> System.ComponentModel.Win32Exception (0x80004005)`

Instead in Azure App Services I get a crash with
```Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at <Module>.SNIOpenSyncExWrapper(SNI_CLIENT_CONSUMER_INFO*, SNI_ConnWrapper**)
```

**Comment by JRahnama** [comment] 2022-08-25 18:27
@joe-green-uk this error as @lcheunglci mentioned is usually based on a mismatching between SNI library and M.D.S versions, in other words you are using a `Microsoft.Data.SqlClient.SNI` library which is not built for the in-use version of `Microsoft.Data.SqlClient`. 
Can you delete all M.D.S from your code (probably uninstall, clean your code) and reinstall M.D.S and let it decide about SNI version?

**Comment by ThreeSevenths** [comment] 2022-08-25 18:35
> @joe-green-uk this error as @lcheunglci mentioned is usually based on a mismatching between SNI library and M.D.S versions, in other words you are using a `Microsoft.Data.SqlClient.SNI` library which is not built for the in-use version of `Microsoft.Data.SqlClient`. Can you delete all M.D.S from your code (probably uninstall, clean your code) and reinstall M.D.S and let it decide about SNI version?

Thank uoi @JRahnama and @lcheunglci for your replies. Can we update the dependency information and setting a max version of Microsoft.Data.SqlClient.SNI to prevent this issue from coming up? Currently the dependency requires >= 2.1.1 and specifies no maximum version.

**Comment by ErikEJ** [comment] 2022-08-25 19:05
Nuget will never pick a major Dependency version afaik

**Comment by JRahnama** [comment] 2022-08-25 22:26
@ThreeSevenths Correct M.D.S 2.1.4 requires >= 2.1.1 for SNI, but SNI packages are not to be consumed by the users. Driver decides on the dependency.  If you look into our [2.1 servicing branch for SNI version](https://github.com/dotnet/SqlClient/blob/db7f4517094df974dc09e9c3db9897bbbb8744c9/tools/props/Versions.props#L15) it will look for SNI v2.1.1 to build the driver and also in [nuspec for sni version](https://github.com/dotnet/SqlClient/blob/db7f4517094df974dc09e9c3db9897bbbb8744c9/tools/specs/Microsoft.Data.SqlClient.nuspec#L31) which specifies the nuget's requirements it has a dependency on SNI v2.1.1. Any alteration to SNI version manually by users may/will cause access violation exception.

Was my suggested solution able to solve the issue for you?

**Comment by ThreeSevenths** [comment] 2022-08-26 11:07
> @ThreeSevenths Correct M.D.S 2.1.4 requires >= 2.1.1 for SNI, but SNI packages are not to be consumed by the users. Driver decides on the dependency. If you look into our [2.1 servicing branch for SNI version](https://github.com/dotnet/SqlClient/blob/db7f4517094df974dc09e9c3db9897bbbb8744c9/tools/props/Versions.props#L15) it will look for SNI v2.1.1 to build the driver and also in [nuspec for sni version](https://github.com/dotnet/SqlClient/blob/db7f4517094df974dc09e9c3db9897bbbb8744c9/tools/specs/Microsoft.Data.SqlClient.nuspec#L31) which specifies the nuget's requirements it has a dependency on SNI v2.1.1. Any alteration to SNI version manually by users may/will cause access violation exception.
> 
> Was my suggested solution able to solve the issue for you?

This is what I did try initially, removing it and adding it again which is when I found myself on 4.0.0. I was _not_ able to repro it and as everyone has mentioned, nuget picked the correct SNI dependency version for me on the second installation. I do not know why it chose 4.0.0 the first time. 

Thank you all for your time and attention, I appreciate it!

**Comment by ErikEJ** [comment] 2022-08-26 11:10
@ThreeSevenths @joe-green-uk Are you using package.config - if so, strongly recommend switching to PackageReference

**Comment by ThreeSevenths** [comment] 2022-08-26 11:15
> @ThreeSevenths @joe-green-uk Are you using package.config - if so, strongly recommend switching to PackageReference

I am, unfortunately 🙁 and it's not something I can switch at the moment without opening a can of worms.

**Comment by ErikEJ** [comment] 2022-08-26 11:46
@ThreeSevenths Why not - you can also use PackageReference with the old .csproj format....

**Comment by ThreeSevenths** [comment] 2022-08-26 12:07
@ErikEJ next week is my last week in my current position and with my current company. Switching a key aspect of the project I am working on is not something I think is a good idea since I won't be around to support it. 🙂

**Comment by JRahnama** [comment] 2022-08-26 18:54
@ThreeSevenths seems like there is not much we can do here. If the issue is resolved/answered feel free to close it.

**Comment by ThreeSevenths** [comment] 2022-08-27 00:36
> @ThreeSevenths seems like there is not much we can do here. If the issue is resolved/answered feel free to close it.

Nothing to do, it's working as intended and the problem was somewhere between the keyboard and the chair. I did not open the issue in the first place; unfortunately, I cannot close it.

**Comment by JRahnama** [comment] 2022-08-29 15:00
@joe-green-uk any update on the issue?

**Comment by JRahnama** [comment] 2022-08-30 18:12
Closing the issue due to inactivity. Feel free to comment or open a new issue if the the problem still exists.

**Closed by JRahnama** 2022-08-30 18:12 UTC
