### ISSUE TITLE
Publish symbols to NuGet symbol server

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/SqlClient#2017] opened 2023-04-24 18:13 UTC
Symbols should be published to NuGet symbol server according to [Creating symbol packages (.snupkg)](https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg).

**Comment by JRahnama** [comment] 2023-04-24 20:50
@paulomorgado seems like duplicate of #2016

**Comment by paulomorgado** [comment] 2023-04-24 22:35
Related, but not duplicate.

I've since found out that source linking is also missing.

**Comment by MichelZ** [comment] 2024-11-01 12:47
This can probably be closed due to #2137

**Closed** 2024-11-01 17:44 UTC
