### ISSUE TITLE
CleanupExecuteReaderAsync OperationId is empty GUID

### ISSUE THREAD

**Issue by AndrewP-GH** [dotnet/SqlClient#1506] opened 2022-02-04 13:09 UTC
### WriteCommandAfter: CleanupExecuteReaderAsync has empty GUID as OperationId
Hello!

I'm writing the library for tracing Sql.Client. And I ran into a problem that the `CleanupExecuteReaderAsync` operation (or correctly call it _command_), which is produced as "Microsoft.Data.SqlClient.WriteCommandAfter" event, contains `Guid.Empty` OperationId. I've been confused with this behaviour because it is "after" command.
 

Event example:
```
{
    OperationId: 00000000 - 0000 - 0000 - 0000 - 000000000000,
    Operation: "CleanupExecuteReaderAsync",
    ConnectionId: 910 f6790 - b10b - 4143 - b723 - 915229 b16bb5,
    Command: SqlCommand {
        Connection: SqlConnection {
            RetryLogicProvider: SqlRetryLogicProvider {
                Retrying: null,
                RetryLogic: SqlRetryLogic {
                    PreCondition: null,
                    NumberOfTries: 1,
                    Current: 0,
                    RetryIntervalEnumerator: SqlNoneIntervalEnumerator {
                        GapTimeInterval: 00: 00: 00,
                        MaxTimeInterval: 00: 00: 00,
                        MinTimeInterval: 00: 00: 00,
                        Current: 00: 00: 00
                    },
                    TransientPredicate: "System.Predicate`1[System.Exception]"
                }
            },
            StatisticsEnabled: False,
            ConnectionString: "",
            ConnectionTimeout: 15,
            CommandTimeout: 30,
            AccessToken: null,
            Database: "",
            DataSource: "",
            PacketSize: 8000,
            ClientConnectionId: 910 f6790 - b10b - 4143 - b723 - 915229 b16bb5,
            ServerVersion: "The property accessor threw an exception: InvalidOperationException",	// this cause because SqlConnection.get_ServerVersion() uses SqlConnection.GetOpenTdsConnection() that throws ADP.ClosedConnectionError() if SqlInternalConnectionTds innerConnection is null when I dump this event
            ServerProcessId: 0,
            State: Closed,
            WorkstationId: "pay-994d47d-qwls4",
            Credential: null,
            FireInfoMessageEventOnUserErrors: False,
            CanCreateBatch: False,
            Site: null,
            Container: null
        },
        RetryLogicProvider: SqlRetryLogicProvider {
            Retrying: null,
            RetryLogic: SqlRetryLogic {
                PreCondition: null,
                NumberOfTries: 1,
                Current: 0,
                RetryIntervalEnumerator: SqlNoneIntervalEnumerator {
                    GapTimeInterval: 00: 00: 00,
                    MaxTimeInterval: 00: 00: 00,
                    MinTimeInterval: 00: 00: 00,
                    Current: 00: 00: 00
                },
                TransientPredicate: "System.Predicate`1[System.Exception]"
            }
        },
        Notification: null,
        Transaction: null,
        CommandText: "select 1;",
        ColumnEncryptionSetting: UseConnectionSetting,
        CommandTimeout: 30,
        CommandType: Text,
        DesignTimeVisible: True,
        Parameters: [],
        UpdatedRowSource: Both,
        Site: null,
        Container: null
    },
    TransactionId: null,
    Statistics: [DictionaryEntry {
        Key: "BuffersReceived",
        Value: 1
    }, DictionaryEntry {
        Key: "BuffersSent",
        Value: 1
    }, DictionaryEntry {
        Key: "BytesReceived",
        Value: 45
    }, DictionaryEntry {
        Key: "BytesSent",
        Value: 48
    }, DictionaryEntry {
        Key: "CursorOpens",
        Value: 0
    }, DictionaryEntry {
        Key: "IduCount",
        Value: 0
    }, DictionaryEntry {
        Key: "IduRows",
        Value: 0
    }, DictionaryEntry {
        Key: "PreparedExecs",
        Value: 0
    }, DictionaryEntry {
        Key: "Prepares",
        Value: 0
    }, DictionaryEntry {
        Key: "SelectCount",
        Value: 1
    }, DictionaryEntry {
        Key: "SelectRows",
        Value: 1
    }, DictionaryEntry {
        Key: "ServerRoundtrips",
        Value: 1
    }, DictionaryEntry {
        Key: "SumResultSets",
        Value: 1
    }, DictionaryEntry {
        Key: "Transactions",
        Value: 0
    }, DictionaryEntry {
        Key: "UnpreparedExecs",
        Value: 1
    }, DictionaryEntry {
        Key: "ConnectionTime",
        Value: 0
    }, DictionaryEntry {
        Key: "ExecutionTime",
        Value: 0
    }, DictionaryEntry {
        Key: "NetworkServerTime",
        Value: 1
    }],
    Timestamp: 964052645195323
}
```

### To reproduce
You need to wait when a connection will be closed

### Expected behavior
I expect this command has some not empty id. :)

### Further technical details
Microsoft.Data.SqlClient version: 3.0.1
.NET target: .net6.0
SQL Server version: Microsoft SQL Azure (RTM) - 12.0.2000.8 
Operating system: Docker container(image aspnet:6.0)

**Comment by AndrewP-GH** [comment] 2022-02-04 13:25
I think the reason is that operationId [here](https://github.com/dotnet/SqlClient/blob/100eaaaeaa9cbef55ac5df17f09a4b2ab7bcd809/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs#L2661) is empty because it this command doesn't have a [parent operation](https://github.com/dotnet/SqlClient/blob/100eaaaeaa9cbef55ac5df17f09a4b2ab7bcd809/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs#L2629)

**Comment by Wraith2** [comment] 2022-02-04 19:16
Interesting. Can you give me a small reproduction app? It doesn't need the listener that you're using to see the value because it'll be visible in the debugger, it's just a lot easier to debug these things when you have a clean reproduction of the exact issue rather than having to work your way towards a problem.

**Comment by Kaur-Parminder** [comment] 2022-02-08 21:17
@AndrewP-GH as Wraith mentioned, Please provide us with small application that reproduces the issue and we can look into the issue.

**Comment by ahydrax** [comment] 2022-02-09 06:55
Fix is available here https://github.com/dotnet/SqlClient/pull/1511

**Comment by ahydrax** [comment] 2023-01-29 02:55
I tried to reproduce this bug on `5.1.0` and seems it's fixed now. This can be closed.

**Comment by Wraith2** [comment] 2023-01-29 10:49
It seems strange that we accidentally fixed it, but good. Thanks for your work.

**Closed** 2023-02-15 20:42 UTC
