### ISSUE TITLE
Microsoft.Data.SqlClient.SNI.x64 not copied to bin

### ISSUE THREAD

**Issue by LucGosso** [dotnet/SqlClient#745] opened 2020-09-30 18:20 UTC
Hi there! 

Using Team City and Octopus deploy, Microsoft.Data.SqlClient asks for the 64x SNI to work at runtime. 

installed nuget Microsoft.Data.SqlClient.SNI.2.1.0, works locally. but in staging it is not copied to bin folder. What am i missing? 

in csproj, got only this: 

` <Import Project="..\..\packages\Microsoft.Data.SqlClient.SNI.2.1.0\build\net46\Microsoft.Data.SqlClient.SNI.targets" Condition="Exists('..\..\packages\Microsoft.Data.SqlClient.SNI.2.1.0\build\net46\Microsoft.Data.SqlClient.SNI.targets')" />`

(the package and targets-file is there)
![image](https://user-images.githubusercontent.com/9716195/94725238-bcd64b80-035b-11eb-9921-11d29f0c9aca.png)

using .net 4.7.2, visualstudio 2019, web project

Any ideas?

**Comment by karinazhou** [comment] 2020-09-30 19:05
Hi @LucGosso ,

When you mention "installed nuget Microsoft.Data.SqlClient.SNI.2.1.0, works locally", does the issue happen when you deploy your application through Team City and Octopus? The Microsoft.Data.SqlClient.SNI nuget package contains the native SNI.dll. If the application can work locally but is not deployed successfully, it may be due to the way how the deployment tool handle native dlls. 

And is your application the WebForms app? We have the known issue about native SNI.dll loading with WebForms https://github.com/dotnet/SqlClient/issues/446 and https://github.com/dotnet/SqlClient/issues/727 .  Could you please provide a standalone repo application so we can test it locally?

Thanks,

**Comment by LucGosso** [comment] 2020-09-30 19:36
Yes, you got it right. and yes it may due to how the deployment tools handles native dlls (hmm)

it is an ASP.MVC project, not webforms.

Sorry, cant share this application. 

so for now, as a workaround, I included the bin/...x64.dll in project to be able to deploy it with tools... 

(for the record, when publishing the solution from VS. the dlls are published to site bin folder, so that works)

**Comment by karinazhou** [comment] 2020-09-30 22:34
@LucGosso  yeah, VS works for you because the nuget.exe solves the native SNI dependency for your application based on the SNI targets file. I am afraid that we have limited knowledge about how the TeamCity and Octopus deploy tool supports native libraries. 

The Microsoft.Data.SqlClient nuget package has the dependency of Microsoft.Data.SqlClient.SNI nuget package. The former is the managed library while the latter is the native library. One thing you can also try is to add Microsoft.Data.SqlClient as direct reference to your application and see how it works. If you have already done this, please ignore it.

**Comment by simongh** [comment] 2020-12-18 17:41
What maybe happening - what happens for me - is the octopack tasks run before the task to move the SNI files. You mention using Octopus & TeamCity. We use the OctoPack package which adds a task to the build to create packages deployable by Octopus. This task runs before the tasks to copy the SNI files. It therefore means the SNI files are missing from the deploy package.

I haven't so far been able to make the build work. One way around it is to modify your nuspec to manually reference the SNI files.

**Comment by LucGosso** [comment] 2021-01-04 16:48
thats a theory... maybe...

or it is something in Microsoft.Data.SqlClient.SNI.targets, some environment condition not copying the files, any idea what? hard to debug... 

<Import Project="..\..\packages\Microsoft.Data.SqlClient.SNI.2.1.0\build\net46\Microsoft.Data.SqlClient.SNI.targets" Condition="Exists('..\..\packages\Microsoft.Data.SqlClient.SNI.2.1.0\build\net46\Microsoft.Data.SqlClient.SNI.targets')" />

**Comment by cheenamalhotra** [comment] 2021-01-04 17:17
> What maybe happening - what happens for me - is the octopack tasks run before the task to move the SNI files.

Hi @simongh 

Could you capture Binlog file and provide us here by running msbuild with `/bl` flag (please try for a non-confidential app only).
So we can see the order to execution and address that if possible.

**Comment by LucGosso** [comment] 2021-01-04 20:00
So, the issue was in OctoPack ... 

the resolution is to add 

`<files>
    <file src="bin\**\*.*" target="bin" />
  </files>`
 to your nuspec in solution, which is used to pack the nuget to octopus deploy
 
 also add 
 ` <PropertyGroup>
      <OctoPackEnforceAddingFiles>True</OctoPackEnforceAddingFiles>
    </PropertyGroup>`
    
in csproj...

does this work for ya too @simongh ?

**Comment by LucGosso** [comment] 2021-01-04 20:03
the weird thing is that all copy commands after CopyRoslynCompilerFilesToOutputDirectory is not included in the package (without nuspec hack), but all before that is... 

![image](https://user-images.githubusercontent.com/9716195/103574234-dabdca00-4ecf-11eb-8c20-8cc8c372d7f5.png)

any idea why? 

https://stackoverflow.com/questions/19115010/octopack-additional-files-copied-in-a-pre-build-event

**Comment by simongh** [comment] 2021-01-17 16:59
I found the way round this was to modify the proj file to make it include the the SNI files when Octopack is running.

`<PropertyGroup>
    <ContentSNIFiles Condition="'$(RunOctoPack)' != '' And '$(RunOctoPack)'!= 'false'">true</ContentSNIFiles>
</PropertyGroup>`

This seemed more reliable than modifying the nuspec file

**Comment by lAnubisl** [comment] 2021-02-25 10:48
Please fix NuGet package

**Comment by norcisa-andy** [comment] 2021-03-03 02:27
I have also experience this issue.

**Comment by MojoDK** [comment] 2021-04-08 11:48
I have this problem too - why is this still not fixed?

**Comment by tobias76** [comment] 2021-04-19 15:53
We are also experiencing this with .NET Framework and WPF. Following for updates.

**Comment by Kellen-Stuart** [comment] 2021-04-22 19:45
We are experiencing this issue with .NET Framework 4.7.2 and C# MVC 5. I think if you output the SNI.dll in /bin instead of /x86 or /x64, it would just work.

**Comment by DavoudEshtehari** [comment] 2021-04-23 21:11
Thanks @tobias76 and @Kellen-Stuart we'll give it a try.

**Comment by kfrancis** [comment] 2021-12-03 19:31
> So, the issue was in OctoPack ...
> 
> the resolution is to add
> 
> `<files> <file src="bin\**\*.*" target="bin" /> </files>` to your nuspec in solution, which is used to pack the nuget to octopus deploy
> 
> also add ` <PropertyGroup> <OctoPackEnforceAddingFiles>True</OctoPackEnforceAddingFiles> </PropertyGroup>`
> 
> in csproj...
> 
> does this work for ya too @simongh ?

This fixed it for me.

**Comment by JRahnama** [comment] 2022-01-12 01:12
@LucGosso is this still an issue?

**Comment by LucGosso** [comment] 2022-01-12 07:33
I think we solved it by including the dlls into the repo/project/bin-folder. Which is not the way to go but as a workaround.

**Comment by Kellen-Stuart** [comment] 2022-01-13 20:13
@JRahnama We are also copying DLLs into the /bin folder manually. Not the way to go, but needed it to work.

**Comment by kfrancis** [comment] 2022-01-20 18:51
> @LucGosso is this still an issue?

Yea, without doing something - it's still an issue. Rather annoying one too because generally it works on development but fails to copy in deploy situations.

**Comment by AndreasJilvero** [comment] 2022-01-20 21:44
@Kellen-Stuart I had the same issue, and while a combination of @simongh 's nor @LucGosso 's solution was working-ish (the SNI files was copied to both /bin and the root folder). However, when working locally I noticed that everything seemed to work using the msbuild CLI - so I tried to use Command line parameters **instead of** using Teamcity's Run Octopack checkbox, like this:

![image](https://user-images.githubusercontent.com/7750212/150426891-1f2fcd56-01cc-4a82-a2c1-6a3d60a83200.png)

And it actually works. I could also remove `<ContentSNIFiles Condition="'$(RunOctoPack)' != '' And '$(RunOctoPack)'!= 'false'">true</ContentSNIFiles>`.

**Comment by dimula** [comment] 2023-01-18 20:28
still an issue. Azure CD pipeline doesnt grab SNI files

**Comment by Aashishkebab** [comment] 2023-04-26 18:36
> still an issue. Azure CD pipeline doesnt grab SNI files

Did you ever figure this out?

**Comment by David-Engel** [comment] 2024-06-11 21:21
Closing as a likely duplicate of #612.

**Closed by David-Engel** 2024-06-11 21:21 UTC
Labels: :link: External, :page_facing_up: Native SNI
