### ISSUE TITLE
.NET application is getting locked up in the System.Data.SqlClient.TdsParserStateObject.WritePacket method

### ISSUE THREAD

**Issue by pphari2001** [dotnet/SqlClient#679] opened 2020-08-09 03:11 UTC
I'm running a .NET (4.6.1.) application that inserts binary data and observing the same issue. It is getting locked up in the System.Data.SqlClient.TdsParserStateObject.WritePacket method while executing the System.Data.SqlClient.SQLCommand.ExecuteNonQuery. See below the version of System.Data.dll used in the system.

C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll 4.7.3630.0

The strange behavior is that it is happening only in a build which we've released in the last Feb. We have rebuilt recently the same code base and run the application and there is no issue. We have compared all binaries/dlls of both build and it is exactly the same.

I noticed that there is a fix for this issue and would like to know which .NET version or specific System.Data.Dll has the fix? I'm using process explorer (System internals) to check the runtime usage of System.Data.dll and it shows the .NET 4.7 version. What are the possibilities, the issue shows only on a specific build? The same data we have tried with at least 4 different builds and couldn't reproduce the issue. Appreciate any help to identify this issue.

![image](https://user-images.githubusercontent.com/69405386/89724066-274db980-d9b3-11ea-8e8d-c8c136de689b.png)

**Comment by Wraith2** [comment] 2020-08-09 09:12
As I've commented on your other post of this at https://github.com/dotnet/corefx/pull/34709#issuecomment-671027276 you should update to the latest version of this library and then try again and see if the error reproduces.

**Comment by pphari2001** [comment] 2020-08-10 21:49
We were trying to identify the differences in the build, but could not find any differences. Created a dump from taskmgr while running both build and checked from Visual Studio (with the DMP file) and both build using the version of System.Data.dll.
Is .NET application can reference to a specific version of System.Data.dll? The target framework choosen for both build in the project is 4.6.1.

**Comment by pphari2001** [comment] 2020-08-10 21:49
> @pphari2001
> 
> Since you mentioned above:
> 
> > We have rebuilt recently the same code base and run the application and there is no issue. We have compared all binaries/dlls of both build and it is exactly the same.
> 
> If your referenced System.Data.dll does not contain the fix, it should reproduce the error even upon rebuilding, it doesn't make sense why 1 build continues to fail while another passes on same code base. Has anything changed on your build machine, an update of .NET Framework perhaps?

We were trying to identify the differences in the build, but could not find any differences. Created a dump from taskmgr while running both build and checked from Visual Studio (with the DMP file) and both build using the version of System.Data.dll.
Is .NET application can reference to a specific version of System.Data.dll? The target framework choosen for both build in the project is 4.6.1.

**Comment by pphari2001** [comment] 2020-08-11 14:22
> @pphari2001
> 
> Since you mentioned above:
> 
> > We have rebuilt recently the same code base and run the application and there is no issue. We have compared all binaries/dlls of both build and it is exactly the same.
> 
> If your referenced System.Data.dll does not contain the fix, it should reproduce the error even upon rebuilding, it doesn't make sense why 1 build continues to fail while another passes on same code base. Has anything changed on your build machine, an update of .NET Framework perhaps?

We noticed that one of the dll (application) built from a build system explores this issue, but other one does not. We are trying to understand the differences in the build environment and also differences between both dll itself. The dll size is exactly same and used nDepend for the comparison, and shows no differences. Is there a tool we can use the compare two .NET dlls find out what is the difference is causing this issue?

**Comment by Wraith2** [comment] 2020-08-11 14:37
You can try https://github.com/bitdiffer/bitdiffer but you'll have to be careful to do that analysis using a complete dump of the dependencies from both environments so you can ensure you aren't seeing framework libraries or redirects wrongly.

You could also try dumping the process and investigating it with windbg.

**Comment by pphari2001** [comment] 2020-08-11 18:17
> You can try https://github.com/bitdiffer/bitdiffer but you'll have to be careful to do that analysis using a complete dump of the dependencies from both environments so you can ensure you aren't seeing framework libraries or redirects wrongly.
> 
> You could also try dumping the process and investigating it with windbg.

Couldn't find any differences with bitdiffer..

**Comment by cheenamalhotra** [comment] 2020-08-11 21:30
@pphari2001 

Is there any difference in the runtime environment when you experienced failures in first build v/s the second working build?
Have you run tests on same machine using both builds and is the failure consistent from original build?

cc @saurabh500 any thoughts?

**Comment by pphari2001** [comment] 2020-08-11 23:29
> @pphari2001
> 
> Is there any difference in the runtime environment when you experienced failures in first build v/s the second working build?
> Have you run tests on same machine using both builds and is the failure consistent from original build?
> 
> cc @saurabh500 any thoughts?

Tested both builds on same machine and the first one fails consistently. There are multiple dlls as part of the Application and I was able to isolate one of the dll pontentially causing the issue. If I replace this dll from the working build it works correctly. However none of the diff tools identifies what is the difference in the dlls. I have tried nDepend, dotpeek, bitdiffer, beyond compare, ILSpy. Using ILSpy and bidiffer decompiled the code from both dlls, which looks exactly same and no differences. Is there a way I can send both dlls to your team to examine the difference?

**Comment by pphari2001** [comment] 2020-08-11 23:30
> @pphari2001
> 
> Is there any difference in the runtime environment when you experienced failures in first build v/s the second working build?
> Have you run tests on same machine using both builds and is the failure consistent from original build?
> 
> cc @saurabh500 any thoughts?

Tested both builds on same machine and the first one fails consistently. There are multiple dlls as part of the Application and I was able to isolate one of the dll pontentially causing the issue. If I replace this dll from the working build it works correctly. However none of the diff tools identifies what is the difference in the dlls. I have tried nDepend, dotpeek, bitdiffer, beyond compare, ILSpy. Using ILSpy and bidiffer decompiled the code from both dlls, which looks exactly same and no differences. Is there a way I can send both dlls to your team to examine the difference?

**Comment by cheenamalhotra** [comment] 2020-08-11 23:54
Ok, which DLLs they are ?
Can you Zip them separately and upload here on GitHub?

**Comment by pphari2001** [comment] 2020-08-12 00:16
> Ok, which DLLs they are ?
> Can you Zip them separately and upload here on GitHub?

The DLLs are built with Target as the .NET framework 4.6.1. I'm not familiar with uploading to the GibHub. Can you please provide the steps for uploading the file.

**Comment by pphari2001** [comment] 2020-08-12 00:26
> Ok, which DLLs they are ?
> Can you Zip them separately and upload here on GitHub?

@cheenamalhotra , attached is the dlls.

[DLL-Issue-pphari2001-abbott.zip](https://github.com/dotnet/SqlClient/files/5060029/DLL-Issue-pphari2001-abbott.zip)

**Comment by cheenamalhotra** [comment] 2020-08-12 00:30
Thanks @pphari2001 

I downloaded them to investigate further.
I wasn't sure if you wanted to leave the source online, so I removed the DLLs from your comment.

**Comment by cheenamalhotra** [comment] 2020-08-12 00:44
It seems that these dependencies (DLLs mentioned below) are coming from different referenced paths in both "notworking" and "working" builds as you can see in your "csproj" file (compared with WinMerge):

```
Architecture.dll
Inst.Infrastructure.dll
Features.Common.dll
OrderMgmt.Common.dll
```
as their "HintPath" are different.

It does not qualify for exact same build as even if the project source is same, csproj controls what is referenced. And if dependencies are not being loaded from same location, you can certainly see different behavior.

**Comment by pphari2001** [comment] 2020-08-12 03:23
> It seems that these dependencies (DLLs mentioned below) are coming from different referenced paths in both "notworking" and "working" builds as you can see in your "csproj" file (compared with WinMerge):
> 
> ```
> Architecture.dll
> Inst.Infrastructure.dll
> Features.Common.dll
> OrderMgmt.Common.dll
> ```
> 
> as their "HintPath" are different.
> 
> It does not qualify for exact same build as even if the project source is same, csproj controls what is referenced. And if dependencies are not being loaded from same location, you can certainly see different behavior.

@cheenamalhotra  thanks for your quick response. Let me check why there is a difference in the external lib path.

**Comment by pphari2001** [comment] 2020-08-12 03:31
Checked the HintPath and it is the path where I copied the two builds. Those 4 dlls used by the ResultMgmt.Common.dll. There is no differences in those dlls and it is in the both build packages. To make it work only I need to replace the ResultMgmt.Common.dll. The build is created by Visual Studio 2015 version 14.0.25123.00 Update 2.

**Comment by pphari2001** [comment] 2020-08-12 23:53
> > It seems that these dependencies (DLLs mentioned below) are coming from different referenced paths in both "notworking" and "working" builds as you can see in your "csproj" file (compared with WinMerge):
> > ```
> > Architecture.dll
> > Inst.Infrastructure.dll
> > Features.Common.dll
> > OrderMgmt.Common.dll
> > ```
> > 
> > 
> > as their "HintPath" are different.
> > It does not qualify for exact same build as even if the project source is same, csproj controls what is referenced. And if dependencies are not being loaded from same location, you can certainly see different behavior.
> 
> @cheenamalhotra thanks for your quick response. Let me check why there is a difference in the external lib path.

@cheenamalhotra , attached is a screenshot from the binary comparison of this two DLLs which has differences. Eventhough DLL diff tools are not identifying these differences. Could you please if there is a way we can determine these differences. Attached is again both DLLs.

[DLLDiffs.zip](https://github.com/dotnet/SqlClient/files/5066461/DLLDiffs.zip)



![image](https://user-images.githubusercontent.com/69405386/90079072-ba406980-dcbb-11ea-9016-dff71b7e9d7b.png)

**Comment by pphari2001** [comment] 2020-08-13 07:52
Visual Studio (Both VS2015, VS2019) incorrectly builds a DLL when Assembly.cs in the DLL contains ‘ LF” line ending characters instead of CR,LF characters (attached).  This line feed ending is caused by our build script. Is there any problem reported for having mixed line ending characters in the Assembly.cs file?
[AssemblyDifferences.zip](https://github.com/dotnet/SqlClient/files/5067813/AssemblyDifferences.zip)

@cheenamalhotra

**Comment by cheenamalhotra** [comment] 2020-08-13 18:53
Hi @pphari2001 

> Visual Studio (Both VS2015, VS2019) incorrectly builds a DLL when Assembly.cs in the DLL contains ‘ LF” line ending characters instead of CR,LF characters (attached).

That's a good question for Visual Studio teams I guess.
You can open a ticket on Developer Community: https://developercommunity.visualstudio.com/spaces/8/index.html?all

**Comment by cheenamalhotra** [comment] 2020-08-19 04:36
Hi @pphari2001 

I'll close this issue from our repository since it doesn't apply to driver.

**Closed by cheenamalhotra** 2020-08-19 04:36 UTC
Labels: :link: External
