### ISSUE TITLE
Update Azure.Identity to 1.6.0.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/SqlClient#1601] opened 2022-05-02 21:40 UTC
Azure.Identity's latest version is 1.6.0 but there is plans for some work for it to remove some more dependencies with it adding an .NET 6 TFM for it so it can require less packages which would be great for everyone using SqlClient directly or indirectly from efcore.

**Comment by JRahnama** [comment] 2022-05-04 09:07
@AraHaan  This is in our radar. We have recently updated the version, but the latest version will be used when Net6 support is added.

**Comment by AraHaan** [comment] 2022-05-04 13:35
So I can basically add it in my PR that basically removes the needless dependencies.

Speaking of that PR, VS seems to be having issues with it as well for some reason.

**Comment by JRahnama** [comment] 2022-05-12 21:15
we will do some testing and if everything works as expected we will upgrade the version in our next preview release.

**Comment by AraHaan** [comment] 2022-05-12 21:32
I experimented with it in my pr to remove some dependencies and it compiles fine with the updated packages. I even pushed them to that PR as well.

**Comment by JRahnama** [comment] 2022-05-12 21:37
Can you make a separate PR for that. We try to avoid multiple changes in one PR to make it easier to find the source any regression? or we can do it.

**Comment by lcheunglci** [comment] 2022-05-12 21:51
@AraHaan already has PR #1536 opened for the Azure Identity upgrade, so I closed my PR opened earlier.

**Comment by AraHaan** [comment] 2022-05-12 22:09
I commented on your PR. #1536 had to have the dependency updates temporarily in order to get my local build to pass.

However the updates could be moved from #1536 as they can also be used by all the other TFMs.

**Comment by lcheunglci** [comment] 2022-05-31 21:21
I added a comment in the merged PR #1611 , regarding the Microsoft.IdentityModel.* dependency i.e. upgrading from 6.8.0 to 6.18.0, where it succeeded in the netcore project but failed on netfx project because the nuget package `Microsoft.IdentityModel.Abstractions` doesn't exist for netfx from the solution/project's nuget repo: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json and the solution to fix it was to add the repo https://api.nuget.org/v3/index.json to it.  However, I'm not sure if there was a reason behind using the azure repo vs the official nuget repo, so perhaps, one of the maintainers could chime in.

**Comment by JRahnama** [comment] 2022-06-03 20:30
@lcheunglci  and @AraHaan the issue with the feed should be fixed now. It is added to public feed.

**Comment by JRahnama** [comment] 2022-06-15 17:50
Closing this as done in PR #1611

**Closed by JRahnama** 2022-06-15 17:50 UTC

**Comment by AraHaan** [comment] 2022-06-15 17:56
@JRahnama, @lcheunglci was the followup pr created for the other Microsoft.IdentityModel.* dependencies?

**Comment by lcheunglci** [comment] 2022-06-15 18:56
I have a branch with the change for the upgrade, I'll open a PR shortly.
