### ISSUE TITLE
EFCore throwing 'System.ObjectDisposedException' several minutes after successful DB Record Retrieval

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/SqlClient#327] opened 2019-11-22 19:13 UTC
Moving from https://github.com/aspnet/EntityFrameworkCore/issues/15069 originally filed by @GRS-Leedo.

We have investigated this from the EF side and can't find anything wrong. It looks like the exception is being generated from somewhere within the SqlClient SNI code, so I'm moving it here for you guys to take a look. However, it's also possible that this is a UWP or a more general lower-level networking issue. 

I'm not moving all the comments and attachments over at this time--please look at the original issue for repro code, etc.

Thanks,
Arthur

----

### Original issue

Describe what is not working as expected.

I am developing a UWP app based on Microsoft.NetCore.UniversalWindowsPlatform V6.2.8 and EFCore 2.2.3

The app successfully retrieves a record from a SQL  database.  Several minutes later (up to 15 minutes) the app throws a System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.'

from SNIPackets.ReadFromStreamAsync

Several issues are strange:
1) There is no further attempt to read from the database to cause this error, this happens several minutes after the successful read from the database.
2) SNIPackets.ReadFromStreamAsync requires a Stream and an SNIAsyncCallback both of which are null
3) The stack trace in incomplete with no reference to what is actually making the call
4) Changing connection and command timeout values has no effect.

Searching the web has provided no help.

Any suggestions or direction would be greatly appreciated.

Thanks.
```
Exception message:
Stack trace:
   at System.Net.Sockets.NetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 size, CancellationToken cancellationToken)
```
This is the entire stack trace, which seems truncated.  The inner exception is null.

### Steps to reproduce
Service Collection Creation in MainPage()

```C#
            _sp = new ServiceCollection()
                .AddScoped<ILoads, Loads>()
                .AddScoped<IDocks, Docks>()
                .AddScoped<IConfig, Config>()
                .AddDbContext<DataDbContext>(options => 
                    options.UseSqlServer("Data Source=app-sql-insight;Initial Catalog=MasterSchedScndVersion; UID and Password Removed;MultipleActiveResultSets=True;Persist Security Info=True"))
                .BuildServiceProvider();`
```

DI
```C#
        private readonly DataDbContext _context;

        public Docks(DataDbContext Context)
        {
            _context = Context;
        }
```

code accessing database (runs successfully and returns a record)
```C#
            try
            {
                LB = await (from l in _context.Tbl_LoadingBayLoadTicketAssignments
                                               .Include(o => o.Operation)
                            where l.BayNumber == LoadingBayNumber && l.LocationID == 10
                            select l).AsNoTracking().FirstOrDefaultAsync();

            }
            catch (Exception ex)
            {

                throw;
            }
```

The catch does not catch the exception
```

### Further technical details
EF Core version: 2.2.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer V 2.2.3
Operating system: Win 10 Target 1803
IDE: Visual Studio 2017 15.9.9

**Comment by Wraith2** [comment] 2019-11-22 21:10
It's likely to be from the pool cleanup after the connection hasn't been used for a while which is why there's no useful stack trace. It also isn't caught by the exception handler because that's no longer on the stack.

**Comment by GRS-Leedo** [comment] 2019-11-25 14:12
That makes a certain amount of sense.

I have noticed another pattern of behavior with UWP, EF Core and SQL...  The first time that a database access is attempted, a large number of errors are thrown, not caught by the exception handler and, eventually, the data access completes.  This is the result of the first read attempt

Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
The thread 0xa528 has exited with code 0 (0x0).
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Battery State Update 46
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
The thread 0x32cc has exited with code 0 (0x0).
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.SqlClient.dll

After all of these errors, the access does complete successfully and all subsequent data access attempts are successful without any errors being thrown.  Since these errors are not caught by the error handler, there is no stack trace to look at.

**Comment by cheenamalhotra** [comment] 2019-11-25 18:54
@GRS-Leedo 

Could you try reproducing the same with [EF Core 3.0.1](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/3.0.1) and [Microsoft.Data.SqlClient 1.1.0](https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.1.0)?

**Comment by GRS-Leedo** [comment] 2019-11-25 20:17
Those are not supported by UWP are they?

[cid:image005.png@01CCFDFB.153168C0]<http://www.leedo.com/>
Glen Swanson | Software Developer
10707 Corporate Drive, Suite 250 | Stafford, TX 77477
T 281.201.0900 ext:1005
Follow us on Twitter<https://twitter.com/LeedoCabinetry> | Like us on Facebook<https://www.facebook.com/LeedoCabinetry>

**Comment by cheenamalhotra** [comment] 2019-11-25 20:26
EF Core 3.0.1 is just newer version of Entity Framework, which now uses Microsoft.Data.SqlClient library instead of System.Data.SqlClient. Support is backwards-compatible and you should be able to upgrade your App with minor changes to SqlClient references.

**Comment by GRS-Leedo** [comment] 2019-11-25 22:38
EF Core 3.0.1 is not compatible with UWP because it seems to rely on NetStandard 2.1 which is currently not compatible with UWP.
Severity
Code
Description
Project
File
Line
Suppression State
Error
NU1202
Package Microsoft.EntityFrameworkCore 3.0.1 is not compatible with uap10.0.18362 (UAP,Version=v10.0.18362) / win10-x86. Package Microsoft.EntityFrameworkCore 3.0.1 supports: netstandard2.1 (.NETStandard,Version=v2.1)
CabScanRemote
C:\Users\gswanson\source\Workspaces\CabScanRemote\CabScanRemote\CabScanRemote.csproj
1



[cid:image005.png@01CCFDFB.153168C0]<http://www.leedo.com/>
Glen Swanson | Software Developer
10707 Corporate Drive, Suite 250 | Stafford, TX 77477
T 281.201.0900 ext:1005
Follow us on Twitter<https://twitter.com/LeedoCabinetry> | Like us on Facebook<https://www.facebook.com/LeedoCabinetry>

**Comment by cheenamalhotra** [comment] 2019-11-25 22:59
Ok. That makes sense.
I'm not much familiar with EF Core but thought it to be backward-compatible.

**Comment by ajcvickers** [comment] 2019-11-25 23:01
@GRS-Leedo EF Core 3.1 brings back to .NET Standard 2.0. The preview 3 package is very close to what will be released; you should be able to test with that.

**Comment by GRS-Leedo** [comment] 2019-11-25 23:13
That seems to have fixed the issue and seems much faster!  I will continue to test and let you know if I come across any issues.

Thanks again!!!

Glen

[cid:image005.png@01CCFDFB.153168C0]<http://www.leedo.com/>
Glen Swanson | Software Developer
10707 Corporate Drive, Suite 250 | Stafford, TX 77477
T 281.201.0900 ext:1005
Follow us on Twitter<https://twitter.com/LeedoCabinetry> | Like us on Facebook<https://www.facebook.com/LeedoCabinetry>

**Comment by JRahnama** [comment] 2020-08-05 19:05
@GRS-Leedo any update on the issue? Feel free to close the issue if it is solved.

**Comment by JRahnama** [comment] 2020-09-01 01:04
Closing the issue as it is fixed.

**Closed by JRahnama** 2020-09-01 01:04 UTC
Labels: :hourglass_flowing_sand: Waiting for Customer
