### ISSUE TITLE
Unhandled exception. System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient 

### ISSUE THREAD

**Issue by martin-studna** [dotnet/SqlClient#1523] opened 2022-02-23 08:53 UTC
We are deploying azure webjob and when the webjob is deployed we are getting the following error:

```
[02/23/2022 08:33:01 > 57fccd: ERR ] Unhandled exception. System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
[02/23/2022 08:33:01 > 57fccd: ERR ]    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
```

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
        <SkipFunctionsDepsCopy>true</SkipFunctionsDepsCopy>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="5.0.0" />
        <PackageReference Include="Nethereum.Web3" Version="4.2.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
        <PackageReference Include="System.Data.SqlClient" Version="4.6.0" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.17.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.16" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0" />
        <PackageReference Include="FlexLabs.EntityFrameworkCore.Upsert" Version="4.0.0" />
       
        <PackageReference Include="RestSharp" Version="106.11.7" />
        <PackageReference Include="RestSharp.Serializers.NewtonsoftJson" Version="106.11.7" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="2.1.3" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="4.1.2" />
        <PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="3.1.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
        <PackageReference Include="Serilog.Filters.Expressions" Version="2.1.0" />
        <PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="3.1.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="4.1.0" />
        <PackageReference Include="Serilog.Sinks.Seq" Version="5.0.1" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CVV.RateGate" Version="1.0.1" />
        <PackageReference Include="SocketIOClient" Version="1.0.3.13" />
    </ItemGroup>

    <ItemGroup>
      
        <PackageReference Include="NServiceBus" Version="7.5.0" />
        <PackageReference Include="NServiceBus.Persistence.Sql.ScriptBuilder" Version="6.2.0" />
        <PackageReference Include="NServiceBus.Heartbeat" Version="3.0.1" />
        <PackageReference Include="NServiceBus.Metrics" Version="3.0.0" />
        <PackageReference Include="NServiceBus.Newtonsoft.Json" Version="2.3.0" />
        <PackageReference Include="NServiceBus.SagaAudit" Version="3.0.1" />
        <PackageReference Include="NServiceBus.Serilog" Version="7.15.0" />
        <PackageReference Include="NServiceBus.Transport.AzureServiceBus" Version="1.9.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="2.1.3" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="4.1.2" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
        <PackageReference Include="NServiceBus.Callbacks" Version="3.0.0" />
        <PackageReference Include="NServiceBus.Extensions.Hosting" Version="1.1.0" />
        <PackageReference Include="NServiceBus.Persistence.Sql" Version="6.2.0" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Shared.Domain\Shared.Domain.csproj" />
    </ItemGroup>
</Project>

```

Firstly, we had Microsoft.Data.SqlClient 3.0.0 as a dependency. Then I moved to System.Data.SqlClient as you can see from *.csproj file. I always get the same error.

I am using azure devops pipeline to make the deployment.

**Comment by JRahnama** [comment] 2022-02-23 20:25
@martin-studna can you post a sample repro please? something minimal that reproduces the issue.
Thank you.

**Comment by martin-studna** [comment] 2022-02-23 21:27
```c#

using System;
using System.Data;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using NServiceBus;
using NServiceBus.Logging;
using NServiceBus.Serilog;
using Serilog;

namespace Shared.NServiceBus
{
    public static class HostBuilderExtensions
    {
        /// <summary>
        ///     Configures the host to start an NServiceBus endpoint.
        /// </summary>
        public static void ConfigureNServiceBus(EndpointConfiguration endpointConfiguration, HostBuilderContext context)
        {
                endpointConfiguration.License(LicenseHelper.GetLicense);

                // Serialization
                var settings = new JsonSerializerSettings
                {
                    ContractResolver = new NonPublicPropertiesResolver(),
                    NullValueHandling = NullValueHandling.Ignore,
                    ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor
                };
                
                settings.Converters.Add(new StringEnumConverter());
                
                var serialization = endpointConfiguration.UseSerialization<NewtonsoftSerializer>();
                serialization.Settings(settings);

                LogManager.Use<SerilogFactory>();
                var serilogTracing = endpointConfiguration.EnableSerilogTracing(Log.Logger);
                serilogTracing.EnableMessageTracing();
                serilogTracing.EnableSagaTracing();

                // Audit
                endpointConfiguration.SendFailedMessagesTo("Error");
                endpointConfiguration.AuditProcessedMessagesTo("Audit");
                if (bool.Parse(context.Configuration["Queues:SagaAuditEnabled"]))
                    endpointConfiguration.AuditSagaStateChanges("Audit");
                 
                // Installers
                endpointConfiguration.EnableInstallers();

                // Transport
                var transport = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
                transport.ConnectionString(context.Configuration.GetConnectionString("ServiceBus"));
                transport.Transactions(TransportTransactionMode.ReceiveOnly);
                transport.EntityMaximumSize(1);
                 
                var outboxSettings = endpointConfiguration.EnableOutbox();
                outboxSettings.UsePessimisticConcurrencyControl();
                outboxSettings.TransactionIsolationLevel(IsolationLevel.ReadCommitted);
                outboxSettings.KeepDeduplicationDataFor(TimeSpan.FromDays(7));
                outboxSettings.RunDeduplicationDataCleanupEvery(TimeSpan.FromDays(1));
                
                var persistence = endpointConfiguration.UsePersistence<SqlPersistence>();
                var sagaSettings = persistence.SagaSettings();
                sagaSettings.JsonSettings(new JsonSerializerSettings
                {
                    TypeNameHandling = TypeNameHandling.Auto,
                    MetadataPropertyHandling = MetadataPropertyHandling.ReadAhead
                });
                persistence.SqlDialect<SqlDialect.MsSqlServer>();
                persistence.ConnectionBuilder(() => new SqlConnection(context.Configuration.GetConnectionString("OperationalDatabase")));
        }
    }
}

```

I can send only this part of the code. This is the only place where Microsoft.Data.SqlClient is used.

**Comment by bingAgility** [comment] 2022-05-18 04:59
I am also facing this issue, below is the code where I am using the "System.Data.SqlClient" package with Version=4.8.2.
i am getting this exception on when i am using Azure dev ops pipeline

namespace ManageNonBlockingTests
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;

    public class DataAccess
    {
        private static Logger logger = Logger.GetLogger();

        public static List<NonBlockingTests> GetNonBlockingTests(string connectionString, string threshold, string maxNumberOfRecords)
        {
            SqlConnection dbConnection = new SqlConnection(connectionString);
            try
            {
                var dbCommand = dbConnection.CreateCommand();
                dbConnection.Open();
                dbCommand.CommandText = "<Query>";
                var dbReader = dbCommand.ExecuteReader();
                List<NonBlockingTests> list = new List<NonBlockingTests>();
                if (dbReader.HasRows)
                {
                    while (dbReader.Read())
                    {
                        //< do something>
                    }
                    dbReader.NextResult();
                }
                else
                {
                    logger.Log("No rows found.");
                }
                dbReader.Close();
                dbConnection.Close();
                return list;
            }
            catch (Exception ex)
            {
                logger.Log($"An Exception occured when trying to read from DB - {ex.Message}");
            }
            finally
            {
                dbConnection.Close();
            }
            return null;
        }
    }
}

**Comment by ajayEngProd** [comment] 2022-05-18 05:01
I am also facing this issue, below is the code where I am using the "System.Data.SqlClient" package with Version=4.8.2.
i am getting this exception on when i am using Azure dev ops pipeline

namespace ManageNonBlockingTests
{
using System;
using System.Collections.Generic;
using System.Data.SqlClient;

public class DataAccess
{
    private static Logger logger = Logger.GetLogger();

    public static List<NonBlockingTests> GetNonBlockingTests(string connectionString, string threshold, string maxNumberOfRecords)
    {
        SqlConnection dbConnection = new SqlConnection(connectionString);
        try
        {
            var dbCommand = dbConnection.CreateCommand();
            dbConnection.Open();
            dbCommand.CommandText = "<Query>";
            var dbReader = dbCommand.ExecuteReader();
            List<NonBlockingTests> list = new List<NonBlockingTests>();
            if (dbReader.HasRows)
            {
                while (dbReader.Read())
                {
                    //< do something>
                }
                dbReader.NextResult();
            }
            else
            {
                logger.Log("No rows found.");
            }
            dbReader.Close();
            dbConnection.Close();
            return list;
        }
        catch (Exception ex)
        {
            logger.Log($"An Exception occured when trying to read from DB - {ex.Message}");
        }
        finally
        {
            dbConnection.Close();
        }
        return null;
    }
}

**Comment by ajayEngProd** [comment] 2022-05-18 06:52
@JRahnama, please let us know if there are any updates on the above issue.
Any help in this regard would be appreciated.

**Comment by JRahnama** [comment] 2022-05-18 16:25
@ajayEngProd can you send us your connection string properties please?

**Comment by JRahnama** [comment] 2022-05-20 20:21
@ajayEngProd can you also try with net6 and its latest version of runtime 6.0.5 please?

**Comment by ajayEngProd** [comment] 2022-05-23 04:45
@JRahnama  apolgoies for the delay,
 @"Data Source = ***********.database.windows.net; Initial Catalog = *******; Persist Security Info = True; User ID = *****; Password =******";

**Comment by ajayEngProd** [comment] 2022-05-23 04:46
i have removed the userID and password , just FYI , they are not empty strings.

**Comment by greengumby** [comment] 2022-10-06 03:38
Any update on this issue?

**Comment by lcheunglci** [comment] 2022-10-11 18:26
Can you provide us information to create the pipeline to reproduce the issue as the information is insufficient for us to reproduce. The error is caused by wrong DLL being deployed from the pipeline (e.g. YAML file example would be helpful).

**Comment by referencejpgiroux** [comment] 2023-04-14 09:40
I have the same problem. Was working fine in .net5 with sqlClient 5.0. Trying to upgrade to .net6 and sqlclient 5.1 and get a PlatformNotSupportedException in the constructor of SqlConnection. I have created a test project that has the same issue:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.1" />
  </ItemGroup>

</Project>
```

```csharp
using Microsoft.Data.SqlClient;

Console.WriteLine("Hello, World!");


using (SqlConnection connection = new SqlConnection("Server=********;Database=******;Uid=*****;Pwd=***********;"))
{
    connection.Open();
    
}

Console.WriteLine("done");
```

When I debug, this is what the decompiled SqlConnection looks like:

```
// Decompiled with JetBrains decompiler
// Type: Microsoft.Data.SqlClient.SqlConnection
// Assembly: Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5
// MVID: 005A6563-6166-43DB-AA8A-36DE14AB06DC
// Assembly location: /home/jpgiroux/code/test_net6/bin/Debug/net6.0/Microsoft.Data.SqlClient.dll

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Security;
using System.Threading;
using System.Threading.Tasks;

namespace Microsoft.Data.SqlClient
{
  [DefaultEvent("InfoMessage")]
  public sealed class SqlConnection : DbConnection, ICloneable
  {
    public SqlConnection() => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public SqlConnection(string connectionString) => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public SqlConnection(string connectionString, SqlCredential credential) => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public string AccessToken
    {
      get => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
      set => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
    }

    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public Guid ClientConnectionId => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public static TimeSpan ColumnEncryptionKeyCacheTtl
    {
      get => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
      set => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
    }

    public static bool ColumnEncryptionQueryMetadataCacheEnabled
    {
      get => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
      set => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
    }

    public static IDictionary<string, IList<string>> ColumnEncryptionTrustedMasterKeyPaths => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public int CommandTimeout => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    [DefaultValue("")]
    [RefreshProperties(RefreshProperties.All)]
    [SettingsBindable(true)]
    public override string ConnectionString
    {
      get => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
      set => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
    }

    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public override int ConnectionTimeout => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public SqlCredential Credential
    {
      get => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
      set => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
    }

    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public override string Database => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    [Browsable(true)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public override string DataSource => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public bool FireInfoMessageEventOnUserErrors
    {
      get => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
      set => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
    }

    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public int PacketSize => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public SqlRetryLogicBaseProvider RetryLogicProvider
    {
      get => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
      set => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
    }

    public int ServerProcessId => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public override string ServerVersion => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public override ConnectionState State => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    [DefaultValue(false)]
    public bool StatisticsEnabled
    {
      get => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
      set => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
    }

    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public string WorkstationId => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public event SqlInfoMessageEventHandler InfoMessage
    {
      add
      {
      }
      remove
      {
      }
    }

    protected override DbTransaction BeginDbTransaction(IsolationLevel isolationLevel) => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public SqlTransaction BeginTransaction() => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public SqlTransaction BeginTransaction(IsolationLevel iso) => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public SqlTransaction BeginTransaction(IsolationLevel iso, string transactionName) => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public SqlTransaction BeginTransaction(string transactionName) => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public override void ChangeDatabase(string database) => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public static void ChangePassword(
      string connectionString,
      SqlCredential credential,
      SecureString newSecurePassword)
    {
      throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
    }

    public static void ChangePassword(string connectionString, string newPassword) => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public static void ClearAllPools() => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public static void ClearPool(SqlConnection connection) => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public override void Close() => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public SqlCommand CreateCommand() => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    protected override DbCommand CreateDbCommand() => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    protected override void Dispose(bool disposing)
    {
    }

    public override DataTable GetSchema() => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public override DataTable GetSchema(string collectionName) => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public override DataTable GetSchema(string collectionName, string[] restrictionValues) => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public override void Open() => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public void Open(SqlConnectionOverrides overrides) => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public override Task OpenAsync(CancellationToken cancellationToken) => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public static void RegisterColumnEncryptionKeyStoreProviders(
      IDictionary<string, SqlColumnEncryptionKeyStoreProvider> customProviders)
    {
      throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
    }

    public void RegisterColumnEncryptionKeyStoreProvidersOnConnection(
      IDictionary<string, SqlColumnEncryptionKeyStoreProvider> customProviders)
    {
      throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
    }

    public void ResetStatistics() => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public IDictionary<string, object> RetrieveInternalInfo() => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    public IDictionary RetrieveStatistics() => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");

    object ICloneable.Clone() => throw new PlatformNotSupportedException("Microsoft.Data.SqlClient is not supported on this platform.");
  }
}

```


My dotnet info:

```
.NET SDK (reflecting any global.json):
 Version:   6.0.113
 Commit:    4a23b50f97

Runtime Environment:
 OS Name:     pop
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/6.0.113/

global.json file:
  Not found

Host:
  Version:      6.0.13
  Architecture: x64
  Commit:       1af80ba017

.NET SDKs installed:
  6.0.113 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

```

**Comment by cheenamalhotra** [comment] 2024-07-23 21:29
It looks like a RuntimeIdentifier issue after updating to .NET 6, and these kinds of issues can be resolved by including appropriate `<RuntimeIdentifier>` property in csproj file.

The MDS NuGet package supports `win` and `unix` related Runtime Identifiers, as per `runtimes` folder included. Customers can choose their DLL based on platforms in use. 

Read more: 
* https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#loading-assets-for-a-specific-os-version-or-distribution
* https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/readme.md

**Closed** 2024-07-23 21:36 UTC
Labels: :information_source: Needs more Info
