### ISSUE TITLE
MARS TDS header contained errors

### ISSUE THREAD

**Issue by meirib** [dotnet/SqlClient#687] opened 2020-08-13 08:56 UTC
@ajcvickers 

Following my previous post:
https://github.com/dotnet/aspnetcore/issues/24831

This error occurs spontaneously on Azure MSSQL, and only a web app restart seems to help:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): The incoming tabular data stream (TDS) protocol stream is incorrect. The MARS TDS header contained errors.
```

Unfortunately, I'm using a 3rd party nuget that reproduces this issue, thus I cannot provide a runnable code for investigation. 

However, It appears that this 3rd party uses Microsoft.EntityFrameworkCore.SqlServer (V3.1.6), which uses:
Microsoft.Data.SqlClient (V1.1.3) as it's **default** dependency version.

![image](https://user-images.githubusercontent.com/34509869/90114583-96346500-dd5b-11ea-8fbf-47d997f0f0ed.png)

According this issue:
[https://github.com/dotnet/SqlClient/issues/85](https://github.com/dotnet/SqlClient/issues/85)

I cannot conclude whether this issue is resolved in Microsoft.Data.SqlClient (V2.0.0) or not.
If so, an upgrade should resolve this matter?

**Comment by karinazhou** [comment] 2020-08-13 17:30
Hi @meirib ,

We have fixed this issue in Microsoft.Data.SqlClient v2.0.0 in this PR https://github.com/dotnet/SqlClient/pull/547 .

**Comment by meirib** [comment] 2020-08-17 07:34
@karinazhou ,

Seems like upgrading to Microsoft.Data.SqlClient v2.0.0 solved the issue.
According to the 3rd party we use, well, they use _"EF abstraction layer -- not SqlClient directly"_

**Comment by karinazhou** [comment] 2020-08-18 21:38
@meirib  Since we have the same fix both in version 2.0.0 and version 1.1.3, the EntityFrameworkCore.SqlServer (V3.1.6) should also work in your scenario. 

> Seems like upgrading to Microsoft.Data.SqlClient v2.0.0 solved the issue.

Do you have the repo app to confirm this?

**Comment by meirib** [comment] 2020-08-19 05:48
@karinazhou 
Well, it's not working - MARS error is produced spontaneously in V1.1.3. 
Only by **manually** upgrading to V2.0.0 we were able to overcome this, annoying infrastructure crisis, which caused us a sever malfunctioning unexpected system behavior.

For what it's worth, these are the properties:

![image](https://user-images.githubusercontent.com/34509869/90596901-a97e7f00-e1f8-11ea-800d-2ea74277009f.png)


![image](https://user-images.githubusercontent.com/34509869/90596845-89e75680-e1f8-11ea-9d4e-7fe59cdae60c.png)

**Comment by karinazhou** [comment] 2020-08-25 19:26
@meirib Thank you for confirming it. From the library property you posted, it is from the \lib folder other than the actual working one from \runtimes folder. Is this the one loaded by your application when using EFCore v3.1.6 only?

![image](https://user-images.githubusercontent.com/27743156/91217609-9ffb8800-e6cc-11ea-8d5f-132018844ebc.png)

From all the clues we have now, we know that direct reference to the Microsoft.Data.SqlClient v2.0.0 works fine no matter what version of EFCore your application uses. And use EFCore v3.1.6 only fails the application. 
- MDS v2.0.0 + EFCore v3.1.7  -->  succeed
- MDS v2.0.0 + EFCore v3.1.6  -->  succeed
- EFCore v3.1.6  -->  fail
- MDS v1.1.3 + EFCore v3.1.6  -->  ?
- EFCore v3.1.7  -->  ?

Can you also try the last two combinations to validate the behavior?

**Comment by karinazhou** [comment] 2020-09-22 18:20
Hi @meirib  , 
Any updates on this?

**Comment by cheenamalhotra** [comment] 2020-09-25 21:21
Closing as duplicate of #85 
Please follow us there if you have more questions on this issue.

**Closed by cheenamalhotra** 2020-09-25 21:21 UTC
