### ISSUE TITLE
Connection Resiliency does not seem to be working

### ISSUE THREAD

**Issue by David-Engel** [dotnet/SqlClient#304] opened 2019-11-13 00:39 UTC
### Describe the bug
In a simple unplug and re-plug of the network cable, connection resiliency seems to have stopped working between System.Data.SqlClient 4.6.0 and Microsoft.Data.SqlClient 1.0.19269.1.

### To reproduce
[smo-test-master.zip](https://github.com/dotnet/SqlClient/files/3838837/smo-test-master.zip)

Using the attached solution, build and run with a command line connection string against a remote SQL Server instance (I used SQL Server 2017 on the same wired LAN): `"Data Source=[remote host];Trusted_Connection=true;Pooling=False;Connect Timeout=30;"`

Unplug your network cable for 30 seconds when prompted. Plug it back in a wait 7-8 seconds for the network to come back up. Press a key to continue and note the exception that the connection is closed.

### Expected behavior
Using System.Data.SqlClient 4.6.0, the ExecuteReader() following the connection interruption succeeds. I would expect Microsoft.Data.SqlClient to succeed, too.

### Further technical details
Microsoft.Data.SqlClient version: 1.0.19269.1
.NET target: Core 2.2
SQL Server version: SQL Server 2017
Operating system: Windows 10

**Additional context**
Others have reproduced this over WiFi by disconnecting and reconnecting WiFi, too. I was not able to reproduce this against an Azure SQL DB endpoint.

**Comment by cheenamalhotra** [comment] 2019-11-13 19:12
Additional Info:

This issue was also reproduced on System.Data.SqlClient 4.7.0 (.NET Core), so seems to be introduced in one of the earlier PRs merged in CoreFx.

**Comment by cheenamalhotra** [comment] 2019-11-16 01:40
Merged in #310 🎉

**Closed by cheenamalhotra** 2019-11-16 01:40 UTC
Labels: Backport to CoreFx, Bug!
