### ISSUE TITLE
Microsoft.Data.SqlClient throwing exception on Powershell under Linux

### ISSUE THREAD

**Issue by umersyed** [dotnet/SqlClient#1387] opened 2021-11-13 20:32 UTC
### Describe the bug
Unable to make a SQL connection in Powershell on Linux using Microsoft.Data.SqlClient.SqlConnection.  

We are using self hosted linux/ubuntu agents in Azure and need to make SQL connection with Authentication="Active Directory Password". Getting below exception . Please assist.

```
Exception message: Exception calling "Open" with "0" argument(s): "The type initializer for 'Microsoft.Win32.Registry' threw an exception."
Stack trace: 
ErrorRecord                 : Exception calling "Open" with "0" argument(s): "The type initializer for 'Microsoft.Win32.Registry' threw an exception."
WasThrownFromThrowStatement : False
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, System.Exception)
Message                     : Exception calling "Open" with "0" argument(s): "The type initializer for 'Microsoft.Win32.Registry' threw an exception."
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.TypeInitializationException: The type initializer for 'Microsoft.Win32.Registry' threw an exception.
                               ---> System.PlatformNotSupportedException: Registry is not supported on this platform.
                                 at Microsoft.Win32.RegistryKey.OpenBaseKeyCore(RegistryHive hKey, RegistryView view)
                                 at Microsoft.Win32.Registry..cctor()
                                 --- End of inner exception stack trace ---
                                 at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionPool.NetCoreApp.cs:line 18
                                 at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) in /_/src/Microsoft.Data.SqlClient/netcore/src
                              /Microsoft/Data/ProviderBase/DbConnectionPool.cs:line 779
                                 at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) in /_/src/Microsoft.Data.SqlClient/netcor
                              e/src/Microsoft/Data/ProviderBase/DbConnectionPool.cs:line 1759
                                 at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions
                              userOptions, DbConnectionInternal& connection) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionPool.cs:line 1214
                                 at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection) in /_/src/Micr
                              osoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionPool.cs:line 1130
                                 at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbCon
                              nectionInternal& connection) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionFactory.cs:line 122
                                 at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOp
                              tions) in /_/src/Microsoft.Data.SqlClient/netcore/src/Common/src/Microsoft/Data/ProviderBase/DbConnectionInternal.cs:line 339
                                 at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in
                              /_/src/Microsoft.Data.SqlClient/netcore/src/Common/src/Microsoft/Data/ProviderBase/DbConnectionClosed.cs:line 39
                                 at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs:
                              line 1792
                                 at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs:line 1277
                                 at CallSite.Target(Closure , CallSite , Object )
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                                 at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

```

### To reproduce
$sqlAdminUser = "xxxxx"
$sqlAdminPass = "xxxxx"
$InstanceName = "xxxx.database.windows.net"
$authType = "Active Directory Password"
$connectionString = "Server=$InstanceName;Database=sqldb;Integrated Security=False;User ID=$sqlAdminUser;Password=$sqlAdminPass;Authentication=$authType"
$query = "some query to DB"
$connection = New-Object Microsoft.Data.SqlClient.SqlConnection
$connection.ConnectionString = $connectionString
$connection.Open()

### Expected behavior
Should be able to connect to SQL database and execute query

### Further technical details
Microsoft.Data.SqlClient version: .3.0.1
.NET Core SDK (reflecting any global.json):
 Version:   3.1.415
 Commit:    52a108342e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.415/

Host (useful for support):
  Version: 3.1.21
  Commit:  df8abc0f7e

.NET Core SDKs installed:
  3.1.415 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

SQL Server version: Azure SQL Server 12
Operating system: Agent running ubuntu 20.04 , 
Powershell version : 7.2

**Additional context**
In order to make Microsoft.Data.SqlClient work in Powershell on Linux,  had to to the following:

Register-PackageSource -provider NuGet -name nugetRepository -location https://www.nuget.org/api/v2 -Trusted
Install-Package Microsoft.Data.SqlClient -Provider nuget -SkipDependencies -Destination /opt/microsoft/powershell/7/ -Force
Install-Package Microsoft.Identity.Client -Provider nuget -SkipDependencies -Destination /opt/microsoft/powershell/7/ -Force
Add-Type -AssemblyName System.Data
Add-Type -Path('/opt/microsoft/powershell/7/Microsoft.Identity.Client.4.37.0/lib/net461/Microsoft.Identity.Client.dll')
Add-Type -Path ('/opt/microsoft/powershell/7/Microsoft.Data.SqlClient.3.0.1/runtimes/unix/lib/netcoreapp3.1/Microsoft.Data.SqlClient.dll')
Install-Package Azure.Core -Provider nuget -SkipDependencies -RequiredVersion 1.6.0.0 -Destination /opt/microsoft/powershell/7/ -Force
Add-Type -Path('/opt/microsoft/powershell/7/Azure.Core.1.6.0/lib/net461/Azure.Core.dll')
Install-Package Azure.Identity -Provider nuget -SkipDependencies -RequiredVersion 1.3.0.0 -Destination /opt/microsoft/powershell/7/ -Force
Add-Type -Path('/opt/microsoft/powershell/7/Azure.Identity.1.3.0/lib/netstandard2.0/Azure.Identity.dll')

**Comment by Wraith2** [comment] 2021-11-14 00:26
Looks like it's using the wrong binary. That's a windows binary as you can see because it's using the registry. You need to use nuget to restore the correct one.

See if this issue helps, https://github.com/dotnet/SqlClient/issues/1301

**Comment by umersyed** [comment] 2021-11-14 00:42
Yes, I am am using nuget, You can see that in the above in Install-Package command lines, the Provider is nuget. Also I followed the solution described in [#1301](https://github.com/dotnet/SqlClient/issues/1301) and added few more assemblies on top of it as required.

**Comment by umersyed** [comment] 2021-11-15 14:17
I wonder if Microsoft.Data.SqlClient provider been tested with Powershell on Linux with Authentication="Active Directory Password" ? If yes, Can someone please provide examples or documentation on that. Thanks

**Comment by cheenamalhotra** [comment] 2021-11-15 16:56
Watch out for what you’re installing, these are .NET Framework DLLs, not for Linux.

`Add-Type -Path('/opt/microsoft/powershell/7/Microsoft.Identity.Client.4.37.0/lib/net461/Microsoft.Identity.Client.dll')`

`Add-Type -Path('/opt/microsoft/powershell/7/Azure.Core.1.6.0/lib/net461/Azure.Core.dll')`

**Comment by JRahnama** [comment] 2021-11-17 22:08
@umersyed is the issue solved? if yes, please feel free to close the issue.

**Comment by umersyed** [comment] 2021-11-18 13:16
@cheenamalhotra thanks for pointing out that, managed to load the right DLLs for linux.
@JRahnama Will confirm soon as still in process of setting up and testing the new provider. thanks

**Comment by umersyed** [comment] 2021-11-18 20:50
Its working for me now. Had to load below packages :

Register-PackageSource -provider NuGet -name nugetRepository -location https://www.nuget.org/api/v2 -Trusted -ErrorAction SilentlyContinue
Install-Package Microsoft.Data.SqlClient -Provider Nuget -SkipDependencies -Scope CurrentUser -RequiredVersion 3.0.1 -Destination ~/PackageManagement/NuGet/Packages -Force
Install-Package Microsoft.Identity.Client -Provider Nuget -SkipDependencies -Scope CurrentUser -RequiredVersion 4.37.0 -Destination ~/PackageManagement/NuGet/Packages -Force
Add-Type -AssemblyName System.Data
Add-Type -Path('~/PackageManagement/NuGet/Packages/Microsoft.Identity.Client.4.37.0/lib/netcoreapp2.1/Microsoft.Identity.Client.dll')
Add-Type -Path ('~/PackageManagement/NuGet/Packages/Microsoft.Data.SqlClient.3.0.1/runtimes/unix/lib/netcoreapp3.1/Microsoft.Data.SqlClient.dll')
Install-Package Azure.Core -Provider Nuget -Scope CurrentUser -SkipDependencies -RequiredVersion 1.6.0.0 -Destination ~/PackageManagement/NuGet/Packages -Force
Add-Type -Path('~/PackageManagement/NuGet/Packages/Azure.Core.1.6.0/lib/netstandard2.0/Azure.Core.dll')
Install-Package Azure.Identity -Provider Nuget -Scope CurrentUser -SkipDependencies -RequiredVersion 1.3.0.0 -Destination ~/PackageManagement/NuGet/Packages -Force
Add-Type -Path('~/PackageManagement/NuGet/Packages/Azure.Identity.1.3.0/lib/netstandard2.0/Azure.Identity.dll')

Can close this issue now
Thank you

**Comment by umersyed** [comment] 2021-11-18 20:52
Its working for me now. Had to do the following :

```
Register-PackageSource -provider NuGet -name nugetRepository -location https://www.nuget.org/api/v2 -Trusted -ErrorAction SilentlyContinue
Install-Package Microsoft.Data.SqlClient -Provider Nuget -SkipDependencies -Scope CurrentUser -RequiredVersion 3.0.1 -Destination ~/PackageManagement/NuGet/Packages -Force
Install-Package Microsoft.Identity.Client -Provider Nuget -SkipDependencies -Scope CurrentUser -RequiredVersion 4.37.0 -Destination ~/PackageManagement/NuGet/Packages -Force
Add-Type -AssemblyName System.Data
Add-Type -Path('~/PackageManagement/NuGet/Packages/Microsoft.Identity.Client.4.37.0/lib/netcoreapp2.1/Microsoft.Identity.Client.dll')
Add-Type -Path ('~/PackageManagement/NuGet/Packages/Microsoft.Data.SqlClient.3.0.1/runtimes/unix/lib/netcoreapp3.1/Microsoft.Data.SqlClient.dll')
Install-Package Azure.Core -Provider Nuget -Scope CurrentUser -SkipDependencies -RequiredVersion 1.6.0.0 -Destination ~/PackageManagement/NuGet/Packages -Force
Add-Type -Path('~/PackageManagement/NuGet/Packages/Azure.Core.1.6.0/lib/netstandard2.0/Azure.Core.dll')
Install-Package Azure.Identity -Provider Nuget -Scope CurrentUser -SkipDependencies -RequiredVersion 1.3.0.0 -Destination ~/PackageManagement/NuGet/Packages -Force
Add-Type -Path('~/PackageManagement/NuGet/Packages/Azure.Identity.1.3.0/lib/netstandard2.0/Azure.Identity.dll')
```
Can close this issue now
Thank you

**Comment by JRahnama** [comment] 2021-11-18 21:05
@umersyed  thanks for the update.

closing as the issue is resolved.

**Closed by JRahnama** 2021-11-18 21:05 UTC

**Comment by abelal83** [comment] 2022-06-08 09:11
> Its working for me now. Had to do the following :
> 
> ```
> Register-PackageSource -provider NuGet -name nugetRepository -location https://www.nuget.org/api/v2 -Trusted -ErrorAction SilentlyContinue
> Install-Package Microsoft.Data.SqlClient -Provider Nuget -SkipDependencies -Scope CurrentUser -RequiredVersion 3.0.1 -Destination ~/PackageManagement/NuGet/Packages -Force
> Install-Package Microsoft.Identity.Client -Provider Nuget -SkipDependencies -Scope CurrentUser -RequiredVersion 4.37.0 -Destination ~/PackageManagement/NuGet/Packages -Force
> Add-Type -AssemblyName System.Data
> Add-Type -Path('~/PackageManagement/NuGet/Packages/Microsoft.Identity.Client.4.37.0/lib/netcoreapp2.1/Microsoft.Identity.Client.dll')
> Add-Type -Path ('~/PackageManagement/NuGet/Packages/Microsoft.Data.SqlClient.3.0.1/runtimes/unix/lib/netcoreapp3.1/Microsoft.Data.SqlClient.dll')
> Install-Package Azure.Core -Provider Nuget -Scope CurrentUser -SkipDependencies -RequiredVersion 1.6.0.0 -Destination ~/PackageManagement/NuGet/Packages -Force
> Add-Type -Path('~/PackageManagement/NuGet/Packages/Azure.Core.1.6.0/lib/netstandard2.0/Azure.Core.dll')
> Install-Package Azure.Identity -Provider Nuget -Scope CurrentUser -SkipDependencies -RequiredVersion 1.3.0.0 -Destination ~/PackageManagement/NuGet/Packages -Force
> Add-Type -Path('~/PackageManagement/NuGet/Packages/Azure.Identity.1.3.0/lib/netstandard2.0/Azure.Identity.dll')
> ```
> 
> Can close this issue now Thank you

Thanks for this, spent several days trying to figure this out!

**Comment by potatoqualitee** [comment] 2022-10-17 13:15
Agreed, that super helped, @umersyed thank you
