### ISSUE TITLE
A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable) - Azure SQL Database

### ISSUE THREAD

**Issue by husnusinterxion** [dotnet/SqlClient#394] opened 2020-01-22 09:49 UTC
Hi all, 
We migrated on-prem sql databases to Azure SQL Databases and after migration, during monitoring the services we see exceptions stating "A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable).". We are getting this error intermittently.  The consumer service itself is in on-prem whilst the database is in Azure.

**Technical Details:**
Dot.net Core Version: .net core 2.2.0
SqlClient Version: 4.5.1
Sqlserver : Azure Sql Server

**The stack trace :** 
```
{
  "Depth": 0,
  "ClassName": "System.Data.SqlClient.SqlException",
  "Message": "A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)",
  "Source": ".Net SqlClient Data Provider",
  "StackTraceString": "   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\r\n   at System.Data.SqlClient.SqlDataReader.get_MetaData()\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate)\r\n   at lambda_method(Closure , QueryContext , ApiScope , Object[] )\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup)\r\n   at lambda_method(Closure , QueryContext , ApiScope )\r\n   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)\r\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)",
  "RemoteStackIndex": 0,
  "ExceptionMethod": {
    "Name": "OnError",
    "AssemblyName": "System.Data",
    "AssemblyVersion": "4.0.0.0",
    "AssemblyCulture": "",
    "ClassName": "System.Data.SqlClient.SqlConnection",
    "Signature": "Void OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1[System.Action])",
    "MemberType": 8
  },
  "HResult": -2146232060
}
```

**Exception Details:**
 ExceptionDetail.Message:A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)
 ExceptionDetail.Number:-1
 ExceptionDetail.Source:.Net SqlClient Data Provider
 ExceptionDetail.Type:System.Data.SqlClient.SqlException
 SourceContext:Microsoft.EntityFrameworkCore.Query
 ContextType:IdentityServer4.EntityFramework.DbContexts.ConfigurationDbContext

**What we applied to solve issue:**
1-Apply custom execution strategy
2-Apply connection resiliency scenarious
3-upgrade nuget packages
4-change connection policy from "Default" to "Redirect" and open required ports as Microsoft Azure team suggested

 
Any help will be very appreciated.
Thanks in advance

**Comment by cheenamalhotra** [comment] 2020-01-22 15:15
@husnusinterxion 

> 4-change connection policy from "Default" to "Redirect"

Could you try reverting this change and verify? I remember having issues with another driver before when policy is changed to "Redirect".

**Comment by husnusinterxion** [comment] 2020-01-23 16:39
@cheenamalhotra , this is what Microsoft recommends when using Azure Sql Database. 
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connectivity-architecture 
What issues did you have when it is "Redirect" ?

**Comment by cheenamalhotra** [comment] 2020-01-23 17:21
I haven't heard of issues in this driver so far, but there have been reported issues in JDBC and Go drivers for SQL Server where host name changes due to "Azure's Redirect mode" and driver doesn't validate the new hostname with servername provided with user as they don't match, so I was wondering if that could be something to verify here too.

This is just a possibility if "Redirect" mode turns out to change behavior.

I'd also like to know if there's a pattern when this error starts occurring and which OS have you reproduced this with and if you can also reproduce this with newer versions of System.Data.SqlClient or Microsoft.Data.SqlClient instead?

**Comment by husnusinterxion** [comment] 2020-01-24 09:33
Indeed, actually I opened this [ticket ](https://github.com/dotnet/efcore/issues/19657)to EF team but they forwarded me to Sql team.
I am very confused about "redirect" mode that it causes issue whereas Microsoft team suggests it to use...
EF is used in the application and it is running on Windows OS. 
it worths to try to use the newest version of  System.Data.SqlClient or Microsoft.Data.SqlClient....

**Comment by cheenamalhotra** [comment] 2020-01-24 15:26
@husnusinterxion 

I'm not saying it causes issue, I'm asking you to disable it and then test again, if it's possible in your test environment.

If it's not possible to test, please provide your repro here that reproduces issue to us so we can test.

**Comment by cheenamalhotra** [comment] 2020-03-04 16:15
@husnusinterxion 

Following up on the issue, do you have a repro you could provide that we can investigate?

**Comment by penihel** [comment] 2020-03-31 11:51
I had this problem when i update the package **System.Data.SqlClient** from  **Version=4.6.1.0** to **Version=4.6.1.1**.

So when i rollback to **Version=4.6.1.0**  problem resolved

**Comment by cheenamalhotra** [comment] 2020-04-03 21:23
@penihel 

Have you also tested with Microsoft.Data.SqlClient versions and have experienced issues? If not, could you try the same and let us know?

**Comment by DavoudEshtehari** [comment] 2020-05-03 21:24
Hi @husnusinterxion,
 
This error seems that pertains to the insufficient resources in the server like max locks exceeded, not enough memory, other internal server limits reached, etc.
Did you try to set the `Auto Close` option on your database to `False`?
Also you can add the retry logic to the DbContext on error number 19 failure.

**Comment by husnusinterxion** [comment] 2020-05-04 11:02
Hi @DavoudEshtehari ,
I did `AutoClose` opt'on to false but it didnt solve the issue.
Also I added the retry logic handlers to the DBContext but the sql error number is not 19 it is -1 which means Unknown. -1 is not  a transient error so that the handler does not create a fresh connection...

**Comment by cheenamalhotra** [comment] 2020-11-27 22:57
This issue should have been resolved by now, since we enhanced Azure connectivity and access token renewal for pooled connections. Could you try with Microsoft.Data.SqlClient latest version and let us know if you still experience this error?

**Comment by cheenamalhotra** [comment] 2021-05-26 18:57
Closing due to inactivity.

**Closed by cheenamalhotra** 2021-05-26 18:57 UTC
