### ISSUE TITLE
EF Core Begin Transaction | The connection is broken and recovery is not possible

### ISSUE THREAD

**Issue by mohanrkrishna** [dotnet/SqlClient#64] opened 2019-03-12 02:43 UTC
Hi - 
I am building .Net core app (2.2) using EF Core/SQL server. Defined repository classes for each model , each repository class has dBContext member (Of Type dBContext class) to perform dB operations.  In startup class defined DI and using options for dBContext

`services.AddDbContext<AppDbContext>(options => options.UseSqlServer(Configuration));`

Everything explained below works fine with out explicit transaction(like BeginTransaction) -> 
   Adding a row to table1& table2 and importing 100 rows to staging table , running SQL query using 
   ExecuteSqlCommand 

But when i try to wrap all above in EF Core transaction using context.Database.BeginTransaction , getting below error. SQL server is up & running as same code works with out explicit transaction. Please assist how to troubleshoot & resolve this issue. Thanks very much!

`The connection is broken and recovery is not possible.  The connection is marked by the server as unrecoverable.  No attempt was made to restore the connection.;
` `at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) `

**Comment by divega** [comment] 2019-05-16 00:55
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by cheenamalhotra** [comment] 2019-07-11 20:04
Hi @mohanrkrishna 

Do you have same project ready for this issue?

**Comment by cheenamalhotra** [comment] 2019-10-08 00:16
Hi @mohanrkrishna 

Please provide us a repro to investigate further.

Thanks!

**Comment by mohanrkrishna** [comment] 2019-10-10 12:14
Hi @cheenamalhotra - Sorry could not create sample. We went ahead without explicit transaction for now. With try to get sample at the earliest. Thanks!

**Comment by cheenamalhotra** [comment] 2020-08-06 22:01
Closing as duplicate of #78

**Closed by cheenamalhotra** 2020-08-06 22:01 UTC
Labels: :information_source: Needs more Info
