### ISSUE TITLE
Why `Microsoft.Data.SqlClient` has dependency to `Microsoft.Identity.Client`?

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/SqlClient#670] opened 2020-07-27 15:52 UTC
Why `Microsoft.Data.SqlClient` has dependency to `Microsoft.Identity.Client`?

**Comment by cheenamalhotra** [comment] 2020-07-27 16:47
Hi @dehghani-mehdi 

We use Microsoft.Identity.Client (MSAL for .NET) to support Azure Active Directory authentication modes:
- Active Directory Password
- Active Directory Integrated
- Active Directory Interactive
- Active Directory Service Principal

May I ask if you are facing any issues? Could you elaborate?

**Comment by dehghani-mehdi** [comment] 2020-07-28 10:12
Hi @cheenamalhotra 

Yes, the description of [Microsoft.Identity.Client](https://www.nuget.org/packages/Microsoft.Identity.Client) package is as follow:

> This package contains the binaries of the Microsoft Authentication Library for .NET (MSAL.NET).
     MSAL.NET makes it easy to obtain tokens from the Microsoft identity platform for developers (formally Azure AD v2.0) signing-in users with work & school accounts, Microsoft personal accounts and social identities Azure AD B2C. These tokens again access to Microsoft Cloud API and any other API secured by the Microsoft identity platform. This version supports adding authentication functionality to your .NET based client on Windows desktop (.NET 4.5+), UWP, .NET Core, Xamarin iOS and Xamarin Android.

But I'm wondering how identitcation is relevent here? `Microsoft.Data.SqlClient` is just a data provider, again here is description of this package:

> Provides the data provider for SQL Server. These classes provide access to versions of SQL Server and encapsulate database-specific protocols, including tabular data stream (TDS)
>
>Commonly Used Types:
Microsoft.Data.SqlClient.SqlConnection
Microsoft.Data.SqlClient.SqlException
Microsoft.Data.SqlClient.SqlParameter
Microsoft.Data.SqlClient.SqlDataReader
Microsoft.Data.SqlClient.SqlCommand
Microsoft.Data.SqlClient.SqlTransaction
Microsoft.Data.SqlClient.SqlParameterCollection
Microsoft.Data.SqlClient.SqlClientFactory

Why this low level package should worry about Active Directory, Azure and ...?

> May I ask if you are facing any issues? Could you elaborate?

Sure, no, I didn't, but I think having unnecessary dll/dependency should consider as issue.

**Comment by cheenamalhotra** [comment] 2020-07-28 16:22
Hi @dehghani-mehdi 

Driver's support for Active Directory authentication modes is built-in, i.e. another dependency is not needed in order to authenticate as: Active Directory Password/Integrated/Interactive/Service principal, authentication modes and more are to come. MSAL is the new library and has replaced ADAL library that was used by System.Data.SqlClient.

The federated authentication design has always been built-in and moving away from it would have caused a lot of disturbance in community for existing SqlClient customers hence we chose to keep it backwards compatible. It's not impossible to do but Azure SQL is as much important to us as SQL Server and is heavily used, thus AD authentication is available in the driver as-is.

Also NuGet does not have a concept of Optional dependencies like Maven (https://github.com/NuGet/Home/issues/686), otherwise it would have been a perfect candidate.

**Comment by cheenamalhotra** [comment] 2020-07-31 21:24
Closing as by design.

**Closed by cheenamalhotra** 2020-07-31 21:24 UTC
Labels: By Design

**Comment by dehghani-mehdi** [comment] 2020-08-01 06:10
All issues could be closed as by desgin.

**Comment by waf** [comment] 2020-12-28 03:46
Just as a note for any future, fellow troubleshooters:

Due to this dependency, the dependency chain for EF Core looks like this:

- Entity Framework Core depends on:
  - Microsoft.Data.SqlClient, which in turn depends on:
    - Microsoft.Identity.Client, [which depends on](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/757):
      - System.Windows.Forms

This is ultimately why upgrading to EF Core in an e.g. ASP.NET application or Console application pulls in Windows Forms. As far as I can tell it's completely harmless, though it does seem to trigger confusing static analysis warnings, like suggesting `STAThread` attributes in non-windows forms applications (e.g. [RSPEC-4210](https://rules.sonarsource.com/csharp/RSPEC-4210)).

**Comment by brumlemann** [comment] 2020-12-28 15:42
- Entity Framework Core depends on:
- Microsoft.Data.SqlClient, which in turn depends on:
- Microsoft.Identity.Client, which depends on:
- System.Windows.Forms

Whaaat?!? Have we learnt nothing about inversion of control?
