### ISSUE TITLE
Getting MSAL to work with Microsoft.Data.SqlClient to create an azure database on sql server

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/SqlClient#1697] opened 2022-08-08 23:58 UTC
We have a desktop app our customers purchase, and some customers want to access azure while running azure ad. We use a DbConnectionInterceptor to determine if azure is used and get the access token. This code is put together from the [WPF app example](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-windows-desktop).  What should the Authentication setting be, for Microsoft.Data.SqlClient connection string, is my first question. Next why does this have an error with the connection string:

`Data Source=tcp:foo.database.windows.net,1433;Pooling=True;Authentication=ActiveDirectoryIntegrated`

We are not setting a password.

![image](https://user-images.githubusercontent.com/5032382/183533926-f2b554c5-512c-4155-a8d8-cd67e1c23d15.png)

![image](https://user-images.githubusercontent.com/5032382/183533990-114d3787-e437-4eec-8c43-a85298fe4343.png)

Our code not event make it to our DbConnectionInterceptor.

`    public class AzureAdDbConnectorInterceptor : DbConnectionInterceptor
    {
        private static string ClientId = "c32c25e9-2f19-4171-ad22-83e969f65e57";

        private static string Tenant = "common";

        private static IPublicClientApplication _clientApp;

        public static IPublicClientApplication PublicClientApp { get { return _clientApp; } }

        static AzureAdDbConnectorInterceptor ()
        {
            _clientApp = PublicClientApplicationBuilder.Create ( ClientId )
                        .WithAuthority ( AzureCloudInstance.AzurePublic, Tenant )
                        .WithDefaultRedirectUri ()
                        .Build ();
        }

        public override InterceptionResult ConnectionOpening (
            DbConnection connection,
            ConnectionEventData eventData,
            InterceptionResult result )
        {
            
            var sqlConnection = ( SqlConnection ) connection;
            if ( DoesConnectionNeedAccessToken ( sqlConnection ) )
            {
                sqlConnection.AccessToken = GetAuthenticationToken ();
            }

            return base.ConnectionOpening ( connection, eventData, result );
        }

        public override async ValueTask<InterceptionResult> ConnectionOpeningAsync (
            DbConnection connection,
            ConnectionEventData eventData,
            InterceptionResult result,
            CancellationToken cancellationToken = default )
        {
            var sqlConnection = ( SqlConnection ) connection;
            if ( DoesConnectionNeedAccessToken ( sqlConnection ) )
            {

                sqlConnection.AccessToken = GetAuthenticationToken ();
            }

            return await base.ConnectionOpeningAsync ( connection, eventData, result, cancellationToken );
        }

        private static bool DoesConnectionNeedAccessToken ( SqlConnection connection )
        {
            var connectionStringBuilder = new SqlConnectionStringBuilder ( connection.ConnectionString );

            var dataSource = connectionStringBuilder.DataSource;

            var contains = false;

            if ( dataSource.Contains ( MsSqlConstants.AzureUrl, StringComparison.OrdinalIgnoreCase ) )
                contains = true;

            return contains;
                
                //&& string.IsNullOrEmpty ( connectionStringBuilder.UserID );
        }

        public string ResultText
        { get; set; }

        private string GetAuthenticationToken ()
        {
            AuthenticationResult authResult = null;

            var scopes = new List<string> () { "user.read", "user.write" };

            var accountResult = _clientApp.GetAccountsAsync ();
            accountResult.Wait ();

            var firstAccount = accountResult.Result.FirstOrDefault ();

            try
            {
                Task<AuthenticationResult> result = _clientApp.AcquireTokenSilent ( scopes, firstAccount ).ExecuteAsync ();

                result.Wait ();

                authResult = result.Result;

            }
            catch ( MsalUiRequiredException ex )
            {
                // A MsalUiRequiredException happened on AcquireTokenSilent.
                // This indicates you need to call AcquireTokenInteractive to acquire a token
                System.Diagnostics.Debug.WriteLine ( $"MsalUiRequiredException: {ex.Message}" );

                try
                {
                    Task<AuthenticationResult> result = 
                        _clientApp.AcquireTokenInteractive ( scopes ).
                            WithUseEmbeddedWebView ( true ).
                            ExecuteAsync ();

                    result.Wait ();

                    authResult = result.Result;

                }
                catch ( MsalException msalex )
                {
                    ResultText = $"Error Acquiring Token:{System.Environment.NewLine}{msalex}";
                }
            }
            catch ( Exception ex )
            {
                ResultText = $"Error Acquiring Token Silently:{System.Environment.NewLine}{ex}";

            }

            if ( authResult != null )
                return authResult.AccessToken;
            else
                return null;

        }
    }
`

**Comment by ErikEJ** [comment] 2022-08-09 05:49
What does GetValidatedConnectionString do - looks like Password has been assigned a value

**Comment by dgxhubbard** [comment] 2022-08-09 15:36
GetValidatedConnectionString is part of Microsoft.Data.SqlClient

**Comment by MichelZ** [comment] 2022-08-09 15:53
My guess is by using `ActiveDirectoryIntegrated` auth method as well as manually providing an access token does not mix well together. Use one or the other, but not both

**Comment by JRahnama** [comment] 2022-08-09 16:25
@dgxhubbard as @MichelZ  mentioned mixing these two is not a good idea. The very same process happens underneath to acquire an access token. If you want the driver to be responsible about acquiring tokens and validating their expiry times let the driver do it. Otherwise each token will be expired in about 10 hours and you will need to renew it. So, basically just let the connection string be as it is and take all acquiring token part out of your code or acquire access token manually and take the authentication part out of your connection string.

**Comment by dgxhubbard** [comment] 2022-08-15 21:59
@JRahnama When I remove the interceptor, so no asking for a token, and use ActiveDirectoryDefault then my connection string is:

`Data Source=foo.database.windows.net;Initial Catalog=FooDb;Pooling=True;Authentication=ActiveDirectoryDefault`

then I call Migrate to create my database I get the following error

![image](https://user-images.githubusercontent.com/5032382/184724666-0f2fd610-0a63-48a9-8d53-e18ba1126fb2.png)

![image](https://user-images.githubusercontent.com/5032382/184724773-2123e6aa-573d-46d0-8f83-eb3512dd91c6.png)

I am expecting to be able to get an environment, interactive browser or I guess managed identity where the access token will be retrieved from, and that vs, azure cli, azure power shell etc will not get in the way.

Why am I getting JSON RPC exception?

**Comment by dgxhubbard** [comment] 2022-08-15 22:13
If I use the interceptor, and no Authentication in the connection string my connection string is:

`Data Source=foo.database.windows.net;Initial Catalog=FooDb;Pooling=True;Authentication=ActiveDirectoryDefault`

I get the access token, through interactive, and then get a login error.

![image](https://user-images.githubusercontent.com/5032382/184727059-92df33bf-83d5-44c3-81f2-38ba5790651f.png)

Is there some way to get this working.

**Comment by lcheunglci** [comment] 2022-08-16 23:16
Hi, I'm going to try to setup the azure environment and attempt to reproduce this with some of the code you provided and get back to you soon.

**Comment by dgxhubbard** [comment] 2022-08-18 15:31
@lcheunglci thanks I appreciate it

**Comment by lcheunglci** [comment] 2022-08-19 21:57
I've been trying to set up the environment but I don't seem to have the proper access to create an azure app and my azure account does not have proper access for Azure Active Directory to follow some of steps. According to the [ADO.NET docs](https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver15#using-active-directory-default-authentication) using `Authentication=Active Directory Default;` should acquire the access token for you and tries 6 different approaches so if that fails, I suspect that it might not be configured properly.  Unfortunately, I'm fairly new in using Azure suite, so perhaps someone else could chime in to give further assistance. As for the JSON-RPC error, I did a quick search and I noticed other products with that same error usually means there's a possible network issue perhaps with the configuration as well.

**Comment by lcheunglci** [comment] 2022-08-22 18:08
@dgxhubbard  Quick question: have you tried connecting using [Microsoft SQL Server Management Studio](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)? I got a similar error when my account wasn't added to the external provider list and also when I didn't have specify the database that I had access to.  
![failed-to-login](https://user-images.githubusercontent.com/31262254/185986718-637856be-258f-4185-93e9-fb1f6f076a7e.png)
If your account doesn't have access, you may need to add your account using your SA account and run the following query `create user [user name] from external provider`
and you may also need to white list the IP address that it's connecting from under one of the azure settings under Network > Firewall rules
Once you can confirm that the account exists and have proper access.  Make sure you sure you specify the `initial catalog` in the connection string.

In SMSS, when I was connecting, I specified `Azure Active Directory - Universal with MFA` under `Authentication` and expand the `Options` and under the `Connection Properties` tab, and in `Connect to database` textbox, I specified my `Initial Catalog` i.e. in my case the `Northwind` db and it worked.
![image](https://user-images.githubusercontent.com/31262254/185988563-bb3edda5-93c0-4bda-9719-9d6ce64b8eb9.png)

Again, for me, after I got my account got access, and specified the initial catalog, I was able to connect successfully.

**Comment by dgxhubbard** [comment] 2022-08-22 20:15
@lcheunglci I have access through SSMS without problems. I am including a full sample here. I am using MSAL and I get the access token and set it  in the SqlConnection. I can create this database on a local sql server. When I try on my azure sql server, that is mixed mode, and has a azure ad admin I get an error unable to login with principal:

`Login failed for user '<token-identified principal>'.`

I created the server through a free azure account, then setup azure ad with one user, and made that user the azure ad admin on the sql server. I registered my test app, then gave the app permissions to the sql server through "APIs my orginization usage". When I run the migrate there are a number of Microsoft.Data.SqlClient.SqlExceptions and I get the the final error message.

MSAL get access token seems to work it has the user I created in azure ad.

![image](https://user-images.githubusercontent.com/5032382/186008906-28d97404-8b6c-449f-a82c-b8971be3857c.png)

In the example type the azure sql server url, and database name and click create.


[CoreWpf.zip](https://github.com/dotnet/SqlClient/files/9397270/CoreWpf.zip)

**Comment by lcheunglci** [comment] 2022-08-22 21:40
Hi @dgxhubbard, thanks for sharing the repro code sample.  I'll need to spend some more time to investigate.

**Comment by dgxhubbard** [comment] 2022-08-22 21:59
Hi @Icheungcli all good

**Comment by JRahnama** [comment] 2022-08-22 22:02
@dgxhubbard I saw some mixed references of `Microsoft.Data.SqlClient` and `System.Data.SqlClient`. Can you manually change them all to `Microsoft.Data.SqlClient` and make a direct reference to `Microsoft.Data.SqlClient v5.0` in your csproj to override any other existing versions of M.D.SqlClient to see the outcome please?

**Comment by dgxhubbard** [comment] 2022-08-22 23:06
@JRahnama replacing the using statements and adding Microsoft.Data.SqlClient had the same result.
The migrate runs produces lots of sql exceptions, and login fails. Adding new code here to make sure I did this right.

[CoreWpf.zip](https://github.com/dotnet/SqlClient/files/9398149/CoreWpf.zip)

**Comment by lcheunglci** [comment] 2022-08-24 19:35
Hi @dgxhubbard , I didn't manage to get the `common` tenant to work, but I manage to retrieve the access token using my own `Directory (tenant) id` but I had to go through the `PublicClientApp.AcquireTokenInteractive` instead of `PublicClientApp.AcquireTokenSilent` and change the exception handle logic as an empty `firstAccount` throws an `AggregateException` instead of a `MsalUiRequiredException` where the interactive authentication is triggered as my a client app retrieved an empty list of accounts when calling `PublicClientApp.GetAccountsAsync` but I got as far as throwing an exception when it attempted to create the database from EFCore but fails due to my read only access to it, but I assume once I am granted access to create/write, it should hopefully work.

**Comment by dgxhubbard** [comment] 2022-08-24 21:13
Hi @Icheunglci, the AcquireTokenSilent does not fail over with the MsalUiRequiredException, it just fails when firstAccount is null. That is why I changed the code to:

`
            IAccount firstAccount;

            var accountResult = PublicClientApp.GetAccountsAsync ();
            if ( accountResult == null )
                throw new NullReferenceException ( "FAILED to get accounts" );

            accountResult.Wait ();

            firstAccount = accountResult.Result.FirstOrDefault ();
            if ( firstAccount == null )
            {
                try
                {
                    var authResult = PublicClientApp.AcquireTokenInteractive ( _azureSqlScopes )
                        .WithAccount ( firstAccount )
                        .WithParentActivityOrWindow ( handle )
                        .WithPrompt ( Prompt.SelectAccount )
                        .ExecuteAsync ();

                    authResult.Wait ();


                    AccessToken = authResult.Result.AccessToken;
                }
                catch ( MsalException msalex )
                {
                    Debug.WriteLine ( msalex.Message );
                }

            }
            else
            {

                try
                {
                    var authSilentResult = PublicClientApp.AcquireTokenSilent ( _azureSqlScopes, firstAccount ).ExecuteAsync ();

                    authSilentResult.Wait ();

                    AccessToken = authSilentResult.Result.AccessToken;
                }
                catch ( MsalUiRequiredException ex )

                //try
                {
                    try
                    {
                        var authResult = PublicClientApp.AcquireTokenInteractive ( _azureSqlScopes )
                            .WithAccount ( firstAccount )
                            .WithParentActivityOrWindow ( handle )
                            .WithPrompt ( Prompt.SelectAccount )
                            .ExecuteAsync ();

                        authResult.Wait ();


                        AccessToken = authResult.Result.AccessToken;
                    }
                    catch ( MsalException msalex )
                    {
                        Debug.WriteLine ( msalex.Message );
                    }
                }
                catch ( Exception ex )
                {
                    Debug.WriteLine ( ex.Message );
                    return;
                }
            }

`

This is about the best [article](https://blogs.aaddevsup.xyz/2021/06/how-to-use-an-access-token-to-connect-to-an-azure-sql-database/) I have seen. Is this a matter of permissions in azure? I have followed what is in that article along with changing the old style code that azure platform has as an example. We have to do this as a multi tenant app, because our customers will expect to be able to create their db on their azure sql server. What would I need to do to get this working?

**Comment by lcheunglci** [comment] 2022-08-25 16:56
Unfortunately, the azure setup process is something out of scope for what our team is able to provide and I had to use a pre-configured setup from our tests instead of my own app as it's a bit complicated.  I feel like this is a login issue with MSAL than with SqlClient itself as once the AccessToken is provided in the connection string successfully, I was able to run the migration.  Perhaps you can ask for further assistant from the [MSAL repo](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues)

**Comment by dgxhubbard** [comment] 2022-08-25 17:06
Thanks @lcheunglci I will give it a try, I can't even get azure assistance with the issue.

**Comment by David-Engel** [comment] 2022-08-25 22:17
@dgxhubbard 

Is there a reason you need to use the DbConnectionInterceptor at all? Are there Azure AD authentication methods you need in your app that are not already built-in to M.D.SqlClient using the Authentication= keyword? (For reference, see [Using Azure Active Directory authentication with SqlClient](https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16))

Managing Access Token acquisition and renewal yourself is difficult, so I'd avoid it if you can.

**Comment by dgxhubbard** [comment] 2022-08-26 00:11
Using SqlClient with setting Authentication to "Active Directory Interactive" was one of my first attempts, but I could not get it working. Then found MSAL after Azure Identity, and MSAL has superseded Azure Identity. MSAL manages the token, and caches it so you can most of the time silently get the token. That almost works, but the problem is the first time you get the token the call to the silent method fails with an aggregate exception, because you attempt to get the an account before the call will return null and the pattern for MSAL is that the silent call fails with MsalUiRequiredException, and in the exception handler you can call AcquireTokenInteractive. Other than that problem, I want able to get the token and set it in interceptor, but the call to Migrate produces alot of SqlException and results in the error login failed for principal.

**Comment by dgxhubbard** [comment] 2022-08-26 00:17
I am trying to find the source of the error. Is it my setup of the Azure sql server and Azure Ad, or is it something wrong in the code. The documentation of connecting to azure sql server is somewhat confusing, so that is why the setup could be wrong. On top of that the changes to the API in the last two years adds to the problem. There are many references for connecting to an existing database, but I have not seen much on running EF Core migrations on an azure sql server to create the database.

**Comment by JRahnama** [comment] 2022-09-16 01:28
Closing the issue as there is nothing more to be done from our side.

**Closed by JRahnama** 2022-09-16 01:28 UTC
Labels: :no_entry_sign: Won't Fix
