### ISSUE TITLE
SqlConnection.OpenAsync causes Windows Forms, WPF, WebView2, etc to be included in trimmed output

### ISSUE THREAD

**Issue by jnm2** [dotnet/SqlClient#2548] opened 2024-06-03 20:12 UTC
A console app that calls a Windows-only API (and thus targets `net8.0-windows`), simply by including a call to SqlConnection.OpenAsync, brings in a ton of UI dependencies and their native libraries.

Removing the call to OpenAsync removes most of the problem but continues bringing in System.Windows.Forms.Design. Removing `new SqlConnection` fixes that.

SqlConnection.OpenAsync should be able to be used without bringing in UI dependencies.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
  </ItemGroup>

</Project>
```

```c#
using Microsoft.Data.SqlClient;

await using var connection = new SqlConnection("Data Source=(local);Integrated Security=True");
await connection.OpenAsync();
```

```
dotnet publish
```

Files in publish output:

<details>

- Accessibility.dll
- Azure.Core.dll
- Azure.Identity.dll
- clretwrc.dll
- clrgc.dll
- clrjit.dll
- coreclr.dll
- createdump.exe
- D3DCompiler_47_cor3.dll
- DirectWriteForwarder.dll
- hostfxr.dll
- hostpolicy.dll
- Microsoft.Data.SqlClient.dll
- Microsoft.Data.SqlClient.SNI.dll
- Microsoft.DiaSymReader.Native.amd64.dll
- Microsoft.Identity.Client.dll
- Microsoft.Identity.Client.Extensions.Msal.dll
- Microsoft.Identity.Client.NativeInterop.dll
- Microsoft.IdentityModel.Abstractions.dll
- Microsoft.SqlServer.Server.dll
- Microsoft.Web.WebView2.Core.dll
- Microsoft.Web.WebView2.WinForms.dll
- Microsoft.Win32.Primitives.dll
- Microsoft.Win32.Registry.dll
- Microsoft.Win32.SystemEvents.dll
- msalruntime.dll
- mscordaccore_amd64_amd64_8.0.524.21615.dll
- mscordaccore.dll
- mscordbi.dll
- mscorlib.dll
- mscorrc.dll
- msquic.dll
- netstandard.dll
- PenImc_cor3.dll
- PresentationCore.dll
- PresentationFramework.dll
- PresentationNative_cor3.dll
- PresentationUI.dll
- ReachFramework.dll
- Repro.deps.json
- Repro.dll
- Repro.exe
- Repro.pdb
- Repro.runtimeconfig.json
- System.Collections.Concurrent.dll
- System.Collections.dll
- System.Collections.Immutable.dll
- System.Collections.NonGeneric.dll
- System.Collections.Specialized.dll
- System.ComponentModel.dll
- System.ComponentModel.EventBasedAsync.dll
- System.ComponentModel.Primitives.dll
- System.ComponentModel.TypeConverter.dll
- System.Configuration.ConfigurationManager.dll
- System.Console.dll
- System.Data.Common.dll
- System.Design.dll
- System.Diagnostics.Debug.dll
- System.Diagnostics.DiagnosticSource.dll
- System.Diagnostics.EventLog.dll
- System.Diagnostics.FileVersionInfo.dll
- System.Diagnostics.Process.dll
- System.Diagnostics.StackTrace.dll
- System.Diagnostics.TraceSource.dll
- System.dll
- System.Drawing.Common.dll
- System.Drawing.Design.dll
- System.Drawing.dll
- System.Drawing.Primitives.dll
- System.Formats.Asn1.dll
- System.IO.Compression.Brotli.dll
- System.IO.Compression.dll
- System.IO.Compression.Native.dll
- System.IO.FileSystem.AccessControl.dll
- System.IO.FileSystem.Watcher.dll
- System.IO.IsolatedStorage.dll
- System.IO.MemoryMappedFiles.dll
- System.IO.Packaging.dll
- System.IO.Pipes.dll
- System.Linq.dll
- System.Linq.Expressions.dll
- System.Memory.Data.dll
- System.Memory.dll
- System.Net.Http.dll
- System.Net.HttpListener.dll
- System.Net.NameResolution.dll
- System.Net.NetworkInformation.dll
- System.Net.Primitives.dll
- System.Net.Quic.dll
- System.Net.Requests.dll
- System.Net.Security.dll
- System.Net.ServicePoint.dll
- System.Net.Sockets.dll
- System.Net.WebClient.dll
- System.Net.WebHeaderCollection.dll
- System.ObjectModel.dll
- System.Printing.dll
- System.Private.CoreLib.dll
- System.Private.Uri.dll
- System.Private.Xml.dll
- System.Private.Xml.Linq.dll
- System.Reflection.Metadata.dll
- System.Runtime.Caching.dll
- System.Runtime.CompilerServices.VisualC.dll
- System.Runtime.dll
- System.Runtime.Extensions.dll
- System.Runtime.InteropServices.dll
- System.Runtime.Numerics.dll
- System.Runtime.Serialization.Formatters.dll
- System.Security.AccessControl.dll
- System.Security.Claims.dll
- System.Security.Cryptography.dll
- System.Security.Cryptography.ProtectedData.dll
- System.Security.Principal.Windows.dll
- System.Text.Encoding.CodePages.dll
- System.Text.Encodings.Web.dll
- System.Text.Json.dll
- System.Text.RegularExpressions.dll
- System.Threading.Channels.dll
- System.Threading.dll
- System.Threading.Thread.dll
- System.Transactions.Local.dll
- System.Windows.Extensions.dll
- System.Windows.Forms.Design.dll
- System.Windows.Forms.dll
- System.Windows.Forms.Primitives.dll
- System.Windows.Input.Manipulations.dll
- System.Xaml.dll
- System.Xml.Linq.dll
- UIAutomationProvider.dll
- UIAutomationTypes.dll
- vcruntime140_cor3.dll
- WebView2Loader.dll
- WindowsBase.dll
- wpfgfx_cor3.dll

</details>

**Comment by dauinsight** [comment] 2024-06-04 17:51
Hi @jnm2, we will look further into this and get back to you with our findings.

**Comment by kf-gonzalez2** [comment] 2024-06-04 18:26
This functionality is current by design, however there is a feature improvement planned under #1108 that would address this issue. Marking this as a duplicate.

**Closed by kf-gonzalez2** 2024-06-04 18:26 UTC
Labels: untriaged
