### ISSUE TITLE
A network-related or instance-specific error occurred while establishing a connection to SQL Server. On AWS Lambda

### ISSUE THREAD

**Issue by pnquest** [dotnet/SqlClient#839] opened 2020-12-04 14:47 UTC
### Describe the bug
With version `2.1.0` of `Microsoft.Data.SqlClient` attempts to connect to a SQL server database that is not hosted in AWS are met with the below exception. 

After failing to find any other cause for this error I rolled back to version `2.0.1` and everything worked fine. I did not see this issue on my local (windows) machine.
```
Exception message: 

Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)

Stack trace:

 at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, SqlAuthenticationMethod authType)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
```

### To reproduce
Attempt to open a connection to a sql server database hosted outside aws from a lambda function.

### Expected behavior
The connection should work fine, just like it does in package versions previous to this.

### Further technical details
Microsoft.Data.SqlClient version: 2.1.0
.NET target: core 3.1
SQL Server version: SQL Server 2017
Operating system: AWS Lambda Runtime

**Comment by pnquest** [comment] 2020-12-04 15:11
After a bit more investigation I think this is a Linux vs Windows thing, and doesn't have anything to do with AWS, Lambda, or the fact that the database is hosted outside AWS.

**Comment by JRahnama** [comment] 2020-12-04 17:33
@pnquest 

> After a bit more investigation I think this is a Linux vs Windows thing, and doesn't have anything to do with AWS, Lambda, or the fact that the database is hosted outside AWS.

Is the issue still Microsoft.Data.SqlClient related? If yes, can you provide us a sample repro? besides that can you share your connection string properties?

**Comment by pnquest** [comment] 2020-12-04 17:50
@JRahnama 

> Is the issue still Microsoft.Data.SqlClient related? If yes, can you provide us a sample repro? besides that can you share your connection string properties?

Yes, It is definitely the library. There doesn't seem to be much to the repro it fails the instant you call Open:

``` C#
var con = new SqlConnection(conString);
con.Open();
```

The trick seems to be that it only occurs on certain platforms, and not others (Win 10 is fine, but whatever underpins the lambda runtime, Amazon Linux 2 I assume, is not).

Whatever caused this was introduced in the latest release, every prior version this same code works just fine.

The connection string looks like this:

`Server=SERVERNAME.DOMAINNAME\\INSTANCENAME; Database=DB_NAME; Encrypt=yes; TrustServerCertificate=true; User Id={userId}; Password={password}`

**Comment by Wraith2** [comment] 2020-12-04 21:38
Psychic debugging attempt. Look at the tls versions that the linux machine you're using has setup, recent docker containers on things like alpine have had known problems with not enabling the required version.

**Comment by pnquest** [comment] 2020-12-05 00:00
@Wraith2 any idea how I would go about checking those from inside a c# program? 

@JRahnama Did this latest release drop support for a TLS version? That seems like it would have belonged in a `3.0.0` release rather than `2.1.0`.

**Comment by JRahnama** [comment] 2020-12-08 16:31
@pnquest we did not drop support for TLS versions. our driver captures the requested TLS from user and passes that to Sql server. Saying that, if anything happens it will happen at server side not at the driver level.
you can enforce TLS version inside your C# application by 
`ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;`

**Comment by pnquest** [comment] 2020-12-11 15:24
@JRahnama if that is the case, it seems unlikely that @Wraith2 is correct. The runtime platform did not change, the library did.

**Comment by JRahnama** [comment] 2020-12-22 17:37
@pnquest can you test your application with the[ latest hotfix release](https://www.nuget.org/packages/Microsoft.Data.SqlClient/) of 2.1.1 to see if the issue comes up?

**Comment by pnquest** [comment] 2020-12-28 14:09
@JRahnama Unfortunately, it did not solve the issue. The error remains the same.

**Comment by cheenamalhotra** [comment] 2020-12-29 17:55
@pnquest 

Could you also try with 2.1.0 preview 1 and 2 versions to help us reach change-set that causes this issue?

**Comment by pnquest** [comment] 2020-12-30 14:49
@cheenamalhotra I just tried both. Preview 1 works fine, but preview 2 fails.

**Comment by MuhKuh7** [comment] 2021-01-20 12:00
I can confirm the same issue running version 2.1.1 in a docker container `mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim`. It works when downgrading to an older version.

**Comment by cheenamalhotra** [comment] 2021-01-22 22:12
Hi @pnquest 

PR https://github.com/dotnet/SqlClient/pull/874 will fix this issue it seems since you're connecting to Instance name as well.
Please try with the changes we made in this PR by running test with this NuGet: [Build CI Artifacts](https://dev.azure.com/sqlclientdrivers-ci/sqlclient/_build/results?buildId=22370&view=artifacts&pathAsName=false&type=publishedArtifacts) and let us know.

We shall release this fix in v2.1.2 patch version soon.

**Comment by pnquest** [comment] 2021-01-25 12:37
@cheenamalhotra Thanks for taking care of this! I unfortunately won't be able to deploy this to our environment if it isn't on nuget. Could you release it as a preview? If not maybe @MuhKuh7 could verify?

**Comment by davesmits** [comment] 2021-01-28 16:53
@cheenamalhotra is there an ETA on when package will be published?

**Comment by cheenamalhotra** [comment] 2021-02-01 18:55
Hi @davesmits 

We're working on a few important changes also candidate for this release, it's planned to be released as soon as we're ready, but latest by mid-February.

**Comment by tarasverq** [comment] 2021-02-26 14:23
@cheenamalhotra can I ask you to send artifacts link posted [here](https://github.com/dotnet/SqlClient/issues/839#issuecomment-765713424) one more time?

**Comment by cheenamalhotra** [comment] 2021-02-26 18:23
Hi @tarasverq 

Sure, I'm uploading NuGet here (rebuilt) you can try:
[Microsoft.Data.SqlClient.2.1.0-pull-4c45dce.21057.1.zip](https://github.com/dotnet/SqlClient/files/6051627/Microsoft.Data.SqlClient.2.1.0-pull-4c45dce.21057.1.zip)

**Comment by cheenamalhotra** [comment] 2021-03-05 22:25
Hi @davesmits @tarasverq 

[Microsoft.Data.SqlClient v2.1.2](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.2) is now released that contains the fix.
Closing issue as resolved.

**Closed by cheenamalhotra** 2021-03-05 22:25 UTC
