### ISSUE TITLE
SqlConnection.Clone doesn't copy AccessTokenCallback

### ISSUE THREAD

**Issue by rayao** [dotnet/SqlClient#2524] opened 2024-05-22 11:41 UTC
I'm not sure it's bug or by design, if by design, can you explain why?

**Comment by kf-gonzalez2** [comment] 2024-05-22 18:07
Can you please elaborate further on the issue? please include any repro steps or more explanation

**Comment by ErikEJ** [comment] 2024-05-22 19:01
@kf-gonzalez2 There is a originating issue here: https://github.com/ErikEJ/EntityFramework6PowerTools/issues/147 and a follow up PR for EF 6 here: https://github.com/ErikEJ/EntityFramework6PowerTools/pull/150 - I think this could be "by design"

**Comment by roji** [comment] 2024-05-22 19:22
FWIW I think the main usefulness in DbConnection.Clone() is precisely to clone the authentication information, so that the clone can actually be opened successfully. For example, the password does get copied to clones, so I'm not sure why AccessTokenCallback would be treated any differently:

```c#
var connection1 = new SqlConnection("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false");
connection1.Open();

var connection2 = (SqlConnection)((ICloneable)connection1).Clone();
connection2.Open();
```

**Comment by ErikEJ** [comment] 2024-05-22 19:25
@roji Thanks for joining! Yeah. could be an oversight - AccessTokenCallback was just added to 5.2.

Would be great to get it fixed in SqlClient. so that Microsoft.EntityFramwork.SqlServer could take advantage (by using a newer SqlClient). I think adding the above "fix" to that is out of scope.

**Comment by David-Engel** [comment] 2024-05-22 19:36
I agree, this seems to be a simple oversight in the original implementation. We should fix this in MDS.

**Closed** 2024-05-23 19:10 UTC
Labels: :bug: Bug!
