### ISSUE TITLE
Microsoft.Data.SqlClient.SqlConnection is converting DateTime objects to datetime2 columns incorrectly.

### ISSUE THREAD

**Issue by ClaytonAndTheClayTones** [dotnet/SqlClient#2117] opened 2023-08-08 02:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using Microsoft.Data.SqlClient.SqlConnection.QuerySingleAsync to call a sql insert query, DateTime objects are not maintaining their millisecond precision when being inserted into a datetime2 column, instead reverting to the old datetime behaviour of only storing the milliseconds ending with 000, 003, or 007.   

Inserting the record directly via raw sql query works as expected:
 
![image](https://github.com/dotnet/aspnetcore/assets/2107874/446d575c-f036-4c0c-8b2d-8cc6324cceaa)

Note the highlighted value and column match with ending digits 222.

---

And now, from the following code:

```
using Microsoft.Data.SqlClient.SqlConnection connection = DatabaseConfig.GetConnection();

var result = await connection.QuerySingleAsync<UserDatabaseModel>(insertPackage.sql, insertPackage.parameters)
```

Let's look at the query and parameters:

![image](https://github.com/dotnet/aspnetcore/assets/2107874/463c20e7-e38f-42e3-919c-f27388912529)

Please note the Immediate window showing the sql query being sent into System.Data.SqlClient.SqlConnection's QuerySingleAsync function.

Then please refer to the highlighted items in the local windows that correspond to the @lockout_ends_at parameter.  The milliseconds are 222 as they should be.

I step forward and now the value returned by the database is incorrect:

![image](https://github.com/dotnet/aspnetcore/assets/2107874/0ac830eb-a545-491a-a802-ce5ab92f82e4)

The value in the database is also incorrect.  

The only thing that occurred between my correct value and the incorrect value is the DateTime object in question being converted to a value to place into my datetime2(7) column.  It should have preserved 222.  It did not.

### Expected Behavior

Since the columns are a datetime2 and not an original datetime, millisecond precision should be preserved.

### Steps To Reproduce

1. Use a General Use Azure Serverless Sql Server Database.
2. Use .NET Core 7
3. Use the code in the above example to insert a parameterized query.

### .NET Version

7.0.304

### Anything else?

Microsoft.NETCore.App v7.0.7

---

dotnet --info

```
 Version:   7.0.304
 Commit:    7e794e2806

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.304/

Host:
  Version:      7.0.7
  Architecture: arm64
  Commit:       5b20af47d9

.NET SDKs installed:
  6.0.410 [/usr/local/share/dotnet/sdk]
  7.0.304 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by JRahnama** [comment] 2023-08-08 18:40
@ClaytonAndTheClayTones can you provide a minimal repro with Microsoft.Data.SqlClient that does not use EF Core, so we can investigate the behavior.

**Comment by ClaytonAndTheClayTones** [comment] 2023-08-08 21:57
I may be mistaken but the above code in my repro steps isn't using EF at
all, it's generating the sql and parameters manually and calling
Microsoft.Data.SqlClient.SqlConnection.QuerySingleAsync
directly.   I'm not really sure how much more minimal I can get.

I am happy to assist/pair and show the repro on debugger etc with someone
if that's helpful.

The only surface area I can see where the "mistake" could be made is
whenever the QuerySingleAsync function takes the DateTime object and tries
to marshal it to a datetime2.  It seems like maybe it's marshalling it to a
datetime instead?

**Comment by roji** [comment] 2023-08-08 22:00
@ClaytonAndTheClayTones QuerySingleAsync isn't part of SqlClient (or ADO.NET), you may be using Dapper.

**Comment by ClaytonAndTheClayTones** [comment] 2023-08-08 22:05
> @ClaytonAndTheClayTones QuerySingleAsync isn't part of SqlClient (or ADO.NET), you may be using Dapper.

I am.  I was fooled into thinking it was part of SqlClient when I went crawling through the assemblies.  

Is Dapper the layer that would be asking SQL Server "what type is column x" and determining how to marshall the DateTime object?  That's where I'm convinced the error is happening.   Some driver logic says "Hey SqlServer what type is lockout_ends_at?" and SqlServer says "oh it's a datetime2" and the driver says "cool, datetime?  thanks!" and that's the bug.

I guess I'm unclear on whether that handshake is Dapper's responsibility or ADO's

**Comment by ClaytonAndTheClayTones** [comment] 2023-08-08 22:40
@JRahnama 

Ok yes I have a much simpler scenario for you, not using Dapper nor EF.

I directly assigned Parameters on an ADO SqlCommand object and it exhibited the same behaviour.

Proof incoming

**Comment by ClaytonAndTheClayTones** [comment] 2023-08-08 22:49
Ok here we go.  This screenshot shows:

- In the code window, I've just assigned user.LockoutEndsAt to dbCommand.Parameters.
- In the Immediate window I'm showing the value of user.LockoutEndsAt.   The milliseconds there are 222.
- in the locals window to the left, you can see the contents of dbCommand.Parameters.SyncRoot[10].   The ParameterName is "LockoutEndsAt".  The Value.Milliseconds is 222.  the SqlValue.Value.Milliseconds is 223.

It's happening when you assign the DateTime object to a parameter.

**Comment by JRahnama** [comment] 2023-08-08 23:34
@ClaytonAndTheClayTones can you zip the sample repro and paste it here to the conversation thread please.

**Comment by ClaytonAndTheClayTones** [comment] 2023-08-09 00:17
> @ClaytonAndTheClayTones can you zip the sample repro and paste it here to the conversation thread please.

Yep here you go

Just run the sln and it'll output the issue:

BrokenDateTime.zip

**Comment by JRahnama** [comment] 2023-08-10 21:57
@ClaytonAndTheClayTones, from the repro provided, the parameter you have defined  is not type of DateTime2.  Simply confirm it by adding below code you can see the type:

```C#
Console.WriteLine(dbCommand.Parameters[0].SqlDbType);
```

SqlDateTime has some limitation and in some cases it rounds up the milli seconds. From the [documentation](https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver16#rounding-of-datetime-fractional-second-precision):

> datetime values are rounded to increments of .000, .003, or .007 seconds, as shown in the following table

If you try 666 it will convert to 667 and 999 will be 000

In my opinion it is better to follow as below:

```C#
SqlParameter param = dbCommand.CreateParameter();
param.DbType = DbType.DateTime2;
DateTime theDate = DateTime.Parse("2023-08-07T23:58:47.222");
param.Value = theDate;
dbCommand.Parameters.Add(param);
```

Now if you check the type it is returned as DateTime2 and you also get a casting error saying:
```powershell
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.Data.SqlTypes.SqlDateTime'.
```

**Comment by JRahnama** [comment] 2023-08-13 04:14
closing the issue as by design.

**Closed by JRahnama** 2023-08-13 04:14 UTC
Labels: By Design, :link: External

**Comment by ClaytonAndTheClayTones** [comment] 2023-10-03 17:57
> ```cs
> SqlParameter param = dbCommand.CreateParameter();
> param.DbType = DbType.DateTime2;
> DateTime theDate = DateTime.Parse("2023-08-07T23:58:47.222");
> param.Value = theDate;
> dbCommand.Parameters.Add(param);
> param.ParameterName = "LockoutEndsAt";
> ```
Apologies in advance for any perceived slight, I speak strongly because I believe in MS and their product and think it should be the best it can be:

If ADO still does not default DateTimes to datetime2 I think that's a terrible flaw.  Datetime can't store ISO-compliant millisecond dates with accuracy; that's a shortfall that was solved with datetime2.  Not targeting a 20 year old data type by default that provides accurate date storage might be by design, but it's objectively _bad_ design.

I'd suggest phrasing this as a feature request instead of just closing it, because defaulting to an inaccurate time storage medium in 2023 is a really bad look when literally no other DB or framework has this issue.
