### ISSUE TITLE
HIGH Severity ! TrustServerCertificate flag if marked True, is not Working in SqlConnectionStringBuilder in Microsoft.Data.SqlClient Package

### ISSUE THREAD

**Issue by SathiyaGirinathan** [dotnet/SqlClient#2551] opened 2024-06-05 14:09 UTC
### Describe the bug
TrustServerCertificate flag if marked True, is not Working in SqlConnectionStringBuilder in Microsoft.Data.SqlClient Package but it is working in System.Data.SqlClient Package.

### To reproduce

```c#
![image](https://github.com/dotnet/SqlClient/assets/65302254/34596041-9c5f-4469-8661-234172bd46c7)

        string connectionString = "Server=.;Database=DummyDB;Trusted_Connection=True;TrustServerCertificate=True;";
        SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder(connectionString);

        Console.WriteLine(builder.ConnectionString);
       //OUTPUT: Server=.;Database=DummyDB;Trusted_Connection=True;Trust Server Certificate=True;
If you clearly look at TrustServerCertificate, that flag gets splitted. It is perfectly working in System.Data.SqlClient

I found this issue when I use this SqlConnectionStringBuilder and using that connection string in my code
![image](https://github.com/dotnet/SqlClient/assets/65302254/f70a923c-cc86-41a4-b2c4-bbc41e43a52d)

```

### Expected behavior
![image](https://github.com/dotnet/SqlClient/assets/65302254/349206a6-e6e1-4af1-b3d5-708b2ff319b5)

       //OUTPUT: Server=.;Database=DummyDB;Trusted_Connection=True;TrustServerCertificate=True;

**Comment by dauinsight** [comment] 2024-06-05 15:35
Hi @SathiyaGirinathan , this is by design. More details here: https://github.com/dotnet/SqlClient/issues/1407

**Comment by kf-gonzalez2** [comment] 2024-06-11 18:16
Closing, duplicate of #1407

**Closed by kf-gonzalez2** 2024-06-11 18:16 UTC
Labels: untriaged
