### ISSUE TITLE
Unicode handling differs between NVARCHAR(Max) and NVARCHAR(n)

### ISSUE THREAD

**Issue by hopfen-heiner** [dotnet/SqlClient#381] opened 2020-01-14 08:03 UTC
The following SQL produces different results when executed in SSMS:
`SELECT CONVERT(NVARCHAR(4000), 0x0BDC), CONVERT(NVARCHAR(MAX), 0x0BDC)`

Reading these values with a .NET program results in equally different strings:
`"�"` and `"\u0bdc"`.

I'd expect to get the very same results. There seems to be a decoding applied to the non-max value, though, as pointed out [here](https://stackoverflow.com/questions/59646548/different-unicode-results-between-nvarcharmax-and-nvarchar4000-in-ms-sql#comment105582175_59646548).

Tested with:
- .NET Framework 4.7.2
- SQL Server 2017 (14.0.1000.169) and SQL Server 2019 (15.0.2000.5)
- SQL Server Management Studio 14.0.17289.0 and 15.0.18131.0
- Windows 10 Enterprise 1903

**Comment by cheenamalhotra** [comment] 2020-01-15 19:05
Hi @hopfen-heiner 

I'm able to reproduce the problem and currently investigating the same.

**Comment by Wraith2** [comment] 2020-01-24 20:28
I think the answer is that the input you're providing isn't a valid UTF codepoint and the result of the two different paths in the library changes whether the incoming value is decoded or stuffed directly into a string object.

The fixed length path gets a byte[] with the contents from the packet in it and then uses `Encoding.Unicode.GetString()` to get a string out of that buffer and in doing so the contents are checked and found to be nonsensical so you get an invalid character replacement which usually shows as the diamond with a question in it.

The max length path works differently because it's a plp type so a char[] buffer is created and the chunks of data from the packets are written directly into the buffer, a string constructed from the buffer and then passed to the user. This path doesn't go through Unicode so the values aren't checked and the string constructor just accepts whatever you pass it assuming users will validate it.

So then there is the question of whether it's a bug and I'm not sure. It's not consistent certainly but should it be? In the presence of nonsensical input data should the output be constrained to be identicall? I'd err on the side of compatibility and say that if you're relying on weird behaviour for invalid input then it's more trouble than it's worth to "fix" that and let you carry on doing weird things as long as you're aware that what you're doing isn't a great idea and could change in future. I'm not a decision maker though so that's purely opinion.

**Comment by David-Engel** [comment] 2024-05-28 23:07
Closing this issue as no-fix.

**Closed by David-Engel** 2024-05-28 23:07 UTC
Labels: :no_entry_sign: Won't Fix
