### ISSUE TITLE
Could not load file or assembly 'Microsoft.Identity.Client' when Microsoft.Identity.Client > 4.14.0 is referenced

### ISSUE THREAD

**Issue by BLWood** [dotnet/SqlClient#763] opened 2020-10-20 15:41 UTC
### Describe the bug
When a version of Microsoft.Identity.Client greater than 4.14.0 is referenced the following exception occurs when opening a connection to a database with `Authentication=ActiveDirectoryInteractive`. This exception occurs when targeting .NET Framework but does not occur when targeting .NET Core.

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.14.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' or one of its dependencies. The located assembly's manifest defini
tion does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.GetFedAuthToken(SqlFedAuthInfo fedAuthInfo)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OnFedAuthInfo(SqlFedAuthInfo fedAuthInfo)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover, Boolean isFirstTranspar
entAttempt, Boolean disableTnir)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential,
TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean r
edirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, ServerCertificateValidationCallback serverCallback, ClientCertificateRetrievalCallback clientCallback, DbConnectionPool pool, String accessToken
, SqlClientOriginalNetworkAddressInfo originalNetworkAddressInfo, Boolean applyTransientFaultHandling)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& con
nection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at ConsoleApp1.Program.Main(String[] args) in C:\Development\ConsoleApp1\ConsoleApp1\Program.cs:line 16

```

### To reproduce
```c#
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Data.SqlClient" Version="2.0.1" />
      <PackageReference Include="Microsoft.Identity.Client" Version="4.21.1" />
    </ItemGroup>

</Project>

```

```c#
using System;
using Microsoft.Data.SqlClient;

namespace ConsoleApp1
{
    class Program
    {
        private const string ConnectionString = "Data Source=benwood.database.windows.net;Initial Catalog=master;User ID=ben.wood@red-gate.com;Authentication=ActiveDirectoryInteractive";

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            using (var connection = new SqlConnection(ConnectionString))
            {
                connection.Open();
            }
        }
    }
}
```

### Expected behavior
The connection to be successful on both .NET Framework - as it is on .NET Core.

**Comment by ErikEJ** [comment] 2020-10-20 15:44
What happens when you remove:

`<PackageReference Include="Microsoft.Identity.Client" Version="4.21.1" />`

**Comment by JRahnama** [comment] 2020-10-20 17:49
@BLWood, thanks for bringing this up to our attention. 
As [nuget.org](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.0-preview1.20235.1)  for Microsoft.Data.SqlClient mentions our driver has dependencies on 
```
Microsoft.Data.SqlClient.SNI (>= 2.1.0)
Microsoft.Identity.Client (>= 4.14.0)
Microsoft.IdentityModel.JsonWebTokens (>= 5.6.0)
Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 5.6.0)
```
when it comes to .NETFramework. I tested your app same as you did, overwriting the Micorosoft.Identity.Client version, and got same error message, however when I created a .NetFramework ConsoleApp with `Project ToolsVersion="15.0"`  everything worked fine.

.NETCoreApp 3.1 dependencies are as below,
```
Microsoft.Data.SqlClient.SNI.runtime (>= 2.1.0)
Microsoft.Identity.Client (>= 4.14.0)
Microsoft.IdentityModel.JsonWebTokens (>= 5.6.0)
Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 5.6.0)
Microsoft.Win32.Registry (>= 4.7.0)
System.Configuration.ConfigurationManager (>= 4.7.0)
System.Diagnostics.DiagnosticSource (>= 4.7.0)
System.Runtime.Caching (>= 4.7.0)
System.Security.Principal.Windows (>= 4.7.0)
System.Text.Encoding.CodePages (>= 4.7.0)

```
there might be some conflict between this packages in .NETFramework or some of them needs to be upgraded as well when you convert a .NETCoreApp to .NETFramework.

**Comment by cheenamalhotra** [comment] 2020-10-20 19:27
Hi @BLWood 

This is an existing issue in dotnet runtime, there are many related discussions you can find in [dotnet/sdk](https://github.com/dotnet/sdk) and [dotnet/runtime](https://github.com/dotnet/runtime) repos: e.g. https://github.com/dotnet/runtime/issues/27774

Root cause of this issue is missing support for auto binding redirects.
Adding below configuration to `App.config` file should resolve your issue, kindly confirm:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Identity.Client" publicKeyToken="0a613f4dd989e8ae" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.14.0.0" newVersion="4.21.1.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by BLWood** [comment] 2020-10-21 14:02
> Hi @BLWood
> 
> This is an existing issue in dotnet runtime, there are many related discussions you can find in [dotnet/sdk](https://github.com/dotnet/sdk) and [dotnet/runtime](https://github.com/dotnet/runtime) repos: e.g. [dotnet/runtime#27774](https://github.com/dotnet/runtime/issues/27774)
> 
> Root cause of this issue is missing support for auto binding redirects.
> Adding below configuration to `App.config` file should resolve your issue, kindly confirm:
> 
> ```
> <?xml version="1.0" encoding="utf-8" ?>
> <configuration>
>   <runtime>
>     <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
>       <dependentAssembly>
>         <assemblyIdentity name="Microsoft.Identity.Client" publicKeyToken="0a613f4dd989e8ae" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-4.14.0.0" newVersion="4.21.1.0"/>
>       </dependentAssembly>
>     </assemblyBinding>
>   </runtime>
> </configuration>
> ```

Thanks for the suggestion.

Unfortunately this is not possible in our actual project since we are an extension and do not control our endpoints.

**Comment by ErikEJ** [comment] 2020-10-21 15:19
@blwood you can add binding redirects programmatically.

**Comment by cheenamalhotra** [comment] 2020-10-26 19:21
Hi @BLWood 

As this is limitation from external component, I will close this issue.

**Closed by cheenamalhotra** 2020-10-26 19:21 UTC
Labels: :link: External

**Comment by smartstoremx** [comment] 2021-09-03 14:20
Dear All,

We are trying to get the access token to use to request my own api. I am using Microsoft. Identity.Client nuget. version: 4.36.0

a) In Net core MVC web application, unit test, console , Library projects works.
b) In Net framework 4.7.2 in unit test, console, library projects works.

c) In MVC web application with net framework 4.7.2 do not work. When you execute await app.AcquireTokenForClient(scopes) . It stay forever not response.

We did the following. you can replicate the problem.

Open visual studio 2019.

Create a new project using MVC web application net framework 4.7.2

Inside the home controller add the following code:

public async Task<string> TokenGetAsync()
 {
     IConfidentialClientApplication app;

     app = ConfidentialClientApplicationBuilder.Create(" your AD client ID ")  
            .WithClientSecret(" Secret ID ")  
            .WithAuthority(new Uri("https://login.microsoftonline.com/ {domain name} .onmicrosoft.com"))
            .Build();
     string[] scopes = new string[] { "https://{domain name}.onmicrosoft.com/xxxxxx/.default" };

     AuthenticationResult result = null;
     try
     {
         // **************Here stay for ever never return the token in MVC net framework 4.7.2******************
         result = await app.AcquireTokenForClient(scopes)
             .ExecuteAsync();    
     }
     catch (MsalServiceException ex) when (ex.Message.Contains("AADSTS70011"))
     {
            Console.WriteLine("Scope provided is not supported");
            return "";
     }
     return result.AccessToken;
 }


 public ActionResult Index()
 {
     ViewBag.Token = TokenGetAsync().GetAwaiter().GetResult(); 
     return View();
 }

**Comment by cheenamalhotra** [comment] 2021-09-03 17:50
```
     // **************Here stay for ever never return the token in MVC net framework 4.7.2******************
     result = await app.AcquireTokenForClient(scopes)
         .ExecuteAsync();    
```
Could you try using `ConfigureAwait(false)`?
