### ISSUE TITLE
A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)

### ISSUE THREAD

**Issue by rajagopal-p** [dotnet/SqlClient#898] opened 2021-02-03 07:11 UTC
We are getting the following error during our performance test run.
_A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)_
We are using Azure SQL database and using System.Data.SqlClient from System.Data (.NET 4.8)

Exception message:
SQL Server error(s): FatalError.
Error Details      : -1 - A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)
Severity   : 20
State      : 0
Server     : asr-perf-sql-tx3psh.database.windows.net
Procedure  : marker.WorkItem_Details_Get_General, line 0
Provider   : .Net SqlClient Data Provider

Stack Trace: 
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at Assessor3.Gateway.Framework.Data.DataAccessBase.ExecuteReader(SqlConnection conn, CommandType type, String cmdText, SqlParameter[] parameters)

System.Data.SqlClient
.NET target: Framework 4.8

**Comment by cheenamalhotra** [comment] 2021-02-03 08:55
Hi @rajagopal-p 

Please provide more info:
1. What is the mode of authentication in your case?
2. How much time does it take to capture this error, from the time application starts? Is it a constant?
3. Have you tried using Microsoft.Data.SqlClient and reproduced this scenario with it too? If not, could you try using it and confirm?
4. Can you confirm "Auto-Close" is turned OFF on Azure DB? Related issue: https://social.msdn.microsoft.com/Forums/en-US/209e6f88-8ac9-4bff-a898-323ac2f1f6e5/a-transport-level-level-error-has-occurred-when-receiving-results-from-the-server-error-19-

**Comment by rajagopal-p** [comment] 2021-02-03 10:29
Hi @cheenamalhotra 

Please find the answers given below:

Mode of authentication - SQL Authentication
Frequency - Randomly we are getting this error. Sometimes we have received this error within 30 minutes. This occurs even with a reduced load.
Library - We haven't tried Microsoft.Data.SqlClient since our application is very near to the production release date. Do you see any issues with System.Data.SqlClient
Auto-Close -  "Auto-close" option is turned OFF on Azure DB

Thanks,
Rajagopal

**Comment by cheenamalhotra** [comment] 2021-02-05 22:10
Hi @rajagopal-p 

Could you run some tests with Microsoft.Data.SqlClient to validate your environment or if you can reproduce errors with this driver too?

**Comment by rajagopal-p** [comment] 2021-02-09 06:22
Hi @cheenamalhotra

Based on the response we have received from MS Azure DB Team, This issue was related to a recent Azure DB infrastructure migration activity. 
They have upgraded some of their clusters to newer hardware across all the regions and our database was a part of that migration. This might be the reason for these issues and they have suggested to implement a retry mechanism for error code 40613 and now we are not receiving this type of errors.

Do you recommend to update SqlClient to Microsoft.Data.SqlClient to avoid similar issues in the future since the development focus for System.Data.SqlClient client has changed?  We are planning to upgrade that in our next release.

Thanks,
Rajagopal

**Comment by ErikEJ** [comment] 2021-02-09 14:19
@rajagopal-p You should always anticipate transient errors from Azure, and implement something like EF Core does here: https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Storage/Internal/SqlServerTransientExceptionDetector.cs

**Comment by cheenamalhotra** [comment] 2021-02-10 09:12
@rajagopal-p 

> Do you recommend to update SqlClient to Microsoft.Data.SqlClient to avoid similar issues in the future since the development focus for System.Data.SqlClient client has changed? We are planning to upgrade that in our next release.

Yes, always. System.Data.SqlClient may not receive these updates, so we always recommend moving sooner rather than later.
Also we're going to introduce new reliability APIs in next releases to be able to configure retry externally too, PR #693 shall bring more hands on capabilities to perform retry.

**Comment by cheenamalhotra** [comment] 2021-02-10 09:28
> This might be the reason for these issues and they have suggested to implement a retry mechanism for error code 40613 and now we are not receiving this type of errors.

Regarding this issue, our driver does retry on error code **40613** ([NetFx](https://github.com/dotnet/SqlClient/blob/0d4c9bb3d55e096a0f3196565b2c786a9125aaf8/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs#L616) | [NetCore](https://github.com/dotnet/SqlClient/blob/0d4c9bb3d55e096a0f3196565b2c786a9125aaf8/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs#L272)) so Microsoft.Data.SqlClient should not fail. This error code also applies to Serverless DBs getting resumed, which we support retrying on. Can you confirm with our latest released version if that works for you?

**Comment by ErikEJ** [comment] 2021-02-10 16:13
@cheenamalhotra but is your retry on connection? (And not on Command) ?

**Comment by cheenamalhotra** [comment] 2021-02-10 16:19
Yes on connection open. It's part of transient fault handling.
40613 shall occur only when server is not available as per [Azure docs](https://docs.microsoft.com/en-us/azure/azure-sql/database/troubleshoot-common-errors-issues#transient-fault-error-messages-40197-40613-and-others).

**Comment by ErikEJ** [comment] 2021-02-10 16:59
Thanks, but the stack trace refers to a read, in that case a custom retry strategy like the one in EF Core is required?

**Comment by cheenamalhotra** [comment] 2021-02-10 17:58
That error above is not 40613 so I'm curious to know too how this error 19 relates to 40613?
Is there an internal error captured above?

**Comment by rajagopal-p** [comment] 2021-02-11 06:55
We recently migrated our DB to Azure. This was the first Perf test run after the migration.
We have got several issues during this test run and unfortunately, some of them are related to a recent Microsoft's infrastructure migration activity (according to the Azure DB support team)

We already have a retry mechanism in our legacy code but it doesn't cover the Azure DB transient errors. I think That's why they suggested to include 40613 error code in our retry mechanism.

These are the existing error codes that we are using in our retry mechanism (which is already covering error code 19)

 ErrorCodes Greater than -3 (negative 3) and less than or equal to 20
• 701: Out of memory
• 1204: Lock Issue
• 1205:Dead Lock Victim
• 1222: Lock Request Timeout
• 8645: Timeout waiting for memory resource
• 8651: Low memory condition
• 1206: MS DTC Transaction Exception
• 10054: Transport-level occurred when sending the request to the server

As @ErikEJ suggested, we are planning to include all the transient error codes in our existing retry mechanism.

Apart from this error, We are getting the below error very frequently. 

**_The incoming tabular data stream (TDS) protocol stream is incorrect. The MARS TDS header contained errors._**
We tried to enable the app context switch to bring back the old behavior using the below code in Web.config 
**_<AppContextSwitchOverrides value="Switch.System.Data.SqlClient.MakeReadAsyncBlocking=true" />_**
but it didn't work. 

Any suggestions to solve this issue as well?

**Comment by rajagopal-p** [comment] 2021-02-11 15:52
UPDATE: We have moved this AppContext.Switch logic to <AppSettings> based on this post [https://github.com/microsoft/dotnet/issues/816](url) and testing is progressing on this change.

<add name="AppContext.SetSwitch:Switch.System.Data.SqlClient.MakeReadAsyncBlocking" value="true" />

**Comment by rajagopal-p** [comment] 2021-02-15 16:10
We couldn't reproduce the above issue after implementing the AppContext switch change mentioned here [https://github.com/microsoft/dotnet/issues/1263#issuecomment-718884828] in Web.config file [https://docs.microsoft.com/en-us/dotnet/api/system.appcontext?view=net-5.0#appcontext-for-library-consumers]

**Comment by cheenamalhotra** [comment] 2021-02-17 01:15
@rajagopal-p 

If you can reproduce error 19 (Physical connection is not usable) by disabling your retry logic, could you provide us a repro so we can investigate and fix it properly for future users?

**Comment by arminatwork** [comment] 2021-05-02 20:45
> Hi @cheenamalhotra,
> 
> We recently migrated our DB to Azure. This was the first Perf test run after the migration.
> We have got several issues during this test run and unfortunately, some of them are related to a recent Microsoft's infrastructure migration activity (according to the Azure DB support team)
> 
> We already have a retry mechanism in our legacy code but it doesn't cover the Azure DB transient errors. I think That's why they suggested to include 40613 error code in our retry mechanism.
> 
> These are the existing error codes that we are using in our retry mechanism (which is already covering error code 19)
> 
> ErrorCodes Greater than -3 (negative 3) and less than or equal to 20
> • 701: Out of memory
> • 1204: Lock Issue
> • 1205:Dead Lock Victim
> • 1222: Lock Request Timeout
> • 8645: Timeout waiting for memory resource
> • 8651: Low memory condition
> • 1206: MS DTC Transaction Exception
> • 10054: Transport-level occurred when sending the request to the server
> 
> As @ErikEJ suggested, we are planning to include all the transient error codes into our existing retry mechanism.
> 
> Apart from this error, We are getting the below error very frequently.
> 
> **_The incoming tabular data stream (TDS) protocol stream is incorrect. The MARS TDS header contained errors._**
> We tried to enable the app context switch to bring back the old behavior using **AppContextSwitchOverrides** in Web.config _Switch.System.Data.SqlClient.MakeReadAsyncBlocking=true_ but it didn't work.
> 
> Any suggestions to solve this issue as well?

Hi @rajagopal-p 
I have 701 error so its a Out of Memory
How can I solved this?

**Comment by eolamisanaffinity** [comment] 2022-04-13 22:00
We are getting the same error.

In the last week in our production environment we have logged 177 of them.
In our test environment we have logged 21 of them.

EF 6.4
.Net Framework 4.8
Azure Sql Server

If MARS is enabled.

```
System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. 
---> System.Data.SqlClient.SqlException: A transport-level error has occurred when receiving results from the server. 
(provider: Session Provider, error: 19 - Physical connection is not usable)
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.<ExecuteStoreCommandsAsync>d__26.MoveNext()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.<ExecuteStoreCommandsAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.<ExecuteAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__156`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.<ProtectedExecuteAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<GetResultsAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.<FirstMoveNextAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<ForEachAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

If MARS is disabled.

```
System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. 
See the inner exception for details. ---> System.InvalidOperationException: The connection does not support MultipleActiveResultSets.     
at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)     
at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()    
 at System.Threading.Tasks.Task.Execute()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.<ExecuteStoreCommandsAsync>d__26.MoveNext()     --- End of inner exception stack trace ---     
at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.<ExecuteStoreCommandsAsync>d__26.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.<ExecuteAsync>d__10`1.MoveNext()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()     
at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__156`1.MoveNext()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()     
at System.Data.Entity.Infrastructure.DbExecutionStrategy.<ProtectedExecuteAsync>d__21`1.MoveNext()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()     
at System.Data.Entity.Core.Objects.ObjectQuery`1.<GetResultsAsync>d__43.MoveNext()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()     
at System.Data.Entity.Internal.LazyAsyncEnumerator`1.<FirstMoveNextAsync>d__9.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<ForEachAsync>d__2`1.MoveNext()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<ToDictionaryAsync>d__16`3.MoveNext()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     

```

Note: the application is not actually using MARS.

One solution frequently mentioned seems to be a custom sql execution strategy and re-tries like so:

https://stackoverflow.com/a/30894154/556649

What is the suggested path to resolving this error?

**Comment by eolamisan** [comment] 2022-04-13 22:01
We are getting the same error.

In the last week in our production environment we have logged 177 of them.
In our test environment we have logged 21 of them.

EF 6.4
.Net Framework 4.8
Azure Sql Server

If MARS is enabled.

```
System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. 
---> System.Data.SqlClient.SqlException: A transport-level error has occurred when receiving results from the server. 
(provider: Session Provider, error: 19 - Physical connection is not usable)
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.<ExecuteStoreCommandsAsync>d__26.MoveNext()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.<ExecuteStoreCommandsAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.<ExecuteAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__156`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.<ProtectedExecuteAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<GetResultsAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.<FirstMoveNextAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<ForEachAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

If MARS is disabled.

```
System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. 
See the inner exception for details. ---> System.InvalidOperationException: The connection does not support MultipleActiveResultSets.     
at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)     
at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()    
 at System.Threading.Tasks.Task.Execute()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.<ExecuteStoreCommandsAsync>d__26.MoveNext()     --- End of inner exception stack trace ---     
at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.<ExecuteStoreCommandsAsync>d__26.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.<ExecuteAsync>d__10`1.MoveNext()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()     
at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__156`1.MoveNext()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()     
at System.Data.Entity.Infrastructure.DbExecutionStrategy.<ProtectedExecuteAsync>d__21`1.MoveNext()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()     
at System.Data.Entity.Core.Objects.ObjectQuery`1.<GetResultsAsync>d__43.MoveNext()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()     
at System.Data.Entity.Internal.LazyAsyncEnumerator`1.<FirstMoveNextAsync>d__9.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<ForEachAsync>d__2`1.MoveNext()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<ToDictionaryAsync>d__16`3.MoveNext()  
--- End of stack trace from previous location where exception was thrown ---     
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     

```

Note: the application is not actually using MARS.

One solution frequently mentioned seems to be a custom sql execution strategy and re-tries like so:

https://stackoverflow.com/a/30894154/556649

What is the suggested path to resolving this error?

**Comment by tomtom1992** [comment] 2022-05-05 06:44
I am receiving the same issue on SQL Server 2016 since end of April. What is the SQLError Code to use in the retry logic in the code? Error 19 it says in the exception, but this is not the internal error code correct?

**Comment by JRahnama** [comment] 2022-05-05 18:14
> We are getting the same error.

@eolamisan can you provide a minimal sample repro that could reproduce the issue?  That will narrow down the issue and will make the investigation possible.

**Comment by JRahnama** [comment] 2022-05-05 18:16
@tomtom1992 if there is no inner exception with a different number, 19 would be the error number.

**Comment by eolamisan** [comment] 2022-05-05 19:23
> > We are getting the same error.
> 
> @eolamisan can you provide a minimal sample repro that could reproduce the issue? That will narrow down the issue and will make the investigation possible.

Sorry, I don't have a minimal sample to reproduce the issue.

**Comment by eolamisan** [comment] 2022-06-21 11:12
Would you update documentation to include "error: 19 - Physical connection is not usable" please?
e.g.
https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-events-and-errors?view=sql-server-ver16

**Comment by Tealons** [comment] 2023-02-16 10:55
We are having this error regularly with out applications on Azure with Azure SQL Server, but we can't create a minimal sample to reproduce it. We could provide access to our logs to investigate the issue? @cheenamalhotra @JRahnama ?

**Comment by Roman-Konstantinov** [comment] 2023-08-29 07:38
Hello @Tealons,
Could you please share the result of the investigation.
Have you found the solution for the issue?
We have the same situation as @eolamisan described but with pyodbc client. It appears accidentally and currently we're not able to identify any patterns

**Comment by David-Engel** [comment] 2024-06-11 21:31
The error is likely due to intermittent network issues. Closing this issue as stale/external.

**Closed by David-Engel** 2024-06-11 21:31 UTC

**Comment by bilalmehrban** [comment] 2025-03-16 10:14
I am getting this exact same issue on my local database as well.
