### ISSUE TITLE
Reading binary data asynchronously hangs execution

### ISSUE THREAD

**Issue by mdzieg** [dotnet/SqlClient#2276] opened 2023-12-18 15:34 UTC
Repro code can be found here: https://github.com/mdzieg/LBOTest/tree/main

Initialize database using SQL from readme. Update connection string in the code if needed.
Code inserts data file and then tries to load it.

When reading entity with binary data it hangs when using async method:

```C#
var att = await c.AttachmentData.FindAsync(1);
```

but works okay when using sync method:

```C#
var att = c.AttachmentData.Find(1);
```

This issue has its roots most likely in SqlClient library, although it was claimed fixed: https://github.com/dotnet/SqlClient/issues/600

### Include provider and version information
EF Core version: 8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: WIN 11
IDE: N/A

**Comment by ErikEJ** [comment] 2023-12-18 16:08
@mdzieg Did you try 5.2 preview 4?

**Comment by mdzieg** [comment] 2023-12-19 09:49
@ErikEJ added <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0-preview4.23342.2" /> and tested, but no luck. It still hangs.

**Comment by ErikEJ** [comment] 2023-12-19 09:52
How do you load the 66 MB file?

**Comment by mdzieg** [comment] 2023-12-19 09:59
> How do you load the 66 MB file?

This POC uses my app database and I have data already in the table. I did not add data loading code to the POC, but can do so.

**Comment by ErikEJ** [comment] 2023-12-19 11:18
Thanks, duplicate of #593

**Comment by mdzieg** [comment] 2023-12-19 11:24
> Thanks, duplicate of #593

@ErikEJ It looks like a long issue originating in mid 2020. Is this something that is being fixed at the moment? You mentioned there "I have confirmed that the major improvement will be in 5.2 preview 4 and later" but using that lib version did not help in my case.

**Comment by ErikEJ** [comment] 2023-12-19 11:31
Your use case is very large binary objects, and the improvements are better for smaller binary objects. 

Read the issue to understand the challenges involved, I do not think this is a high priority at the moment.

IMHO saving 66 MB binary objects in a database is an anti pattern. Use a file system for that.

**Comment by mdzieg** [comment] 2023-12-19 11:40
> Your use case is very large binary objects, and the improvements are better for smaller binary objects.
> 
> Read the issue to understand the challenges involved, I do not think this is a high priority at the moment.
> 
> IMHO saving 66 MB binary objects in a database is an anti pattern. Use a file system for that.

Seems it will not be fixed any time soon then.

Saving large binary objects to the database in most cases is an anti-pattern, I agree.
 
I did not expect such a basic operation to hang our application. Now we are aware of the problem and will avoid async code with LBO.

**Comment by kf-gonzalez** [comment] 2023-12-19 19:30
Closing as it is a duplicate of #593

**Closed by kf-gonzalez** 2023-12-19 19:30 UTC
Labels: customer-reported, untriaged
