### ISSUE TITLE
Build conflict with SqlDbType

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/SqlClient#144] opened 2019-07-31 14:34 UTC
A thread was started on an old EF Core issue that evolved into something which may be an issue with M.D.SqlClient, or should probably at least be investigated.

See https://github.com/aspnet/EntityFrameworkCore/issues/7820

Snippet of build output:
```
1>Build FAILED.
1>
1>TVPBuilder.cs(48,29,48,38): error CS0433: The type 'SqlDbType' exists in both 'System.Data.Common, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>Program.cs(13,92,13,101): error CS0433: The type 'SqlDbType' exists in both 'System.Data.Common, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>    0 Warning(s)
1>    2 Error(s)
1>
1>Time Elapsed 00:00:00.38
```
@slubowsky reported the issue, and @ErikEJ (one of our top contributors) has been able to reproduce it. I'm sure they will be wiling to help as needed if you need more information.

/cc @David-Engel @vickyharp @divega

**Comment by Wraith2** [comment] 2019-08-01 11:25
Looking at the locations for that type at https://apisof.net/catalog/System.Data.SqlDbType the only time it was present in S.D.SqlClient is the netstandard1.6+platform extensions. It shouldn't be present in any M.D.SqlClient builds as far as i can see.  The answer might be to ensure that the project targets netstandard 2.0 or later and if it still preroduces the dependency resolution steps need to be checked.

**Comment by ErikEJ** [comment] 2019-08-01 13:27
@wraith2 have a look at my repro csproj! 

Looks like it is AppInsights package that pulls the dependency from a very old s.d.sqlclient

**Comment by Wraith2** [comment] 2019-08-01 14:37
It might be worth doing a build and then pulling the version of S.D.SqlClient that you find in the bin folder into a disassembler to see if it's a version that contains the type in question. If it is then in theory adding an explicit dependency to the latest version of S.D.SqlClient should force upgrade it. Dependency shenanigans can get messy though.

**Comment by ErikEJ** [comment] 2019-08-01 15:29
@Wraith2 How would I do a build ? - this issue prevents building

**Comment by ErikEJ** [comment] 2019-08-01 15:40
![image](https://user-images.githubusercontent.com/4169187/62307159-ffac4300-b47a-11e9-8b45-45774c68e821.png)

**Comment by ErikEJ** [comment] 2019-08-01 15:43
https://www.nuget.org/packages/System.Data.SqlClient/4.3.1 (.NET Standard 1.3!)

**Comment by Wraith2** [comment] 2019-08-01 16:13
> 
> 
> @Wraith2 How would I do a build ? - this issue prevents building

Oh yeah... oops.

Directly adding a reference to the latest (or later) S.D.SqlClient should cause the later version to be used instead of that transative one though. Without binding redirects i'm not sure what you'd have to do to resolve this i'm afraid.

**Comment by David-Engel** [comment] 2019-08-01 16:51
I think Wraith2's suggestion may work around it (add a newer reference yourself). But you probably need to file an issue in the Application Insights server repo and ask them to update the version they depend on since that old System.Data.SqlClient version is where the issue lies:
https://github.com/microsoft/ApplicationInsights-dotnet-server/issues

**Comment by ErikEJ** [comment] 2019-08-01 19:29
Confirmed that adding a newer reference fixes the issue:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="1.0.19189.1-Preview" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.8.0-beta1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.1" />
  </ItemGroup>

</Project>
```

**Comment by ErikEJ** [comment] 2019-08-01 19:35
Issue filed: https://github.com/microsoft/ApplicationInsights-dotnet-server/issues/1249

**Comment by cheenamalhotra** [comment] 2019-08-02 02:51
Closing issue here as issue identified with external library.

**Closed by cheenamalhotra** 2019-08-02 02:51 UTC
Labels: External
