### ISSUE TITLE
`SqlConfigurableRetryFactory.CreateExponentialRetryProvider` not waiting expected durations between retries when `MaxTimeInterval` is not specified

### ISSUE THREAD

**Issue by kendaleiv** [dotnet/SqlClient#1806] opened 2022-10-14 17:39 UTC
### Describe the bug

`SqlConfigurableRetryFactory.CreateExponentialRetryProvider` is not waiting the expected durations between retries with a server and database accessible via managed identity when `MaxTimeInterval` is not specified.

### To reproduce

```c#
using Azure.Core;
using Azure.Identity;
using Microsoft.Data.SqlClient;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace SqlClientRetryTest
{
    public class Program
    {
        public static async Task Main()
        {
            var retryProvider = SqlConfigurableRetryFactory.CreateExponentialRetryProvider(new SqlRetryLogicOption
            {
                DeltaTime = TimeSpan.FromSeconds(30),
                NumberOfTries = 5,
                TransientErrors = Enumerable.Range(0, int.MaxValue)
            });
            retryProvider.Retrying += (object s, SqlRetryingEventArgs args) =>
            {
                Console.WriteLine("[{0}] SQL: Retrying for {1} times - Error code: {2}, Delay: {3}", DateTime.Now, args.RetryCount, (args.Exceptions[0] as SqlException).Number, args.Delay);
            };

            var credential = new DefaultAzureCredential();
            var token = credential.GetToken(new TokenRequestContext(new[] { "https://database.windows.net/.default" }));

            var connectionString = "Server=tcp:SERVER_NAME_HERE.database.windows.net;Initial Catalog=DATABASE_NAME_HERE;";
            using var conn = new SqlConnection(connectionString);
            conn.AccessToken = token.Token;

            using var cmd = conn.CreateCommand();
            cmd.CommandText = "select bad request";

            conn.RetryLogicProvider = retryProvider;
            cmd.RetryLogicProvider = retryProvider;

            Console.WriteLine("[{0}] Before OpenAsync", DateTime.Now);
            await conn.OpenAsync();
            Console.WriteLine("[{0}] After OpenAsync", DateTime.Now);

            Console.WriteLine("[{0}] Before ExecuteNonQueryAsync", DateTime.Now);
            await cmd.ExecuteNonQueryAsync();
            Console.WriteLine("[{0}] After ExecuteNonQueryAsync", DateTime.Now);
        }
    }
}
```

Result:

```
[10/14/2022 1:32:14 PM] Before OpenAsync
[10/14/2022 1:32:15 PM] After OpenAsync
[10/14/2022 1:32:15 PM] Before ExecuteNonQueryAsync
[10/14/2022 1:32:15 PM] SQL: Retrying for 1 times - Error code: 207, Delay: 00:00:00
[10/14/2022 1:32:16 PM] SQL: Retrying for 2 times - Error code: 207, Delay: 00:00:00
[10/14/2022 1:32:16 PM] SQL: Retrying for 3 times - Error code: 207, Delay: 00:00:00
[10/14/2022 1:32:16 PM] SQL: Retrying for 4 times - Error code: 207, Delay: 00:00:00
```

### Expected behavior

Delays between retries.

### Further technical details
Microsoft.Data.SqlClient version: 5.0.1
.NET target: net6.0
SQL Server version: Azure SQL
Operating system: Windows 11

**Comment by kendaleiv** [comment] 2022-10-14 18:01
Delays happen if `MaxTimeInterval` is included though:

```csharp
var retryProvider = SqlConfigurableRetryFactory.CreateExponentialRetryProvider(new SqlRetryLogicOption
{
    DeltaTime = TimeSpan.FromSeconds(30),
    NumberOfTries = 5,
    MaxTimeInterval = TimeSpan.FromSeconds(90),
    TransientErrors = Enumerable.Range(0, int.MaxValue)
});
```

```
[10/14/2022 1:55:02 PM] Before OpenAsync
[10/14/2022 1:55:03 PM] After OpenAsync
[10/14/2022 1:55:03 PM] Before ExecuteNonQueryAsync
[10/14/2022 1:55:03 PM] SQL: Retrying for 1 times - Error code: 207, Delay: 00:00:35.7350000
[10/14/2022 1:55:39 PM] SQL: Retrying for 2 times - Error code: 207, Delay: 00:01:15.0090000
[10/14/2022 1:56:54 PM] SQL: Retrying for 3 times - Error code: 207, Delay: 00:01:28.4273101
[10/14/2022 1:58:23 PM] SQL: Retrying for 4 times - Error code: 207, Delay: 00:01:18.3404490
```

Is this expected behavior?

**Comment by DavoudEshtehari** [comment] 2022-10-17 18:35
@kendaleiv The `MaxTimeInterval` default value is zero by design, and this is expected that any delay over it will be ignored. 

See the [SqlRetryIntervalBaseEnumerator](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlretryintervalbaseenumerator.-ctor?view=sqlclient-dotnet-standard-5.0) document as the base class for all the internal retry enumerators.

**Comment by kendaleiv** [comment] 2022-10-17 18:47
Thanks for following up! Concerned folks may think `MaxTimeInterval` can exist as an optional upper bound maximum. If one says *retry 5 times with 30 second and exponential backoff* they might expect to have non-zero delays, since it seems like enough information has been provided? Or am I missing something here?

**Comment by DavoudEshtehari** [comment] 2022-10-17 19:54
Reading the API documentation is necessary prior use it, to avoid any possible mistakes. The calculated delay time is checked to be between `MinTimeInterval` and `MaxTimeInterval` (which is **zero** by default as I linked above). So, any time out of this boundary will be shrunk to the valid duration, which ends in zero in your case.

For more information see, [Configurable retry logic](https://learn.microsoft.com/en-us/sql/connect/ado-net/configurable-retry-logic?view=sql-server-ver16) and [SqlRetryLogicOption Class](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlretrylogicoption?view=sqlclient-dotnet-standard-5.0).

**Comment by lcheunglci** [comment] 2022-10-18 18:08
Closing issue because the behavior is by design

**Closed by lcheunglci** 2022-10-18 18:08 UTC
Labels: By Design
