### ISSUE TITLE
Microsoft.Data.SqlClient.SqlConnection throws exception when connecting to a local SQL database

### ISSUE THREAD

**Issue by jkiller295** [dotnet/SqlClient#1779] opened 2022-09-27 23:30 UTC
### Describe the bug
When creating a `SqlConnection` instance with `Microsoft.Data.SqlClient`, it throws an exception but `System.Data.SqlClient` works just fine.

Exception message:
```
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: HTTP Provider, error: 0 - )
```
Stack trace:
```
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlInternalConnection.cs:line 768
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\TdsParser.cs:line 1719
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, Boolean isFirstTransparentAttempt, SqlAuthenticationMethod authType, String certificate, ServerCertificateValidationCallback serverCallback, ClientCertificateRetrievalCallback clientCallback, Boolean useOriginalAddressInfo, Boolean disableTnir) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\TdsParser.cs:line 629
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover, Boolean isFirstTransparentAttempt, Boolean disableTnir) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlInternalConnectionTds.cs:line 2295
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlInternalConnectionTds.cs:line 1920
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlInternalConnectionTds.cs:line 1725
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, ServerCertificateValidationCallback serverCallback, ClientCertificateRetrievalCallback clientCallback, DbConnectionPool pool, String accessToken, SqlClientOriginalNetworkAddressInfo originalNetworkAddressInfo, Boolean applyTransientFaultHandling) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlInternalConnectionTds.cs:line 548
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnectionFactory.cs:line 143
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionFactory.cs:line 148
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionPool.cs:line 950
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionPool.cs:line 2014
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionPool.cs:line 1419
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionPool.cs:line 1303
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionFactory.cs:line 339
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionInternal.cs:line 770
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionClosed.cs:line 71
   at Microsoft.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 2107
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 2095
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 1652
   at Microsoft.Data.SqlClient.SqlConnection.Open() in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 1621
   at SqlClientTest.SqlClientTest.Main() in D:\source\repos\Test code\ConsoleApp1\Program.cs:line 30
```

### To reproduce

```c#
            try
            {
                using (System.Data.SqlClient.SqlConnection sqlCon = new System.Data.SqlClient.SqlConnection("Server = .\\SQLEXPRESS; Database = TestDb; Trusted_Connection = True;"))
                {
                    sqlCon.Open();
                    Console.WriteLine("System.Data.SqlClient.SqlConnection - OK");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"System.Data.SqlClient.SqlConnection: {ex.Message}");
            }
            try
            {
                using (Microsoft.Data.SqlClient.SqlConnection sqlCon = new Microsoft.Data.SqlClient.SqlConnection("Server = .\\SQLEXPRESS; Database = TestDb; Trusted_Connection = True;"))
                {
                    sqlCon.Open();
                    Console.WriteLine("Microsoft.Data.SqlClient.SqlConnection - OK");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Microsoft.Data.SqlClient.SqlConnection: {ex.Message}\r\nTrace: {ex.StackTrace}");
            }
```

### Expected behavior
It should output in the console if both cases behave the same
```
System.Data.SqlClient.SqlConnection - OK
Microsoft.Data.SqlClient.SqlConnection - OK
```

### Further technical details
Microsoft.Data.SqlClient version: 4.1.0
.NET target: Framework 4.7
SQL Server version: 15.0.4236
Operating system: Windows 10

**Additional context**
There is an issue with SMO that might relate to this problem [SMO 111](https://github.com/microsoft/sqlmanagementobjects/issues/111).

**Comment by ErikEJ** [comment] 2022-09-28 06:19
Add Encrypt=false to your connection string ?

**Comment by jkiller295** [comment] 2022-09-28 06:24
> Add Encrypt=false to your connection string ?

Yup, that works. But what if I need to have `Encrypt=true`?

**Comment by shueybubbles** [comment] 2022-09-28 12:17
My question is - if the error is "expected" why is it so vague? And why is it coming from the "HTTP Provider" ? How is HTTP involved? A better error message would go a long way to help people here.

**Comment by jkiller295** [comment] 2022-09-28 22:44
> My question is - if the error is "expected" why is it so vague? And why is it coming from the "HTTP Provider" ? How is HTTP involved? A better error message would go a long way to help people here.

Agreed. It could say something like 
`The server requires an encrypted connection. Try setting Encryption to true etc. etc.` pardon my English.

**Comment by JRahnama** [comment] 2022-09-29 16:23
@jkiller295 we will get back to this shortly.

**Comment by DavoudEshtehari** [comment] 2022-09-29 18:07
The desired exception issues from the server by **SSL Provider**, which I can see by running the repro against either SDS or MDS with `Encrypt=True`.
```
Microsoft.Data.SqlClient.SqlConnection: A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
```

@jkiller295 I could reproduce the reported `HTTP` message using the incompatible SNI library **v5.0.0** with **MDS v4.1**. Can you make sure you're using the correct version of `Microsoft.Data.SqlClient.SNI` by running a clean test and checking the `SNI` library's version in use?

**Comment by jkiller295** [comment] 2022-09-30 00:01
I tried again with **SNI v4.0.0** and **MDS v4.1** and got the same error message now.
> A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)

I didn't pay attention to the **SNI** version when I got the initial error message above.
If **MDS** or **SMO** latest version requires the **SNI** version to be **>= 5.0.0**, why does it not install that version by default?

**Comment by DavoudEshtehari** [comment] 2022-09-30 16:31
Package dependency is defined correctly in MDS for different versions and these kinds of issues are usual for a development environment. Cleaning and building the project is a good practice each time a project dependency is changed.

Closing the issue since it's not a driver issue.

**Closed by DavoudEshtehari** 2022-09-30 16:31 UTC

**Comment by flensrocker** [comment] 2022-10-21 09:40
I have the same error with a fresh console application and the repo code in the first post.

I try to connect to a SQL Server 2019 Developer Edition on Windows 11:
Microsoft SQL Server 2019 (RTM-GDR) (KB5014356) - 15.0.2095.3 (X64)   Apr 29 2022 18:00:13   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 22000: ) (Hypervisor) 

ConnectionString is: `Data Source=localhost\\INSTANCENAME;Initial Catalog=TestDb;Integrated Security=True`

If I add `Trust Server Certificate=True` it works. The version of SNI is 5.0.1.

This error is also in version 4.x, with version 3.x there's no exception.

**Comment by flensrocker** [comment] 2022-10-21 09:51
@jkiller295 Yes, I don't want to set this option, but I have to, otherwise I have to downgrade MDS to 3.1.1.
Since it's only needed on my local development machine, it's a workaround for now.

The app published to Azure works with MDS 5.0.1.

How can I make MDS trust my local SQL Server?

**Comment by flensrocker** [comment] 2022-10-21 10:02
Ok, thank you!

**Comment by DavoudEshtehari** [comment] 2022-10-21 16:59
Adding link to the [Q/A](https://github.com/dotnet/SqlClient/wiki/Frequently-Asked-Questions#12-i-have-upgraded-microsoftdatasqlclient-to-version-400-but-am-not-able-to-open-a-connection-which-was-working-in-a-previous-version) For more information.
