### ISSUE TITLE
Getting "System.PlatformNotSupportedException" in Blazor WebAssembly page.

### ISSUE THREAD

**Issue by mszixie** [dotnet/SqlClient#599] opened 2020-06-11 06:54 UTC
### Describe the bug
I tried to add and use the Microsoft.EntityFrameworkCore.SqlServer package in the Blazor WebAssembly page. However on loading the page component, it shows this exception and it is not able to run correctly.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
**Exception message:**
System.PlatformNotSupportedException: Microsoft.Data.SqlClient is not supported on this platform.

**Stack trace:**
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Microsoft.Data.SqlClient is not supported on this platform.
System.PlatformNotSupportedException: Microsoft.Data.SqlClient is not supported on this platform.
  at Microsoft.Data.SqlClient.SqlConnection..ctor (System.String connectionString) [0x00006] in H:\tsaagent1\_work\9\s\obj\Release.AnyCPU\Microsoft.Data.SqlClient\netcore\netstandard2.0\Microsoft.Data.SqlClient.notsupported.cs:295 
  at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection () <0x313e910 + 0x0000c> in <filename unknown>:0 
  at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection () <0x313e5c0 + 0x0003c> in <filename unknown>:0 
  at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateDbCommand (Microsoft.EntityFrameworkCore.Storage.RelationalCommandParameterObject parameterObject, System.Guid commandId, Microsoft.EntityFrameworkCore.Diagnostics.DbCommandMethod commandMethod) <0x3f20d30 + 0x000ec> in <filename unknown>:0 
  at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync (Microsoft.EntityFrameworkCore.Storage.RelationalCommandParameterObject parameterObject, System.Threading.CancellationToken cancellationToken) <0x3f1f6b8 + 0x000ba> in <filename unknown>:0 
  at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1+AsyncEnumerator[T].InitializeReaderAsync (Microsoft.EntityFrameworkCore.DbContext _, System.Boolean result, System.Threading.CancellationToken cancellationToken) <0x3e91ae8 + 0x0014a> in <filename unknown>:0 
  at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult] (TState state, System.Func`4[T1,T2,T3,TResult] operation, System.Func`4[T1,T2,T3,TResult] verifySucceeded, System.Threading.CancellationToken cancellationToken) <0x3e90d20 + 0x000f4> in <filename unknown>:0 
  at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1+AsyncEnumerator[T].MoveNextAsync () <0x3e8a178 + 0x0050c> in <filename unknown>:0 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x3f715f0 + 0x00034> in <filename unknown>:0 
  at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource] (System.Linq.IQueryable`1[T] source, System.Threading.CancellationToken cancellationToken) <0x3486608 + 0x0015a> in <filename unknown>:0 
  at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource] (System.Linq.IQueryable`1[T] source, System.Threading.CancellationToken cancellationToken) <0x3486608 + 0x0025a> in <filename unknown>:0 
  at BlazorDemo1.Pages.Movies.OnInitializedAsync () [0x00122] in D:\Programs\WASM\BlazorDemo1\BlazorDemo1\Pages\Movies.razor:84 
  at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x2f85ca0 + 0x0013a> in <filename unknown>:0 
```
### To reproduce
Please try my test sample project here: https://github.com/mszixie/BlazorDemo1
The Sqlclient test page is the "/movies" page. 
It's based on the default Blazor WebAssembly template.

### Expected behavior
The SqlClient should be able to initialize and connect to my Azure SQL DB and retrieve data.

### Further technical details
Microsoft.EntityFrameworkCore.SqlServer: 5.0.0-preview.5.20278.2 (or 3.1.5 doesn't work)
Microsoft.Data.SqlClient (dependency of Microsoft.EntityFrameworkCore.SqlServer) version: 2.0.0-preview3.20122.2. (or older version included in Microsoft.EntityFrameworkCore.SqlServer 3.1.5 doesn't work neither)
.NET target: .Net Standard 2.1 (It's default of Blazor WebAssembly)
Blazor WebAssembly: 3.2.0
SQL Server version: Azure SQL Database
VS: 16.6.2
Operating system: Windows 10 2004 64Bit

**Additional context**
I am inspired by the blog post here: https://blog.jeremylikness.com/blog/ef-core-and-cosmosdb-with-blazor-webassembly/
From this blog seems the EF Core Cosmos DB client supports Blazor WebAssembly now, so I wonder if SqlClient in EF Core also supports this new platform. However, in my test I am getting the above error.

**Comment by cheenamalhotra** [comment] 2020-06-12 20:48
@mszixie 

We are able to reproduce the issue, thanks for repro app. The reason being it's loading Microsoft.Data.SqlClient.dll from `lib\netstandard2.0\` folder from NuGet package as it fails to find applicable DLL from runtime folder.

We'll investigate and get back to you with workaround/solution soon.

**Comment by cheenamalhotra** [comment] 2020-06-23 23:01
Hi @mszixie @pterevinto

SqlClient is not supported on Blazor/WebAssembly as of now. Also there's no TFM available for `WebAssembly` in NuGet as of now: https://github.com/NuGet/Home/issues/8186
While that gets supported, our driver would have to be built/tested accordingly for specific RIDs.

The `lib\netstandard2.0` DLLs are correctly throwing "Platform Not Supported" exception as of now.

**Comment by cheenamalhotra** [comment] 2020-07-15 03:05
Closing this issue since it's not possible to support this in SqlClient due to NuGet limitations.

**Closed by cheenamalhotra** 2020-07-15 03:05 UTC

**Comment by slepmog** [comment] 2021-03-14 14:34
I'm confused!

So is SqlClient not supported in Blazor/WebAssembly because there are some restrictions on the NuGet side that may be resolved eventually, as [mentioned above](https://github.com/dotnet/SqlClient/issues/599#issuecomment-658518127), or is it because it's fundamentally impossible to run such arbitrary code in the context of a browser like [mentioned here](https://github.com/dotnet/aspnetcore/issues/16977#issuecomment-552543164), so it's not going to be supported ever?

**Comment by David-Engel** [comment] 2021-03-15 16:41
@slepmog 

> So is SqlClient not supported in Blazor/WebAssembly because there are some restrictions on the NuGet side that may be resolved eventually, as [mentioned above](https://github.com/dotnet/SqlClient/issues/599#issuecomment-658518127), or is it because it's fundamentally impossible to run such arbitrary code in the context of a browser like [mentioned here](https://github.com/dotnet/aspnetcore/issues/16977#issuecomment-552543164), so it's not going to be supported ever?

From reading the various threads, it sounds like the latter. From a sandboxed browser session, you can't open an arbitrary network connection. That means you can't use SqlClient to connect to a database. (Caveat: I'm not a Blazor/WebAssembly developer.)

Additional ref: https://github.com/dotnet/aspnetcore/wiki/Common-Problems-and-Solutions-in-Blazor#problem-blazor-wasm-restrictions
And: https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md#why-is-there-no-tfm-for-blazor

**Comment by cheenamalhotra** [comment] 2021-03-15 17:42
Right, the explanation on blog is correct.
I've updated my comment to avoid confusions.
