### ISSUE TITLE
Microsoft.data.sqlclient fails to connect to local server

### ISSUE THREAD

**Issue by Martin-Stein** [dotnet/SqlClient#118] opened 2019-06-03 14:46 UTC
Hi there,

Microsoft.data.sqlclient (1.0.19128.1-Preview) fails to connect to local server, connections to remote SQL-Servers are working. It also fails with System.data.sqlclient(latest version, and all version before :-( )
Find attached the related error message.

Kind regards,

Martin Stein

![2019-06-03 16_45_25-_WinDev1903Eval_ auf _DESKTOP-7QAG33J_ - Verbindung mit virtuellen Computern](https://user-images.githubusercontent.com/32069131/58810857-0f481080-861f-11e9-98e3-01316e84952f.png)

**Comment by David-Engel** [comment] 2019-06-03 18:48
> I have forgot something to mention.
> This error only happens to Apps released and installed thru the MS-Appstore!
> When run the App from my developer PC it works fine!

@Martin-Stein It sounds like you've left a lot of details out of this issue. What is the environment where you are installing the app? In that environment, are you able to connect to the local SQL Server using something other than the installed app? (Like sqlcmd, a separate test program, etc.) Is the local SQL Server something you are deploying with your app? Is it configured to accept TCP connections? I assume this is all on Windows 10 running on x86/x64 hardware...

**Comment by Martin-Stein** [comment] 2019-06-03 19:13
Hi,

 

It is a Windows UWP App, deployed  thru the Microsoft Store.

I have installed it on a fresh Windows 10 1809 VM, with MS SQL-Server 2017,

The Local SQL-Server is reachable by local programs like SQL-Management Studio.

The Server is not deployed with the App. It was installed separately, TCPIP  is enabled.

is all on Windows 10 running on x86/x64 hardware.

 

 

Let me know, if you need more infos.

 

Thanks,

 

Martin

 

 

Von: David Engel <notifications@github.com> 
Gesendet: Montag, 3. Juni 2019 20:49
An: dotnet/SqlClient <SqlClient@noreply.github.com>
Cc: Martin-Stein <mytrainer@freenet.de>; Mention <mention@noreply.github.com>
Betreff: Re: [dotnet/SqlClient] Microsoft.data.sqlclient fails to connect to local server (#118)

 

I have forgot something to mention.
This error only happens to Apps released and installed thru the MS-Appstore!
When run the App from my developer PC it works fine!

@Martin-Stein <https://github.com/Martin-Stein>  It sounds like you've left a lot of details out of this issue. What is the environment where you are installing the app? In that environment, are you able to connect to the local SQL Server using something other than the installed app? (Like sqlcmd, a separate test program, etc.) Is the local SQL Server something you are deploying with your app? Is it configured to accept TCP connections? I assume this is all on Windows 10 running on x86/x64 hardware...

**Comment by peterbae** [comment] 2019-07-16 21:17
Hi @Martin-Stein, that error message is pretty generic and it could be caused by multiple reasons. Have you tried some of the troubleshooting steps on [this](https://blogs.msdn.microsoft.com/sql_protocols/2008/04/30/steps-to-troubleshoot-sql-connectivity-issues/) MSDN blog? Also, we have a new Microsoft.Data.SqlClient driver release (1.0.19189.1-Preview), so please give that driver a try as well, and let us know if that solves your problem.

**Comment by Martin-Stein** [comment] 2019-07-16 22:56
Hi Peter,




Yes, I have tried all these things, from the blog. The new Mictosoft. Data. SQL-client do not solve the problem. I still cant connect to the local sql Server when the App is installed thru the app-store.






Kind regards,




Martin 




Outlook für Android herunterladen







On Tue, Jul 16, 2019 at 11:17 PM +0200, "Peter Bae" <notifications@github.com> wrote:












Hi @Martin-Stein, that error message is pretty generic and it could be caused by multiple reasons. Have you tried some of the troubleshooting steps on this MSDN blog? Also, we have a new Microsoft.Data.SqlClient driver release (1.0.19189.1-Preview), so please give that driver a try as well, and let us know if that solves your problem.

**Comment by Martin-Stein** [comment] 2019-08-26 07:07
Oh come on!
You have scheduled this for 1.1.0 , instead of 1.0.0.? 
Am I the only person how needs this feature? I have a ready product but can't release it, because it's almost useless when you cant' use the local SQL-Server!

Please push this a litte bit more.
Thanks,

Martin

**Comment by Martin-Stein** [comment] 2019-09-19 06:34
Hi There,

1.0.0.0 is out, and preview 1.1.0.0 has it's first version ready but not released.
Do you have a roadmap?

@David-Engel , I thought UWP-Apps are the future of Microsoft! Did I bet on the wrong horse?


Kind regards,

Martin

**Comment by David-Engel** [comment] 2019-09-19 21:59
@Martin-Stein UWP support is in our backlog. We just don't have a date for at this time.

**Comment by David-Engel** [comment] 2019-11-20 00:10
@Martin-Stein Do you have the full stack trace of the error you get? You are leaving out a lot of information when you do not include a full stack trace and any inner exceptions.

I learned something new about UWP today. Applications need to specify required permissions for the application in their application manifest, including network access. Could your problem be something basic?
https://docs.microsoft.com/en-us/windows/uwp/networking/networking-basics

**Comment by Martin-Stein** [comment] 2019-11-22 10:24
Hi David,

 

I know about the flag in the UWP settings and all necessary flags are set.

The thing NOT to access SQL-servers in the network, but the LOCAL SQL-Server cannot be accessed AND ONLY if I use the app when it is installed from the store!

I have implemented to show the complete stacktrace, as you have suggested, but the store has not accepted my new version with the latest Microsoft.Data.SQlClient (1.1.0)

You will find attached the Error Report.

 

To be honest I really loose my trust in Microsoft supporting UWP Apps! 

My Application is ready since may 2018!!!!! And  cannot be release, because of this error!

 

 

Kind regards,

Martin

 

 

Von: David Engel <notifications@github.com> 
Gesendet: Mittwoch, 20. November 2019 01:11
An: dotnet/SqlClient <SqlClient@noreply.github.com>
Cc: Martin-Stein <mytrainer@freenet.de>; Mention <mention@noreply.github.com>
Betreff: Re: [dotnet/SqlClient] Microsoft.data.sqlclient fails to connect to local server (#118)

 

@Martin-Stein <https://github.com/Martin-Stein>  Do you have the full stack trace of the error you get? You are leaving out a lot of information when you do not include a full stack trace and any inner exceptions.

I learned something new about UWP today. Applications need to specify required permissions for the application in their application manifest, including network access. Could your problem be something basic?
https://docs.microsoft.com/en-us/windows/uwp/networking/networking-basics

**Comment by Martin-Stein** [comment] 2019-11-22 17:51
Hi David,
I have use the last SYSTEM.data.SQLClient again to reproduce the error.
Find attach a screeshot of the stacktrace.
Thanks,

Martin
![2019-11-22 18_47_38-Window](https://user-images.githubusercontent.com/32069131/69448525-feb85d80-0d58-11ea-8e1b-2916cbf0fa5e.png)

**Comment by David-Engel** [comment] 2019-11-22 18:56
@Martin-Stein 

> The thing NOT to access SQL-servers in the network, but the LOCAL SQL-Server cannot be accessed AND ONLY if I use the app when it is installed from the store!

The error you are getting is the one everyone gets when there are network connectivity problems to the server. SqlClient is using the network and TCP to try to connect and it is failing. Without a working reproduction, we are just guessing at what the problem is.

> I know about the flag in the UWP settings and all necessary flags are set.

Are you sure? It really feels like your UWP app settings may be the issue. Here are some links that indicate to me that this is a common issue in UWP apps with possible solutions:

- https://stackoverflow.com/questions/34589522/cant-see-localhost-from-uwp-app
- https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/deploying-and-debugging-uwp-apps#debugging-options
- https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap4-loopbackaccessrules
- https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh770532(v=win.10)#network-isolation-and-loopback
- https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh780593(v=win.10)

**Comment by Martin-Stein** [comment] 2019-11-24 16:08
HI David,

 

we are getting closer!

 

When I use fiddler’s

Loopback Exemption utility and activate an exemption for my App it works.

 

But how can I enable this with the installation?

 

According to this document:

https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap4-loopbackaccessrules

 

I have added <Extensions>

        <uap4:Extension Category="windows.loopbackAccessRules">

          <uap4:LoopbackAccessRules>

            <uap4:Rule Direction = "in" PackageFamilyName = "<Package Name>"/>

            <uap4:Rule Direction = "out" PackageFamilyName = "<Package Name>"/>

          </uap4:LoopbackAccessRules>

        </uap4:Extension>

      </Extensions>   

 

This to my manifest file, but this has no effect.

 

Ony if I run “checknetisolation loopbackexempt -a -n<Package Name>”  from the console it works!

 

But this is not my idea how Store Apps should work.
My idea of Store-Apps is “install it and run it”, not to configure something manually.

 

 

Is there a more user friendly way???

 

 

Thanks in advance,

 

Martin

 

 

Von: David Engel <notifications@github.com> 
Gesendet: Freitag, 22. November 2019 19:56
An: dotnet/SqlClient <SqlClient@noreply.github.com>
Cc: Martin-Stein <mytrainer@freenet.de>; Mention <mention@noreply.github.com>
Betreff: Re: [dotnet/SqlClient] Microsoft.data.sqlclient fails to connect to local server (#118)

 

 <https://github.com/Martin-Stein> @Martin-Stein

The thing NOT to access SQL-servers in the network, but the LOCAL SQL-Server cannot be accessed AND ONLY if I use the app when it is installed from the store!

The error you are getting is the one everyone gets when there are network connectivity problems to the server. SqlClient is using the network and TCP to try to connect and it is failing. Without a working reproduction, we are just guessing at what the problem is.

I know about the flag in the UWP settings and all necessary flags are set.

Are you sure? It really feels like your UWP app settings may be the issue. Here are some links that indicate to me that this is a common issue in UWP apps with possible solutions:

*	 <https://stackoverflow.com/questions/34589522/cant-see-localhost-from-uwp-app> https://stackoverflow.com/questions/34589522/cant-see-localhost-from-uwp-app
*	 <https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/deploying-and-debugging-uwp-apps#debugging-options> https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/deploying-and-debugging-uwp-apps#debugging-options
*	 <https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap4-loopbackaccessrules> https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap4-loopbackaccessrules
*	 <https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh770532(v=win.10)#network-isolation-and-loopback> https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh770532(v=win.10)#network-isolation-and-loopback
*	 <https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh780593(v=win.10)> https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh780593(v=win.10)

**Comment by David-Engel** [comment] 2019-12-03 17:34
> Is there a more user friendly way???

@Martin-Stein You might want to ask about making loopback connections in a forum that has more UWP experts, like:
https://docs.microsoft.com/answers/topics/uwp.html
or
https://stackoverflow.com/questions/tagged/uwp

Regards,
David

**Comment by Martin-Stein** [comment] 2019-12-10 17:45
Hi David,

 

I was too optimistic!

After releasing the package and testing on a VM , it fails running with a local SQL-Server,

 

Even  with checknetisolation loopbackexempt command, no connection to the local server is possible.

This behavior is approved by a friend of mine, how downloaded the App and tested it, as well.

 

I think I have to give up my project!, at least using local SQL- Servers.

 

I have spent all over 1,5 years on this project, for nothing!

 

 

Kind regards,

 

Martin

 

 

 

 

Von: David Engel <notifications@github.com> 
Gesendet: Dienstag, 3. Dezember 2019 18:34
An: dotnet/SqlClient <SqlClient@noreply.github.com>
Cc: Martin-Stein <mytrainer@freenet.de>; Mention <mention@noreply.github.com>
Betreff: Re: [dotnet/SqlClient] Microsoft.data.sqlclient fails to connect to local server (#118)

 

	Is there a more user friendly way???

@Martin-Stein <https://github.com/Martin-Stein>  You might want to ask about making loopback connections in a forum that has more UWP experts, like:
https://docs.microsoft.com/answers/topics/uwp.html <https://docs.microsoft.com/answers/topics/uwp.html> 
or
https://stackoverflow.com/questions/tagged/uwp <https://stackoverflow.com/questions/tagged/uwp> 

Regards,
David

**Comment by Martin-Stein** [comment] 2020-01-27 10:51
Hi there,
When I read the release notes to Version 2.0. preview, there are still no word about my problem.
The problem is tagged as future. What future is meant???

Pleas don't let me alone with this! I have spent many time in this project and don't want to let it die!


Best regards,

Martin

**Comment by cheenamalhotra** [comment] 2020-01-27 17:53
Hi @Martin-Stein 

I'm sorry but this is Out of Scope for this team, you need to reach out to experts in UWP forum as also mentioned by David already: https://github.com/dotnet/SqlClient/issues/118#issuecomment-561274974.

We are SqlClient driver team here and only handle issues limited to driver problems, whereas the problem you're experiencing is a network access issue as you're struck with network isolation. Please reach out to UWP teams for support.

Politely closing issue as "External".

**Closed by cheenamalhotra** 2020-01-27 17:53 UTC
Labels: Enhancement, External
