### ISSUE TITLE
Very bad ADO.NET performance on Linux

### ISSUE THREAD

**Issue by quanmaiepi** [dotnet/SqlClient#1201] opened 2021-08-02 09:07 UTC
First time reporter - so please let me know if I am missing some important information.

We are investigating a very bad performance characteristics on Linux. It seems it has something to do with the SqlConnection handling.
- .NET 5
- Azure App Service
- Same code runs on Windows very well (same configurations, even with more traffic)
- Affected both databases our app connected to
- Database usage levels are both very low (<10%). We don't see any particularly slow query.
In a particular memory dump, we see about 950 threads stuck in this same stacktrace:

```
00007F5EC7F2A838 00007f65d61873f9 [HelperMethodFrame: 00007f5ec7f2a838] System.Threading.WaitHandle.WaitMultipleIgnoringSyncContext(IntPtr*, Int32, Boolean, Int32)
00007F5EC7F2A980 00007f65667dfa86 System.Threading.WaitHandle.WaitMultiple(System.ReadOnlySpan`1<System.Threading.WaitHandle>, Boolean, Int32)
00007F5EC7F2AA00 00007f6562ee7b96 Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(System.Data.Common.DbConnection, UInt32, Boolean, Boolean, Microsoft.Data.Common.DbConnectionOptions, Microsoft.Data.ProviderBase.DbConnectionInternal ByRef) [/_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionPool.cs @ 1172]
00007F5EC7F2AA80 00007f65667df0d7 Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(System.Data.Common.DbConnection, System.Threading.Tasks.TaskCompletionSource`1<Microsoft.Data.ProviderBase.DbConnectionInternal>, Microsoft.Data.Common.DbConnectionOptions, Microsoft.Data.ProviderBase.DbConnectionInternal ByRef) [/_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionPool.cs @ 1142]
00007F5EC7F2AAE0 00007f6562ee553b Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(System.Data.Common.DbConnection, System.Threading.Tasks.TaskCompletionSource`1<Microsoft.Data.ProviderBase.DbConnectionInternal>, Microsoft.Data.Common.DbConnectionOptions, Microsoft.Data.ProviderBase.DbConnectionInternal, Microsoft.Data.ProviderBase.DbConnectionInternal ByRef) [/_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionFactory.cs @ 121]
00007F5EC7F2AB70 00007f65667dea2b Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(System.Data.Common.DbConnection, Microsoft.Data.ProviderBase.DbConnectionFactory, System.Threading.Tasks.TaskCompletionSource`1<Microsoft.Data.ProviderBase.DbConnectionInternal>, Microsoft.Data.Common.DbConnectionOptions) [/_/src/Microsoft.Data.SqlClient/netcore/src/Common/src/Microsoft/Data/ProviderBase/DbConnectionInternal.cs @ 347]
00007F5EC7F2ABC0 00007f65667de80c Microsoft.Data.SqlClient.SqlConnection.TryOpen(System.Threading.Tasks.TaskCompletionSource`1<Microsoft.Data.ProviderBase.DbConnectionInternal>, Microsoft.Data.SqlClient.SqlConnectionOverrides) [/_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs @ 1721]
00007F5EC7F2AC00 00007f65667ddbe7 Microsoft.Data.SqlClient.SqlConnection.Open(Microsoft.Data.SqlClient.SqlConnectionOverrides) [/_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs @ 1211]
```

Any idea if this might already be known? What next step should we do to investigate?

**Comment by quanmaiepi** [comment] 2021-08-02 09:08
Recreated from https://github.com/microsoft/dotnet/issues/1318

**Comment by PashaPash** [comment] 2021-08-02 09:17
Make sure you are either closing or disposing SqlConnection objects (by wrapping them into `using` statement)

**Comment by Wraith2** [comment] 2021-08-02 09:36
Are you trying to open large numbers of connections simultaneously?

**Comment by Wraith2** [comment] 2021-08-02 09:44
Shot in the dark. Try increasing the size of your threadpool minimum to something like 100 and see if it helps.

**Comment by quanmaiepi** [comment] 2021-08-02 09:45
by threadpool you probably meant the sql connection pool? I tried with 200 and 300 and it did not help. the pool will be flooded eventually

**Comment by Wraith2** [comment] 2021-08-02 09:49
No, I mean ThreadPool. The native and managed implementations of the SNI layer have different ways of dealing with waits and the managed on relies on the threadpool for callbacks, if you saturate the threadpool workers things stop working. If that's the case here then upping the minimum available threads alleviates it by starting the threadpool much higher, default is 10 i'd suggest bumping it up to 100.

**Comment by quanmaiepi** [comment] 2021-08-02 09:51
Interesting. Will try and report back. Thanks

**Comment by quanmaiepi** [comment] 2021-08-02 10:58
I am still running the test but it looks VERY promising. Spent last month on this issue, just so you know how grateful I am. Huge thanks!

**Comment by Wraith2** [comment] 2021-08-02 12:05
It was just an idea based on previous debugging of similar issues. It doesn't fix the problem it just works around it by starting you above the current growth threshold, you can still encounter the problem with higher loads. We're aware of the underlying issue but I don't know of any way to fix it at the moment.

**Comment by roji** [comment] 2021-08-02 12:42
@Wraith2 is this tracked somewhere? Would be interested in learning the cause of this...

**Comment by quanmaiepi** [comment] 2021-08-02 12:44
Interestingly, both workerThreads and completionPortThreads are 8 on Windows and Linux (for P3v3 instance, for S1 it's 1). Not sure why it differs under load...I'm happy with the results by setting them to 100 on Linux but if someone can investigate/explain the root cause that'd be great

**Comment by Wraith2** [comment] 2021-08-02 13:13
@roji it's the issue investigated in https://github.com/dotnet/SqlClient/issues/422

**Comment by roji** [comment] 2021-08-02 13:28
Thanks @Wraith2 - would it be a fair approximate summary to say that SqlClient is synchronously blocking TP threads (via locking/sleeping/IO/whatever)? Is this a MARS-only phenomenon?

**Comment by PashaPash** [comment] 2021-08-02 13:30
@quanmaiepi SQL Connection pool flooding means you are not releasing connections back to the pool. Cloud you please provide a sample code on SQLConnection lifetime - some snippet on how and when the connection is opened/closed? 

Do you use SQLConnection per http request (that is generally a bad idea). Or you are opening a connection right before a query, and disposing it afterwards?

There could be a difference on window/linux due to different GC schemas - in your case, windows GC could be more aggressive, and that cause dangled connections to be closed faster.

**Comment by Wraith2** [comment] 2021-08-02 16:10
> Thanks @Wraith2 - would it be a fair approximate summary to say that SqlClient is synchronously blocking TP threads (via locking/sleeping/IO/whatever)? Is this a MARS-only phenomenon?

Any async high throughput scenario with managed sni will likely exhibit the same problem, there's at least one other open issue where not related to mars where opening large numbers of connections has the same problem. I don't quite know where the problem is but I now recognize it as worker thread starvation well enough to suggest trying the threadpool configuration, in this case it worked. 

I know the MS team are aware of this problem.

**Comment by roji** [comment] 2021-08-02 17:11
Thanks @Wraith2

**Comment by JRahnama** [comment] 2021-08-03 16:13
@quanmaiepi as @Wraith2 mentioned the issue #422 is open and it seems it is the root cause of the issue. Is it possible for you to make us a sample repro application? Also can you let us know what version of Microsoft.Data.SqlClient is being used in your application?

**Comment by cheenamalhotra** [comment] 2021-08-03 16:18
Hi @quanmaiepi 

The exact problem area is unclear as we going to put more time to do some trails/experiments, but we're aware this is a design problem that was never "caught" on Windows (since System.Data.SqlClient) due to high availability of threads but the same application on Unix when run in limited thread pool, leads to thread starvation. We have identified it to be related to MARS (Multiple Active Result Sets) enabled connections only, but let us know if you have a use case otherwise too with a repro.

**Comment by lunchin** [comment] 2021-08-03 16:19
@JRahnama the application is running on a performance test in azure and running lots of different apis to simulate load on the application so is hard to provide repro application.  I can confirm we are using MultipleActiveResultSets=true in the connection string.  We are using the latest version of SqlClient

**Comment by JRahnama** [comment] 2021-08-03 17:48
@lunchin as @Warit2 mentioned for now increasing the `ThreadPool` size or setting `MARS` to false, if possible,  will work as workarounds.

**Comment by quanmaiepi** [comment] 2021-08-09 08:53
We can't really set MARS to false. Increase Min thread count is obviously a workaround, and it has drawbacks...

**Comment by Wraith2** [comment] 2021-08-09 09:28
> Increase Min thread count is obviously a workaround, and it has drawbacks...

What drawbacks are you seeing? Clearly you can tune the min threadpool.

**Comment by quanmaiepi** [comment] 2021-08-09 09:32
If for some reasons, it hits the thread pool limit, the instance will fail and never recover.
For the traffic we are testing, I can handle it with ~10 Windows instances, there were some spikes due to GC, but then they recovered quickly. For Linux if an instance is bad, it is bad "forever" (until it's taken out of the pool and restarted).

Also as we are serving wide range of traffic on different sites, fixing the pool size is something we'd like a avoid (no size fits all).

Setting the min thread count definitely helped us (and we are grateful :) ), but we also see that is a workaround instead of actual fix :)

**Comment by cheenamalhotra** [comment] 2021-08-12 22:23
Closing issue as original issue #422 will track this effort.

**Closed by cheenamalhotra** 2021-08-12 22:23 UTC
