### ISSUE TITLE
Transition to Microsoft.Data.SqlClient - VS Dataset Designer Errors

### ISSUE THREAD

**Issue by jfred1978** [dotnet/SqlClient#1502] opened 2022-02-02 18:24 UTC
I have a VS VB.net project and I have converted all of my instances to System.Data.Sqlclient to Microsoft.Data.Sqlclient and the application is running fine (using .Net 4.6.1).  

The application uses SQL server database and datasets that are created at design time configured using stored procedures.  I recently updated the database schema and when I go to the dataset designer, right click on a table and try to configure (or simply preview data) I get an error that says.   Cannot obtain provider factory for data provider named 'Microsoft.Data.Sqlclient'.  

![image](https://user-images.githubusercontent.com/58558640/152213509-e0f369ae-8338-4cc7-9182-4f539fd3c9fc.png)

So, I did some digging and I tried adding the code below to my app.config file (from #239) but this didn't help.  

```
  <system.data>
    <DbProviderFactories>
      <add name="SqlClient Data Provider"
       invariant="Microsoft.Data.SqlClient"
       description=".Net Framework Data Provider for SqlServer"
       type="Microsoft.Data.SqlClient.SqlClientFactory, Microsoft.Data.SqlClient" />
    </DbProviderFactories>
  </system.data>
```

How can I resolve this, do I need to update to a newer version of .Net framework or do I just need to convert back to System.Data.Sqlclient?

Many thanks in advance for the help.

Jeff

**Comment by ErikEJ** [comment] 2022-02-02 18:33
Duplicate of #1297

**Comment by JRahnama** [comment] 2022-02-03 18:28
@jfred1978 as @ErikEJ mentioned the issue is out of Microsoft.Data.SqlClient and you can follow the progress at https://developercommunity.visualstudio.com/t/vs-designer-support-for-microsoftdatasqlclient/1543400.

Closing the issue as duplication of #1297

**Closed by JRahnama** 2022-02-03 18:28 UTC
