### ISSUE TITLE
Dependency packages version conflict in .NET 6

### ISSUE THREAD

**Issue by sjahongir** [dotnet/SqlClient#1487] opened 2022-01-26 16:16 UTC
I have a .NET 6 web application and I used 
`Microsoft.AspNetCore.Authentication.JwtBearer` Version=6.0.1
This package has a dependency to `Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 6.10.0)`
![image](https://user-images.githubusercontent.com/16816791/151199627-6d8650cb-a0ce-4e13-b749-c61a497f8bfe.png)

`Microsoft.Data.SqlClient -Version 4.0.1` has dependency to `Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 6.8.0)`
![image](https://user-images.githubusercontent.com/16816791/151199868-f136fe08-fbcf-479c-a36a-6f84825579d7.png)

So there is a conflict with the versions
I think need to update dependencies

**Comment by JRahnama** [comment] 2022-01-26 17:46
@sjahongir you can always overwrite the version in the csproj. Have you tried that?

**Comment by sjahongir** [comment] 2022-01-26 18:43
@JRahnama As you said I will try, thank you for the answer.

**Comment by JRahnama** [comment] 2022-02-02 17:25
@sjahongir any update on this issue? If your issue is solved please feel free to close it.

**Comment by Ryba1986** [comment] 2022-02-23 23:48
> @JRahnama As you said I will try, thank you for the answer.

https://github.com/dotnet-outdated/dotnet-outdated

Command: dotnet outdated -u -t

**Comment by JRahnama** [comment] 2022-09-02 18:11
@Ryba1986, I think the issue is addressed with the latest release of M.D.SqlClient v5.0. Closing the issue as fixed. Please feel free to open a new issue or comment here if you still see the problem.

**Closed by JRahnama** 2022-09-02 18:11 UTC
