### ISSUE TITLE
SqlConnection.State value is not updated when connection is broken

### ISSUE THREAD

**Issue by Charles-Gagnon** [dotnet/SqlClient#1874] opened 2022-12-21 01:03 UTC
### Describe the bug

Note, this may be happening in other scenarios as well. But this is a clear example of behavior I wasn't expected so figured we'd start from there. 

The root issue is that the State property doesn't match what I'd expect when the connection to the server is broken. 

### To reproduce

1. Create sample app that continuously executes a query against a server, e.g. 

```c#
using SqlConnection conn = new SqlConnection("SERVER INFO HERE");
conn.Open();
while(true)
{
    SqlCommand cmd = conn.CreateCommand();
    cmd.CommandText = "SELECT 1";
    try
    {
        var result = cmd.ExecuteNonQuery();
        Console.WriteLine("Executed successfully");
    } catch (Exception e)
    {
        Console.WriteLine($"State={conn.State} {e.Message}");
    }
    Thread.Sleep(1000);
}
```
2. Start the program, it should start printing out "Executed successfully"
3. Shut off the server

### Expected behavior

I expect an exception to be thrown (this happens) and the connection state to be Closed/Broken (this does not happen). 

Instead I get the failures but the connection State stays as open

![image](https://user-images.githubusercontent.com/28519865/208795553-8326818b-91c5-4e98-968a-a3ad2106d542.png)

### Further technical details
Microsoft.Data.SqlClient version: 5.1.0-preview2.22314.2
.NET target: .NET 6.0
SQL Server version: SQL 2022
Operating system: Docker container

**Comment by lcheunglci** [comment] 2023-01-10 19:48
This behavior is by design.  Connection State does not change outside of client server communication.  The only things that change State are the application closing the connection or some kind of failure of an active call between the client and the server. There are no performant opportunities for the driver to change the connection state outside of those events.

**Comment by Charles-Gagnon** [comment] 2023-01-10 19:51
Why is the above example not considered a "failure of an active call"? I try to execute a query and it fails with a connection error.

**Comment by Charles-Gagnon** [comment] 2023-01-10 19:54
The documentation for [State](https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.state?view=dotnet-plat-ext-7.0) specifically says : 

`Indicates the state of the SqlConnection during the most recent network operation performed on the connection.`

which in the above example is false - I tried to execute a network operation but it was broken and so failed.

**Comment by lcheunglci** [comment] 2023-01-11 17:50
Thanks for your response.  I'll do some investigation after our release.

**Comment by cheenamalhotra** [comment] 2023-01-20 20:34
I've talked to @Charles-Gagnon offline on this, and I had few points to add:

Error with Class 20 is not retriable, as in this case, so application must not retry (as per guidelines), for now I would recommend that to be handled.

For SqlClient, since the error class is 20 and this is infact a [login failure](https://github.com/dotnet/SqlClient/blob/20d4c199923c9b4ea2ffd44d9304fcb306c5efb5/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs#L1357), the driver should be able to update the connection state to 'Closed' and make it ready to be re-opened. The parser is also disconnected here so it doesn't change the fact that this connection will never be reusable in this state. It has to be re-opened by applications if this error occurs.

Doing (2) is presumably safe since closing an already closed connection doesn't lead to exception.

**Comment by JRahnama** [comment] 2023-04-03 19:34
Closing the issue. PR #1953 is merged with the fix for this issue.

**Closed by JRahnama** 2023-04-03 19:34 UTC
