### ISSUE TITLE
Collation is not supported for Traditional_Spanish_CI_AS

### ISSUE THREAD

**Issue by mobius127** [dotnet/SqlClient#1396] opened 2021-11-19 12:14 UTC
### Describe the bug
I´m trying to map an entire database with **Traditional_Spanish_CI_AS** collation with Entity Framework Core 6 with .net6.

When I try to execute the command for scaffold the database drops this error:

```
Exception message:
Stack trace:
```
![image](https://user-images.githubusercontent.com/16031601/142621013-2e45ec92-f7fb-42ea-a635-18f47a6d641e.png)

SQL Server 2019
.net 6
Visual Studio 2022
EF Core 6

**Comment by mobius127** [comment] 2021-11-19 12:30
Sorry but I Tried to solved with this packages
![image](https://user-images.githubusercontent.com/16031601/142622998-5ca3c062-f884-4199-8a14-8a2a60f008c1.png)
Still not working.

PD: I closed the issu previously because I thought was SqlClient version installed with EF Core

**Comment by JRahnama** [comment] 2021-11-19 18:55
@mobius127 have you tried testing with net 5 or netcoreapp 3.1?

**Comment by mobius127** [comment] 2021-11-22 08:21
@JRahnama hi!!!

I`m just tried with .net5 and EF core 5 versions and it works

![image](https://user-images.githubusercontent.com/16031601/142825794-3e708333-14bb-4a43-94a4-e7ae06fdc934.png)

Dependencies with EF Core 5 and SQLClient
![image](https://user-images.githubusercontent.com/16031601/142825885-6614ff44-0c35-4fc7-91a9-bec8a016abdd.png)

In EF core 6 the dependencies with SqlClient
![image](https://user-images.githubusercontent.com/16031601/142826967-7a0ee1c6-cebe-4b67-9cb2-1b0cf59a9d92.png)

**Comment by JRahnama** [comment] 2021-11-22 17:09
@mobius127 the version can be overwritten in your csproj. just add 
```C#
<ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="4.0.0" />
</ItemGroup>
```
to the `csproj` and the latest version will be used. My concern is `.net 6` has something to do with this. Using latest version of MDS and `net 5.0` will give us a clear answer.

Regards.

**Comment by mobius127** [comment] 2021-11-23 08:32
@JRahnama in .net6 i tried to overwrite with the latest version of MDS and failed with dotnet dbcontext scaffold:

![image](https://user-images.githubusercontent.com/16031601/142991394-53c88608-1f21-45b1-a279-f4372dfd7570.png)

![image](https://user-images.githubusercontent.com/16031601/142991668-3749a9d2-a09d-4a5b-8c4b-53419ba099ca.png)

This is the example:
`dotnet ef dbcontext scaffold "Data Source=[SQLServer];Initial Catalog=[Database];Integrated Security=True;TrustServerCertificate=True;MultipleActiveResultSets=true;Enlist=true" Microsoft.EntityFrameworkCore.SqlServer --context ContextName --context-dir "Context" --output-dir "Entities" --force
`

Regards

**Comment by roji** [comment] 2021-11-24 09:27
@mobius127 what exact exception are you seeing when trying to use Microsoft.EntityFrameworkCore.SqlServer 6.0.0 with Microsoft.Data.SqlClient 4.0.0? I've just done a quick test application and it works fine for me - can you post a sample app which fails etc?

**Comment by mobius127** [comment] 2021-11-24 11:20
Hi @roji have you tried with sql server configured with this collation "Traditional_Spanish_CI_AS"?

This is the error that drops 
`Build started...
Build succeeded.
To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
Microsoft.Data.SqlClient.SqlException (0x80131904): The Collation specified by SQL Server is not supported.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.DrainData(TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.ThrowUnsupportedCollationEncountered(TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadStringWithEncoding(Int32 length, Encoding encoding, Boolean isPlp, String& value)
   at Microsoft.Data.SqlClient.TdsParser.TryReadSqlStringValue(SqlBuffer value, Byte type, Int32 length, Encoding encoding, Boolean isPlp, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.TryReadSqlValue(SqlBuffer value, SqlMetaDataPriv md, Int32 length, TdsParserStateObject stateObj, SqlCommandColumnEncryptionSetting columnEncryptionOverride, String columnName, SqlCommand command)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadColumnInternal(Int32 i, Boolean readHeaderOnly, Boolean forStreaming)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn, Boolean forStreaming)
   at Microsoft.Data.SqlClient.SqlDataReader.ReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn)
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerDatabaseModelFactory.GetTables(DbConnection connection, DatabaseModel databaseModel, Func`3 tableFilter, IReadOnlyDictionary`2 typeAliases, String databaseCollation)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:78327ee0-1282-4c41-990c-330519ff22a9
The Collation specified by SQL Server is not supported.`

Packages installed:
`<ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="4.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>`

I can share the project but i'ts a web api project with those packages nothing more and dunno if it's make sense to share.

The point is, automatic scaffold fails whatever the version of MDS are installed with EF core 6. In the other hand with .net5 and ef core 5 it works

My enviroment has:

Visual Studio 2022
SQL Server 2019
.NET SDK 6.0.100
EF Core command-line tools 6.0.0


ConnectionString = "Data Source=[SQLServer];Initial Catalog=[Database];Integrated Security=True;TrustServerCertificate=True;MultipleActiveResultSets=true;Enlist=true"

I hope this helps

Thanks for your time

**Comment by roji** [comment] 2021-11-24 13:11
> Hi @roji have you tried with sql server configured with this collation "Traditional_Spanish_CI_AS"?

Yes, I have - with SQL Server 2019, on both Windows and Linux, I can't get the error to reproduce with EF Core 6.0.0 and Microsoft.Data.SqlClient 4.0.0, when trying to scaffold a database created as follows:

```sql
CREATE DATABASE test COLLATE Traditional_Spanish_CI_AS;
```

The scaffolded EF Core model contains the following in its OnModelCreating:

```c#
modelBuilder.UseCollation("Traditional_Spanish_CI_AS");
```

Is it possible you have a specially-tweaked SQL Server? Could you try on brand new installation just to make sure?

**Comment by mobius127** [comment] 2021-11-24 14:32
@roji mmm my SQL Server it's the developers edition

Here's some captures 
![image](https://user-images.githubusercontent.com/16031601/143257261-d86983c5-a715-400a-9edd-5873bebcbaa9.png)
![image](https://user-images.githubusercontent.com/16031601/143257456-b0b36294-5b51-403c-92b9-28f5cd19d150.png)

**Comment by roji** [comment] 2021-11-24 16:21
@JRahnama have you been able to repro this?

**Comment by mobius127** [comment] 2021-11-24 16:26
@roji for more info my PC is configured with this language options:

![image](https://user-images.githubusercontent.com/16031601/143276367-4b18d12c-e40a-4bd6-9605-eb4334df0c7f.png)

And if you install SQL Server, the installer selects "Traditional_Spanish_CI_AS" by default.

Today I try a brand new installation and I've selected this collation "SQL_Latin1_General_CP1_CI_AS" and it works the command dbcontext scaffold.

**Comment by Kaur-Parminder** [comment] 2021-11-24 16:44
@roji and @mobius127 We have been able to Repro this.

I created the DB SQL server 2019 with Traditional_Spanish_CI_AS and try to scaffold it using EFCore 6 

Command:
 Scaffold-DbContext "Server=xxxxx;Database=xxxx;Trusted_Connection=True;Encrypt=False" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

I get this error

Microsoft.Data.SqlClient.SqlException (0x80131904): The Collation specified by SQL Server is not supported.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.DrainData(TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.ThrowUnsupportedCollationEncountered(TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadStringWithEncoding(Int32 length, Encoding encoding, Boolean isPlp, String& value)
   at Microsoft.Data.SqlClient.TdsParser.TryReadSqlStringValue(SqlBuffer value, Byte type, Int32 length, Encoding encoding, Boolean isPlp, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.TryReadSqlValue(SqlBuffer value, SqlMetaDataPriv md, Int32 length, TdsParserStateObject stateObj, SqlCommandColumnEncryptionSetting columnEncryptionOverride, String columnName, SqlCommand command)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadColumnInternal(Int32 i, Boolean readHeaderOnly, Boolean forStreaming)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn, Boolean forStreaming)
   at Microsoft.Data.SqlClient.SqlDataReader.ReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn)
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerDatabaseModelFactory.GetTables(DbConnection connection, DatabaseModel databaseModel, Func`3 tableFilter, IReadOnlyDictionary`2 typeAliases, String databaseCollation)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:5367b05a-02e6-48e0-b50e-91797d8a9260
The Collation specified by SQL Server is not supported.



The other way we could see it with Driver was:

SqlConnection conn = new SqlConnection("Data Source = xxxx; Initial Catalog = xxxx; Integrated Security = true; Encrypt = false;");
conn.Open();


SqlCommand command = new SqlCommand("Select top 1 'id1' from Table1", conn);
using (SqlDataReader reader = command.ExecuteReader())
{
    if (reader.Read())
    {
        Console.WriteLine(String.Format("{0}", reader[0]));
    }
}

conn.Close();

Root cause:

This is working correctly with .Net5. Driver is internally using System.Globalization.CultureInfo and
Updating to .Net 6, Driver is throwing exception due to the bug https://github.com/dotnet/runtime/issues/61977

**Comment by roji** [comment] 2021-11-24 17:54
OK, maybe the **server** collation needs to be set (I set the database one in my test). In any case, I'm not sure what could be related to EF Core here...

**Comment by ajcvickers** [comment] 2021-11-24 18:10
@roji Could it be that DbContext scaffolding is reverse engineering a collation that then doesn't work when connecting to the database? (This would explain why is started happening in 6.0.)

**Comment by roji** [comment] 2021-11-24 22:40
It's possible, though the exception stack trace above seems to indicate that the exception happens during reverse engineering, rather than afterwards... It looks like EF Core is being asked to reverse engineer, but then SqlClient is throwing that error while reading reverse engineering results from the database. It might specifically be a column name on some table that uses the unsupported collation, triggering the exception when we try to read that column name in GetTables.

Re 6 vs. 5, it seems like this is a .NET 6 vs. 5 issue (dotnet/runtime#61977) rather than an EF Core 6 vs. EF Core 5; @mobius127 can you confirm this? Can you scaffold when running EF Core 5 on .NET 6.0?

**Comment by mobius127** [comment] 2021-11-25 15:31
@roji sorry for the delay, I just created a Web Api project under .net6.0 with EF core 5.0 and it works the reverse engineering.

here's some screenshots
![image](https://user-images.githubusercontent.com/16031601/143466422-30b5fdde-a1f4-4e37-8a2f-62082a2cdc9f.png)

But yesterday, I've reinstalled sql server with "SQL_Latin1_General_CP1_CI_AS" collation.

But today, I create a database with "Traditional_Spanish_CI_AS" collation (the server is configured with SQL_Latin1_General_CP1_CI_AS)

Here's the result
![image](https://user-images.githubusercontent.com/16031601/143468278-d43b276d-9d8f-42d4-8d0d-0984b1a16e0a.png)
![image](https://user-images.githubusercontent.com/16031601/143468368-89837c77-5508-4471-ab1a-57994036e1f4.png)

As you can see, reverse engineering fails because of collation and maybe it's because for the runtime.

**Comment by Kaur-Parminder** [comment] 2021-11-25 16:18
@mobius127 [This](https://github.com/dotnet/runtime/issues/61977#issuecomment-978125240) list of collation wont work with .Net6  others should be fine.

**Comment by ErikEJ** [comment] 2021-11-25 16:52
Will it be fixed in a 6.0 patch?

**Comment by Kaur-Parminder** [comment] 2021-11-30 00:48
@ErikEJ will hear from [.Net team](https://github.com/dotnet/runtime/issues/61977#issuecomment-980281332) and update the issue accordingly.

**Comment by Kaur-Parminder** [comment] 2021-11-30 23:18
Closing this issue as the [PR](https://github.com/dotnet/runtime/pull/62155) for .Net6 fix has been created for next .Net6.x [milestone](https://github.com/dotnet/runtime/milestone/87) .

**Closed by Kaur-Parminder** 2021-11-30 23:18 UTC
Labels: :link: External, Repro Available
