### ISSUE TITLE
SqlClient  unable to resolve named instance port

### ISSUE THREAD

**Issue by steveoh** [dotnet/SqlClient#905] opened 2021-02-10 17:02 UTC
### Describe the bug

I am trying to connect to a database on a named instance `yada yada/instance`. The `yada yada` db cluster has the production database while the named instance has the development database both with the same name same users but different passwords. When I use the `yada yada/instance` connection string the client fails on credentials because it is not using the named instance port but instead is trying to connect the production database on 1433. If I remove the named instance and use `yada yada,port` i can access the development database.  

Applications like SMS or DBeaver do not have the same behavior when using the named instance connection string. This happens with dotnet code on osx and windows server.

### Expected behavior

I expect the named instance connection string to resolve to it's configured port and not the default 1433.

### Further technical details

Microsoft.Data.SqlClient version: 2.1.1
.NET target: 5.0.2
SQL Server version: SQL Server 2019
Operating system: Windows 2016, macOS 10.15

**Comment by ErikEJ** [comment] 2021-02-10 17:06
Duplicate of #868 ?

**Comment by steveoh** [comment] 2021-02-10 17:17
My apologies, it appears to be. 

I see it was moved to a v3 release. What is the expected timeframe for that? I don't enjoy using the specific port in my connection strings.

**Comment by ErikEJ** [comment] 2021-02-10 18:10
@steveoh the fix will also be in next 2.1 release, planned for beginning of March.

**Closed** 2021-02-10 19:16 UTC

**Comment by steveoh** [comment] 2021-03-26 02:22
Was this fixed in 2.1.2 or maybe in the 3.0 previews?

**Comment by cheenamalhotra** [comment] 2021-03-26 03:12
Yes this was fixed and released in both v2.1.2 and v3.0.0-preview1.
