### ISSUE TITLE
SqlServer Operations too slow in Ubuntu 

### ISSUE THREAD

**Issue by TejasPatadiya10** [dotnet/SqlClient#2280] opened 2023-12-19 12:41 UTC
Currently we have one scenario where certain queries getting executed in windows in in 5 seconds and same queries are taking time of more than 2 minutes in Ubuntu linux.

We are using latest version of Microsoft.Data.SqlClient and we have also check that certain posts regarding the same in this repo and it shows that it is fixed but still we are facing this.

Please guide to avoid this slowness in Ubuntu.

**Comment by ErikEJ** [comment] 2023-12-19 13:02
Please provide a full repro demonstrating the issue.

**Comment by TejasPatadiya10** [comment] 2023-12-21 04:45
We have figured it out, It was due to MARS set to true if we make it false it is working fine.

We can not eliminate MARS so please suggest the best possible way to run it fast in Ubuntu.

**Comment by Wraith2** [comment] 2023-12-28 18:13
Why is it impossible to remove usage of MARS? Generally I consider any code written to require mars to be bad code.

**Comment by kf-gonzalez** [comment] 2024-01-02 19:25
We would still need some repro information in order to investigate the issue

**Comment by kf-gonzalez** [comment] 2024-01-02 19:27
This issue may be a duplicate of #422

**Comment by cheenamalhotra** [comment] 2024-07-08 18:52
Closing as duplicate of #422

**Closed by cheenamalhotra** 2024-07-08 18:52 UTC
Labels: :information_source: Needs more Info, :hourglass_flowing_sand: Waiting for Customer
