### ISSUE TITLE
Error using  SqlDataAdapter.Update and sourceColumn with null values

### ISSUE THREAD

**Issue by hakano14** [dotnet/SqlClient#67] opened 2019-04-08 07:16 UTC
There is an error when using DataAdapter.Update with some datatypes and DBNull values.

Here is an example trying to insert 2 rows in a temp table.

```c#
private static void MiniTest()
        {
            using (var conn = new SqlConnection("Server=localhost;Database=DB;Uid=user;Pwd=password;"))
            {


                const string cTableName = "#tmpTest";

                // Create tmp table
                var sCreateTable = "IF NOT EXISTS(";
                sCreateTable += $"SELECT * FROM sysobjects WHERE name= '{ cTableName }' and xtype = 'U')";
                sCreateTable += $"CREATE TABLE { cTableName }( BinValue binary(16)  null)";

                conn.Open();
                var cmd = new SqlCommand(sCreateTable, conn);
                cmd.ExecuteNonQuery();

                var dt = new DataTable("SourceDataTable");
                dt.Columns.Add("SourceBinValue", typeof(byte[]));

                dt.Rows.Add(Guid.NewGuid().ToByteArray());
                dt.Rows.Add(DBNull.Value);

                var cmdInsert = new SqlCommand();
                cmdInsert.UpdatedRowSource = UpdateRowSource.None;
                cmdInsert.Connection = conn;

                cmdInsert.CommandText = $"INSERT { cTableName } (BinValue) ";
                cmdInsert.CommandText += "Values(@BinValue)";
                cmdInsert.Parameters.Add("@BinValue", SqlDbType.Binary, 16, "SourceBinValue");

                var da = new SqlDataAdapter();

                da.InsertCommand = cmdInsert;

                da.UpdateBatchSize = 2;
                da.AcceptChangesDuringUpdate = false;

                da.Update(dt);

            }
        }
```

This will result in exception:

> Implicit conversion from data type nvarchar to binary is not allowed. Use the CONVERT function to run this query.

The SQL Trace is like this:

exec sp_executesql N'INSERT #tmpTest (BinValue) Values(@BinValue)',N'@BinValue varbinary(16)',@BinValue=0x34B33D0C58B1D6469A6404FFA67F473C
exec sp_executesql N'INSERT #tmpTest (BinValue) Values(@BinValue)',N'@BinValue **nvarchar**(16)',@BinValue=NULL

As you can see the length is correct but the datatype is nvarchar and not expected Binary.	

We have been testing with the lastest preview of SQLClient 4.7.0-preview3.19128.7.

**Comment by divega** [comment] 2019-05-16 00:58
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by Fasopus** [comment] 2019-05-23 15:15
I'm currently testing the migration of an app from .Net Framework and System.Data.SqlClient and I believe I've also run into this issue. The exception I'm getting is different, but it seems like it could be the same root cause: 

```System.InvalidOperationException: 'String[0]: the Size property has an invalid size of 0.'```

In my scenario I have a data table which contains an integer column that is only used for output. When the data table contains more than 1 entry the above exception is thrown when I invoke `SqlDataAdapter.Update` , if there is only a single entry in the table everything works as expected. 

I've uploaded a repository [here](https://github.com/Fasopus/SqlBatchDataTable) that contains a database project and small console app that reproduces the issue I'm seeing.

**Comment by Gary-Zh** [comment] 2019-07-18 23:40
Hi,
This issue is now fixed in the latest preview release.
Closing this issue.

**Closed by Gary-Zh** 2019-07-18 23:40 UTC
