### ISSUE TITLE
SqlClient fails to convert decimal(38,20) to .Net decimal for values within the range of .Net's decimal type

### ISSUE THREAD

**Issue by dbrownems** [dotnet/SqlClient#95] opened 2019-05-10 18:06 UTC
This program

```
        static void Main(string[] args)
        {
            using (var con = new SqlConnection("server=.;database=tempdb;Integrated Security=true"))
            {
                con.Open();
                var cmd = new SqlCommand("select cast(4210862852.86 as decimal(38,20))  val", con);
                using (SqlDataReader rdr = cmd.ExecuteReader())
                {
                    rdr.Read();

                    var val = rdr.GetDecimal(0);
                    Console.WriteLine(val);
                }
            }
        }
```

fails with 

System.OverflowException: 'Conversion overflows.'

at [SqlBuffer.cs](https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlBuffer.cs) line 254:

```
                if (StorageType.Decimal == _type)
                {
                    if (_value._numericInfo.data4 != 0 || _value._numericInfo.scale > 28)
                    {
                        throw new OverflowException(SQLResource.ConversionOverflowMessage);
                    }
```
This value is well within the range of a .NET decimal, and it's a value that the SqlClient can _write_ using a SqlParameter.  So it should be converted to .NET decimal. 

The byte pattern in SQL and TDS for this value is:

`0x261400010000D877FB4DEE8B51699A5005000000`

And it looks like SqlBuffer refuses to convert any value with a non-zero value in the last 4 bytes.  But a .NET Decimal is stored as a 12-byte integer, along with a sign and a scaling factor.

So the apparent intent is to determine if the SqlDecimal uses a larger-than-12 byte integer and trigger the overflow.

So this conversion has a bug.  It looks like the SqlClient is confused on the byte ordering SQL Server is using, and the last 4 bytes of this buffer are not the 4 least-significant bytes of the 16-byte integer embedded in the decimal.  

This number requires uses 12 (base-10) decimal digits to store, so it requires fewer than 12 (base-256) bytes to store.

https://docs.microsoft.com/en-us/dotnet/api/system.decimal?redirectedfrom=MSDN&view=netframework-4.8

**Comment by divega** [comment] 2019-05-16 01:19
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by David-Engel** [comment] 2019-05-17 18:29
This same exception occurs in .NET Framework and Core. It seems like a fairly basic bug but I'm guessing there is a good reason it hasn't been discovered yet. Priority wise, I'm going to consider this an edge case for now unless there is more information that is occurs in a more general use case.

**Comment by NathanJonker** [comment] 2020-05-31 19:47
> This same exception occurs in .NET Framework and Core. It seems like a fairly basic bug but I'm guessing there is a good reason it hasn't been discovered yet. Priority wise, I'm going to consider this an edge case for now unless there is more information that is occurs in a more general use case.

@David-Engel, I have the same issue, I am trying to retrieve value: 1234567891234.56789 stored in SQL as: 1234567891234.56789000000000000, because of a column data type decimal(35,17), as you can see it does not exceed the limit of the .Net decimal type if you ignore the 0's. Can you recommend an interim solution while this is set as low priority?

**Comment by dbrownems** [comment] 2020-06-01 15:19
As a workaround, use an intermediate conversion to string.  Either on SQL Server with a CAST or on the client like this:

`var val = Decimal.Parse(rdr.GetSqlDecimal(0).ToString());`

**Comment by NathanJonker** [comment] 2020-06-01 19:32
> As a workaround, use an intermediate conversion to string. Either on SQL Server with a CAST or on the client like this:
> 
> `var val = Decimal.Parse(rdr.GetSqlDecimal(0).ToString());`

Thank you for the reply @dbrownems, much appreciated. Note that I am using Entity Framework Core 2.1, any suggestion would be great?

**Comment by NathanJonker** [comment] 2020-06-02 10:08
Would it be possible to remove or exclude the trailing zeros when the _value._numericInfo.scale exceed 28 in the below extract, in that way you keep your precision there is no rounding issue, and throwing the conversion overflow is more valid?

if (StorageType.Decimal == _type)
                {
                    if (_value._numericInfo.data4 != 0 || _value._numericInfo.scale > 28)
                    {
                        throw new OverflowException(SQLResource.ConversionOverflowMessage);
                    }

**Comment by branko-d** [comment] 2020-08-19 19:40
I'm hitting the same issue. We have a test which writes a random `decimal` value to the database, and then ensures that the same value can be retrieved from the database intact. Which is failing intermittently because of this.

**Comment by scidec** [comment] 2021-04-13 19:52
Same problem here. A simple entity project generated from a sql server database cannot write decimals from c# back to the database, even when they are both of same type decimal.

**Comment by klemmchr** [comment] 2021-07-06 09:25
Any updates on this? This issue is present since 3 years.

**Comment by DavoudEshtehari** [comment] 2021-07-09 21:42
It is on the to-do list this semester.

**Closed** 2021-09-16 17:36 UTC

**Comment by pabnemlig** [comment] 2025-05-22 12:55
This error still persist, I have a decimal (38,20) column which is configured in EF like this where Cubage is a decimal property:
            entity.Property(e => e.Cubage)
                .HasColumnType("decimal(38, 20)");

If I set the property in EF to 1584000000, it fails and 1584000000 is far off the max value of decimal (38,20).

**Comment by dbrownems** [comment] 2025-05-22 15:43
Yep.  Not sure this is exactly the same issue, but here's a repro on Microsoft.Data.SqlClient 6.0.2 and 6.1.0-preview1.25120.4:

```
using var con = new SqlConnection("Server=.;Database=tempdb;Trusted_Connection=True;TrustServerCertificate=true");
con.Open();
using var cmd = con.CreateCommand();
cmd.CommandText = "select @d d";
var p = new SqlParameter("@d", System.Data.SqlDbType.Decimal);
p.Precision = 38;
p.Scale = 20;
p.Value = 1584000000;
cmd.Parameters.Add(p);
try
{
    var s = cmd.ExecuteScalar();
}
catch (Exception ex)
{
    Console.WriteLine(ex.ToString());
}
```




```
System.OverflowException: Conversion overflows.
   at System.Data.SqlTypes.SqlDecimal.ToDecimal()
   at Microsoft.Data.SqlClient.TdsParser.AdjustDecimalScale(Decimal value, Int32 newScale)
   at Microsoft.Data.SqlClient.TdsParser.TDSExecuteRPCAddParameter(TdsParserStateObject stateObj, SqlParameter param, MetaType mt, Byte options, SqlCommand command, Boolean isAnonymous)
   at Microsoft.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Program.<Main>$(String[] args) in C:\Users\david\source\repos\EfTest\EfTest\Program.cs:line 15
```

**Comment by pabnemlig** [comment] 2025-05-22 17:51
After a bunch of research I have found that SqlClient uses Decimal.GetBits and SqlDecimal.ConvertToPrecScale during the conversion in my case. Your case is probably similar. The problem here seems to be that the .NET decimal is perceived by SqlDecimal to support numbers that can be represented by 96 bits. As such, while SqlDecimal.ConvertToPrecScale would succeed, SqlClients desire to request the decimal value again after parsing it with ConvertToPrecScale leads to the Conversion overflow exception. Why? Because internally, a check is made on the fourth integer of the return value of Decimal.GetBits and if its higher than 0, the exception will be thrown. It will essentially be thrown once the number in SqlDecimal is represented by more than three integers.

A simple way to reproduce the issue
var valueB = SqlDecimal.Parse("1584000000.00000000000000000000");
        var testV = SqlDecimal.ConvertToPrecScale(valueB, 38, 20).Value;

To fix this, I have changed all decimal(38,20) to match the precision you can achieve with 96 bit, in other words decimal(29,20)
