### ISSUE TITLE
After SqlException application state is corrupted

### ISSUE THREAD

**Issue by epignosisx** [dotnet/SqlClient#97] opened 2018-10-26 15:57 UTC
Environment: 
OS - Windows Server 2012 R2
.NET Core: 2.0.5
SQL Server 2016

Exception:
```
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 0 - The wait operation timed out.) ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at bool System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, uint waitForMultipleObjectsTimeout, bool allowCreate, bool onlyOneCheckConnection, DbConnectionOptions userOptions, out DbConnectionInternal connection)
   at bool System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource<DbConnectionInternal> retry, DbConnectionOptions userOptions, out DbConnectionInternal connection)
   at bool System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource<DbConnectionInternal> retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, out DbConnectionInternal connection)
   at bool System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource<DbConnectionInternal> retry, DbConnectionOptions userOptions)
   at bool System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource<DbConnectionInternal> retry)
   at Task System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
   at async Task<byte[]> Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.GetCacheItemAsync(string key, bool includeValue, CancellationToken token)
   at async Task Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.RefreshCacheItemAsync(string key, CancellationToken token)
   at async Task Microsoft.Extensions.Caching.SqlServer.SqlServerCache.RefreshAsync(string key, CancellationToken token)
   at async Task Microsoft.AspNetCore.Session.DistributedSession.CommitAsync(CancellationToken cancellationToken)
   at async Task Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
ClientConnectionId:f8356379-665e-484b-9093-e8e99ae10a72
Error Number:258,State:0,Class:20
```

This issue has come up in production in two separate occasions this week and once the ASP.NET Core app enters into this state only restarting the app resolves the problem. A few points I want to share:

1- It seems like something in the Connection Pool is getting corrupted once this happens. Since a restart fixes it.

2- The error seems related to some SSL issue based on the exception details (`Provider SSL`). However, our connection strings do not specify the `Encrypt` attribute.

3- There are a few issues reported with the same exception here, but in Linux/Mac environments. In this case this is an all Windows environment.

**Comment by divega** [comment] 2019-05-16 01:19
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by jzabroski** [comment] 2022-07-19 15:00
> @Code-DJ : You know connection pools are per-process right? The trick is to replace you code to open a connection with that loop.
> -- @jhudsoncedaron 

Incorrect.  Connection pools are per connection string.  e.g., changing the Application Name in the pool will cause a second pool to be created.

> Connections that come out of the connection pool are bad and have a trashed transaction isolation. I raised an issue on this almost ten years ago and eventually found out it's considered intended behavior.
> -- @jhudsoncedaron 

What you're describing isn't a client bug, but a bug in `sp_reset_connection` (which the client calls when it fetches a connection from the pool - and the client doesn't need to be the SQL Driver, since [in Java-land, the JDBC driver for SQL Server does not call sp_reset_connection, but instead delegates that to the client caller](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-connection-pooling?view=sql-server-ver16), which makes sense, as calling sp_reset_connection many times can increase `LOCK_HASH` spinlock count to the point of creating resource contention issues on a busy SQL Server.).  The transaction isolation level issue with `sp_reset_connection` was fixed/changed in SQL Server 2014.

The workaround you're describing could be made better by checking the @@VERSION value, caching it and checking it to see if you're on a version that doesn't require this chicanery.

> https://github.com/dotnet/SqlClient/issues/97#issuecomment-434793762
> -- @saurabh500 

@saurabh500 , are you saying that connections that wait too long to go through the queue can in turn re-trigger issue #1, resulting in a possible meta-stable failure state when connections consistently take 5 seconds to handshake?

**Comment by jhudsoncedaron** [comment] 2022-07-19 15:06
"The transaction isolation level issue with sp_reset_connection was fixed/changed in SQL Server 2014."

It wasn't. I reproduced it on SQL 2014 back when I used to run that.

**Comment by jzabroski** [comment] 2022-07-19 15:26
> "The transaction isolation level issue with sp_reset_connection was fixed/changed in SQL Server 2014."
> 
> It wasn't. I reproduced it on SQL 2014 back when I used to run that.

It appears you are right. #96 and #1098 (duplicate) independently verify this on SQL Server 2017 or later.

**Closed** 2024-07-08 18:55 UTC
Labels: :bug: Bug!
