### ISSUE TITLE
Is SqlClient supported on Xamarin/Xamarin.Android?

### ISSUE THREAD

**Issue by JasonLiu007** [dotnet/SqlClient#831] opened 2020-12-01 06:29 UTC
![image](https://user-images.githubusercontent.com/53427423/100705224-d2123980-33e1-11eb-8dbd-65763b129c74.png)

**Comment by JRahnama** [comment] 2020-12-01 17:47
@JasonLiu007 can you provide more information please? for example, is the question about Microsoft.Data.SqlClient or System.Data,SqlClient. The error message is showing you are using System.Data.SqlClient version 4.6. Can you confirm that?   Also, please make sure you have added the NuGet System.Data.SqlClient to your project using your `Nuget Package Manager` and confirm that you are using Xamarin.Android  (>= 7.1)

**Comment by JasonLiu007** [comment] 2020-12-02 05:27
@JRahnama Thanks lot for your patience reply.First I use the System.Data,SqlClient,but if my project inclde SqlDependency class the error is occer.

Then I find the Microsoft.Data.SqlClient on the website.Than I try to use it.But it has other error blew:
![1](https://user-images.githubusercontent.com/53427423/100831764-5f689300-34a1-11eb-8e21-ec1dbf109271.png)
![2](https://user-images.githubusercontent.com/53427423/100831767-61325680-34a1-11eb-9b2b-e4196f0bcea0.png)
![3](https://user-images.githubusercontent.com/53427423/100831769-61caed00-34a1-11eb-8dcb-96f484828c77.png)
![4](https://user-images.githubusercontent.com/53427423/100831771-6394b080-34a1-11eb-8895-060e8b9e41d1.png)
![5](https://user-images.githubusercontent.com/53427423/100831774-655e7400-34a1-11eb-8eeb-c9ebd4dc55f4.png)
![error](https://user-images.githubusercontent.com/53427423/100831777-65f70a80-34a1-11eb-9f36-743025dc9aa0.png)
![error1](https://user-images.githubusercontent.com/53427423/100831779-67283780-34a1-11eb-834f-612c376048a3.png)
![werpanuget1](https://user-images.githubusercontent.com/53427423/100831783-67c0ce00-34a1-11eb-9752-fd1e9e866b90.png)
![werpnuget1](https://user-images.githubusercontent.com/53427423/100831786-68596480-34a1-11eb-8944-afa9b965c7d0.png)
![werpnuget2](https://user-images.githubusercontent.com/53427423/100831787-698a9180-34a1-11eb-9fae-28541b84398e.png)

**Comment by JasonLiu007** [comment] 2020-12-07 06:20
@JRahnama Please help me to have a look how can I slove this problem.

**Comment by JRahnama** [comment] 2020-12-07 07:49
@JasonLiu007 I will update here tomorrow.

**Comment by JasonLiu007** [comment] 2020-12-07 08:00
@JRahnama Roger that.Thanks lot.

**Comment by JRahnama** [comment] 2020-12-07 21:43
@JasonLiu007 the problem is coming from [PCL](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/pcl?tabs=windows) and some security concerns. Basically, you cannot directly consume your SQL server/database info on a mobile application. What you need to do is creating a web service. Please read more [here](https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/web-service/?tabs=vswin).

In other words, some internal application should read your data, make sure firewall setting is setup accordingly to provide required permissions, and get your data from the web service using EFCore  `WebAPI`. 

**Avoid using EFCore directly inside your Xamarin application.**

If you insist using the connectivity and data layer inside your mobile application try using [SQLite](https://sqlite.org/index.html).

I will close the issue as it is not in scope of our driver. Feel  free to reopen the issue if you have anything connected to the driver itself.

**Closed by JRahnama** 2020-12-07 21:43 UTC

**Comment by JasonLiu007** [comment] 2020-12-09 02:57
@JRahnama Thaks for your support.
