### ISSUE TITLE
Cannot unload a collectible AssemblyLoadContext if System.Data.SqlClient is used

### ISSUE THREAD

**Issue by stasgaonkar** [dotnet/SqlClient#414] opened 2019-11-25 07:05 UTC
The Assembly we want to load (and unload) needs the ability to connect to a database for which we use Dapper. Dapper internally makes use of System.Data.SqlClient. We find that when we create such an assembly, then we are unable to Unload the **collectible AssemblyLoadContext**.

The sample source code is available at: https://github.com/stasgaonkar/DynamicLoading

Having followed the steps mentioned in https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability#, the following is the output of `gcroot` command,

```
0:000> !dumpheap -type LoaderAllocator
         Address               MT     Size
000002022c46e1f0 00007fff74999410       48     
000002022c46e260 00007fff74999538       24     

Statistics:
              MT    Count    TotalSize Class Name
00007fff74999538        1           24 System.Reflection.LoaderAllocatorScout
00007fff74999410        1           48 System.Reflection.LoaderAllocator
Total 2 objects
0:000> !gcroot -all 0x000002022c46e1f0
HandleTable:
    000002022A9D12A0 (strong handle)
    -> 000002022C4E8C48 System.Data.SqlClient.TdsParserStateObjectNative
    -> 000002022C46E1F0 System.Reflection.LoaderAllocator

    000002022A9D12A8 (strong handle)
    -> 000002022C4E00F0 System.Data.SqlClient.TdsParserStateObjectNative
    -> 000002022C46E1F0 System.Reflection.LoaderAllocator

    000002022A9D12E0 (strong handle)
    -> 000002022C4B38C0 System.Data.SqlClient.TdsParserStateObjectNative
    -> 000002022C46E1F0 System.Reflection.LoaderAllocator

    000002022A9D15F8 (pinned handle)
    -> 000002023C461038 System.Object[]
    -> 000002022C475768 System.Threading.TimerQueue[]
    -> 000002022C475840 System.Threading.TimerQueue
    -> 000002022C4ABE88 System.Threading.TimerQueueTimer
    -> 000002022C475708 System.Threading.TimerQueueTimer
    -> 000002022C475580 System.Threading.TimerCallback
    -> 000002022C474D60 System.Data.SqlClient.SqlConnectionFactory
    -> 000002022C46E1F0 System.Reflection.LoaderAllocator

Found 4 roots.
```

So it seems that the TdsParserStateObjectNative is the culprit. What we have also noticed is that there are some **"unmanaged/native DLL"** that are used (`sni.dll`) internally by `System.Data.SqlClient`, possibly from within `TdsParserStateObjectNative`. Not sure if this is causing any issues. 

Is something that we are attempting to do, incorrect?

**Comment by grant77** [comment] 2020-07-30 18:20
This worked for me:

```
var sqlClientAssembly = alc.Assemblies.SingleOrDefault(x => x.GetName().Name == "Microsoft.Data.SqlClient");
var sqlConnectionFactoryType = sqlClientAssembly?.GetType("Microsoft.Data.SqlClient.SqlConnectionFactory");
if (sqlConnectionFactoryType != null)
{
    var singletonInstance = sqlConnectionFactoryType.InvokeMember("SingletonInstance", BindingFlags.Public | BindingFlags.Static | BindingFlags.GetField, null, null, null) !;
    var baseType = sqlConnectionFactoryType.BaseType!;
    baseType.InvokeMember("ClearAllPools", BindingFlags.InvokeMethod, null, singletonInstance, null);
    var pruningTimer = (Timer)baseType.InvokeMember("_pruningTimer", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.GetField, null, singletonInstance, null) !;
    pruningTimer.Dispose();
}

```

**Comment by cheenamalhotra** [comment] 2020-07-31 21:16
@stasgaonkar 

Could you try solution posted by @grant77 if you're still facing this issue?

**Comment by Benjiinator** [comment] 2021-02-12 09:25
I am running into this same issue in .Net 5.0 using Microsoft.Data.SqlClient v2.1.1, the solution @grant77 provided does not appear to solve the issue for me.

**Comment by cheenamalhotra** [comment] 2021-02-12 16:46
Could you provide us a repro app to investigate?

**Comment by Benjiinator** [comment] 2021-02-13 16:46
@cheenamalhotra i have created a repro app here: [Assembly Unloading with Microsoft.Data.SqlClient](https://github.com/Benjiinator/assembly-unloading-sqlclient)

**Comment by Wraith2** [comment] 2021-02-15 01:10
Draft PR to get that basebones example working is at https://github.com/dotnet/SqlClient/pull/913 

@Benjiinator can you try the nuget package produced by the CI builds and add in whatever other functionality you need from SqlClient so we can see if there are other things that end up rooting the assembly?

**Comment by Benjiinator** [comment] 2021-02-15 14:12
@Wraith2 So far it appears to unload fine with the CI build.
The Microsoft.Data.SqlClient.SNI.dll is however still locked in the filesystem even after unloading.
I am attempting to delete the file so that i can update my application.

**Comment by Wraith2** [comment] 2021-02-15 16:39
Hmm, that's an unmanaged root then and I'm not sure how to track that down, @janvorli any hints?

**Comment by janvorli** [comment] 2021-02-15 19:30
@Wraith2 Unmanaged dlls used via DllImport cannot be ever freed, that's by design. I was trying to enable unloading them when I was working on the unloadable AssemblyLoadContext, but in the discussion on the respective PR, there were concerns about allowing freeing of native libraries in general. Many native libraries are not designed to be freeable and freeing them could result in memory leaks, crashes, deadlocks and other nasty stuff. See https://github.com/dotnet/coreclr/pull/22274 for details. The main issue is that if we freed the native libraries automatically, people that are not even aware that a 3rd party component uses native library may start hitting these issues that are difficult to diagnose in general when they use the component in an unloadable context.
So the way to free dlls where the author intends them to be freed is to use the NativeLibrary class (https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary?view=net-5.0) to explicitly load/unload the library and get the exports instead of using the PInvoke. Then you have full control over the library lifetime.

**Comment by Wraith2** [comment] 2021-02-15 19:49
Tricky then. The alternative is to put sql client in managed mode using the AppContext switch "Switch.Microsoft.Data.SqlClient.UseManagedNetworkingOnWindows" which will force it to use managed sni instead of native sni.dll, the perf isn't quite as good but it's mostly the same. Just make sure you set it before calling any sql client functions.

I'll have a look at the loader code for sni.dll at some point but i remember there being some complex logic around loading the right version from subdirectories and i don't want to disturb it given how many support issues it causes.

**Comment by Benjiinator** [comment] 2021-02-16 08:15
@Wraith2 using your CI build and setting "Switch.Microsoft.Data.SqlClient.UseManagedNetworkingOnWindows" did the trick for me. Thanks for your help @Wraith2, and thanks to you @janvorli for explaining the issue.

**Comment by David-Engel** [comment] 2021-02-16 22:29
> I'll have a look at the loader code for sni.dll at some point but i remember there being some complex logic around loading the right version from subdirectories and i don't want to disturb it given how many support issues it causes.

@Wraith2 It's not as complicated as you think. It just uses a standard DllImport to load the appropriate x86/x64 class and then DLL either in the SqlClient DLL's current folder or in the PATH. It would be awesome if we could reliably unload the SNI DLL when it's appropriate. I looked into a way to do it before, but didn't find a simple solution.

All here: https://github.com/dotnet/SqlClient/tree/master/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop

**Comment by Wraith2** [comment] 2021-02-16 22:34
I'm not sure if it'll be worth doing. If we want to move to managed sni as default then enabling NativeLibrary loading of the pinvokes is a distraction. It'll all depend on performance gains and timescales and customer demand. If setting the app context is enough for most users then it might be best to leave it as-is.

**Comment by Benjiinator** [comment] 2021-03-04 11:09
@Wraith2 Your solution has worked so far, but i have found out that unloading does not work when using ```CommandType.StoredProcedure```.

**Comment by Wraith2** [comment] 2021-03-04 11:17
Interesting, can you provide a minimal repo for that and I'll dig into it again and see if i can identify what is rooting it for that case.

**Comment by Benjiinator** [comment] 2021-03-04 14:05
@Wraith2 I have been unable to recreate it. currently investigating if anything else could be causing this behavior.

**Comment by Benjiinator** [comment] 2021-03-04 14:33
@Wraith2 i seem to have resolved my issue now, but what caused it remains a mystery.

**Comment by Wraith2** [comment] 2021-03-04 15:15
Well if you find more all I'll need is the repro and I can investigate.

**Comment by cheenamalhotra** [comment] 2021-03-12 23:06
Closing as PR #913 is now merged.

**Closed by cheenamalhotra** 2021-03-12 23:06 UTC

**Comment by rafalkwol** [comment] 2022-06-04 20:42
@Wraith2 it seems the solution is working fine in 3.1 version of Microsoft.Data.SqlClient NuGet, but doesn't seem to be working for me in 4.0 and beyond. Any idea what change could be causing this? As otherwise I will have to use 3.1 in my plugin based application, but would prefer to stick to the newest version.

**Comment by Wraith2** [comment] 2022-06-04 23:20
If you can provide a standalone repro then I can debug into it and see what is rooting sqlclient. If you do manage to reproduce it please open a new issue so it can be tracked as an open item.

**Comment by rafalkwol** [comment] 2022-06-05 07:42
@Wraith2 I made a separate issue for this with the source code provided.

#1635
