### ISSUE TITLE
Need help getting AzureKeyVaultProvider to work with NET6

### ISSUE THREAD

**Issue by umamaheswareada550** [dotnet/SqlClient#1924] opened 2023-02-14 15:46 UTC
I am trying to implement Always Encrypted feature in .NET6.

Error --> ```System.ArgumentException: Failed to decrypt a column encryption key. Invalid key store provider name: 'AZURE_KEY_VAULT'. A key store provider name must denote either a system key store provider or a registered custom key store provider. Valid system key store provider names are: 'MSSQL_CERTIFICATE_STORE', 'MSSQL_CNG_STORE', 'MSSQL_CSP_PROVIDER'. Valid (currently registered) custom key store provider names are: . Please verify key store provider information in column master key definitions in the database, and verify all custom key store providers used in your application are registered properly.```

I was going through the docs and unable to figure it out in resolving this issue.
Any pointers/suggestions in this regard?

Registering the Provider :- 

```internal partial class AlwaysEncryptedPearlDbContext : DbContext
    {
        static bool IsInitialized;
        readonly ActiveDirectory _activeDirectory;
        static ClientCredential _ClientCredential;
        public AlwaysEncryptedPearlDbContext(DbContextOptions<AlwaysEncryptedPearlDbContext> options, IOptions<AppSettings> appSettings)
    : base(options)
        {
            _activeDirectory = appSettings.Value.ActiveDirectory;
            if (!IsInitialized)
            { InitializeAzureKeyVaultProvider(); IsInitialized = true; }

            void InitializeAzureKeyVaultProvider()
            {
                _ClientCredential = new ClientCredential(_activeDirectory.ClientId.ToString(), _activeDirectory.ClientSecret);

                SqlColumnEncryptionAzureKeyVaultProvider azureKeyVaultProvider = new SqlColumnEncryptionAzureKeyVaultProvider(GetToken);

                Dictionary<string, SqlColumnEncryptionKeyStoreProvider> providers =
                  new Dictionary<string, SqlColumnEncryptionKeyStoreProvider>
                  {
                      { SqlColumnEncryptionAzureKeyVaultProvider.ProviderName, azureKeyVaultProvider }
                  };
                SqlConnection.RegisterColumnEncryptionKeyStoreProviders(providers);
            }

            async Task<string> GetToken(string authority, string resource, string scope)
            {
                var authContext = new AuthenticationContext(authority);
                AuthenticationResult result = await authContext.AcquireTokenAsync(resource, _ClientCredential);

                if (result == null)
                    throw new InvalidOperationException("Failed to obtain the access token");
                return result.AccessToken;
            }
        }
    }```

Packages : 
Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider : 1.2.0
Microsoft.Identity.Client: 4.50.0
ActiveDirectory : 5.3.0

**Comment by JRahnama** [comment] 2023-02-14 16:51
@umamaheswareada550 seems like a duplicate of #1907. If it is, please close this one and follow the thread on that issue.

**Comment by JRahnama** [comment] 2023-02-20 07:37
closing as duplicate. Please follow issue #1907 for more information.

**Closed by JRahnama** 2023-02-20 07:37 UTC
Labels: Duplicate
