### ISSUE TITLE
Calling `RollbackAsync(string)` on a `SqlTransaction` object will throw a `NotSupportedException`.

### ISSUE THREAD

**Issue by byte-clown** [dotnet/SqlClient#2213] opened 2023-11-10 04:24 UTC
### Describe the bug

Calling `RollbackAsync(string)` on a `Microsoft.Data.SqlClient.SqlTransaction` object will throw a `NotSupportedException`.

### To reproduce

```c#
SqlTransaction tran = ...;
tran.RollbackAsync("..."); // throw NotSupportedException
```

**Additional context**

The method `public void Rollback(string transactionName)` in `Microsoft.Data.SqlClient.SqlTransaction` should be declared as `override`, just like the `public override void Rollback()` method.

Because `Microsoft.Data.SqlClient.SqlTransaction` itself does not actually implement the `RollbackAsync(string)` method, when you call the `RollbackAsync(string)` method on a `Microsoft.Data.SqlClient.SqlTransaction` object, you are actually invoking the `RollbackAsync(string)` method of `System.Data.Common.DbTransaction`.

The `RollbackAsync(string)` method of `System.Data.Common.DbTransaction` is actually implemented by calling the `Rollback(string)` method and then returning a `Task.CompletedTask` object. Since the `Rollback(string)` method of `Microsoft.Data.SqlClient.SqlTransaction` does not have an `override` declaration, it still calls the `Rollback(string)` method of `System.Data.Common.DbTransaction`, which will throw a `NotSupportedException`.

**Comment by roji** [comment] 2023-11-10 13:14
Duplicate of #1256

**Comment by roji** [comment] 2023-11-10 13:15
Implementing the ADO.NET savepoint management APIs in general - async and sync - is tracked by #1256.

**Comment by DavoudEshtehari** [comment] 2023-11-10 17:40
@byte-clown Feel free to include any thoughts on the #1256 thread. Closing as it is a duplicate.

**Closed by DavoudEshtehari** 2023-11-10 17:40 UTC
