### ISSUE TITLE
SqlClient SqlBulkCopy ColumnMapping case sensitive 

### ISSUE THREAD

**Issue by tomhafner** [dotnet/SqlClient#751] opened 2020-10-07 16:27 UTC
Is there a possibility to correct the bug with the case sensitive column names after 10 years with the new namespace?

 {
                    if ((_localColumnMappings[assocId]._destinationColumnOrdinal == metadata.ordinal) ||
                        **(UnquotedName(_localColumnMappings[assocId]._destinationColumnName) == metadata.column)**)
                    {
                        if (rejectColumn)

The comparison of the column names should be case insensitive.
By definition, the SQL server is not case sensitive for the object names.

**Comment by cheenamalhotra** [comment] 2020-10-07 16:33
@tomhafner Thanks for the catch.

I also agree SQL Server is not case sensitive for object names and this comparison should be fixed.
Since this is not a breaking change, there's no concern in getting this fixed soon!

cc @karinazhou

**Comment by mburbea** [comment] 2020-10-08 04:41
Sql servers case sensitivity matches the collation of the database. 
The default is case insensitive, but you can make it case sensitive if you're inclined.

**Comment by cheenamalhotra** [comment] 2020-10-08 17:57
That's a good point @mburbea 👍 
I think if we have to fix it for case-insensitive comparison (CI), it could be based on collation information from available metadata.

**Comment by karinazhou** [comment] 2020-10-17 02:04
Hi @tomhafner ,

After comparing the bulk copy behavior with other drivers such as ODBC and JDBC, I think that the following destination column name comparison is by design: 

```
if ((_localColumnMappings[assocId]._destinationColumnOrdinal == metadata.ordinal) ||
(UnquotedName(_localColumnMappings[assocId]._destinationColumnName) == metadata.column))
```

For the ODBC driver, the application is allowed to bind data to a table column during bulk copy by column ordinal. The column name is not considered:
https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-extensions-bulk-copy-functions/bcp-bind?view=sql-server-ver15

For the JDBC driver, the application can add the source column name and destination column name by `SQLServerBulkCopy.addColumnMapping()`. This requires the column name to be exactly the same as what is in the destination table. Otherwise, it will give an invalid column name exception no matter the destination database collation is case sensitive or case insensitive.  
https://github.com/microsoft/mssql-jdbc/blob/dev/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java#L414
https://github.com/microsoft/mssql-jdbc/blob/dev/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java#L1817

When using column mapping, either matched destination column ordinals or matched destination column names are required. It is expected that the application provides the correct destination column metadata to the driver when column mapping is applied. 

Thanks,

**Comment by cheenamalhotra** [comment] 2020-10-30 21:12
Hi @mburbea 

As explained by @karinazhou above, we don't think this behavior is a bug as it is by design.
Closing this issue.

**Closed by cheenamalhotra** 2020-10-30 21:12 UTC
Labels: By Design
