### ISSUE TITLE
SqlClient gives wrong error with expired or incorrect SQL Server credentials

### ISSUE THREAD

**Issue by albahari** [dotnet/SqlClient#103] opened 2019-01-12 10:20 UTC
Microsoft Windows [Version 10.0.17763.253]
Microsoft.NETCore.App 3.0.0-preview1-26929-01

To reproduce:

1. In SQL Server 2017, create a new SQL Server login with SQL Server authentication. Set the username to 'test' and the password to 'foo'. Leave the checkbox "User must change password at next login" ticked. (Note that the bug still occurs without that checkbox ticked, but the consequences are not as severe).

2. Create a .NET Core Console app that references nuget:System.Data.SqlClient and paste in the following code:

```
static void Main (string[] args)
{
    TestSql ();    // Fails - gives wrong error
    // Try again 6 seconds later
    Thread.Sleep (6000);
    TestSql ();   // Now it works correctly
}

static void TestSql()
{
    var cx = new SqlConnection ("Data Source=.;User ID=test;Password=foo");
    try
    {
        cx.Open ();
    }
    catch (SqlException ex)
    {
        Console.WriteLine (ex.Number);
        Console.WriteLine (ex.Message);
    }
    Console.WriteLine();
}
```

Expected result:
```
18488
Login failed for user 'test'.  Reason: The password of the account must be changed.

18488
Login failed for user 'test'.  Reason: The password of the account must be changed.
```

Actual result:
```
233
A connection was successfully established with the server, but then an error occurred during the login process. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.)

18488
Login failed for user 'test'.  Reason: The password of the account must be changed.
```

It's a bit of a showstopper if you're trying to catch the scenario of a user's login expiring, so you can prompt the user to change their password. The problem does not occur with .NET Framework. 

Here's the stack trace for the first exception:
```
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
```

**Comment by divega** [comment] 2019-05-16 01:26
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by peterbae** [comment] 2019-07-30 22:05
Hi @albahari,

I just tested your code against .Net Core version `3.0.100-preview7-012821` with System.Data.SqlClient version `4.6.1`, and the error seems to be no longer reproducible. Could you test against the latest packages and let me know if you still experience the same problem?

**Comment by albahari** [comment] 2019-07-31 03:47
I've just tried it with netcore 3.0.0-preview7-27912-14, using both System.Data.SqlClient 4.6.1 and System.Data.SqlClient 4.7.0-preview7.19362.9, and I'm experiencing the same bug.

**Comment by David-Engel** [comment] 2019-09-06 15:49
I've been poking at this issue a bit and in my investigation, I've found that it only occurs when named pipes is used for the connection. So the repro against localhost (Data Source=.) returns 233 because it defaults to using named pipes locally, but if you change it to "Data Source=tcp:." to force it to use TCP, it returns 18488, as expected.

@albahari Can you confirm that adding "tcp:" to the connection string to force the driver to use TCP when connecting locally works for you and is a viable workaround?

**Comment by albahari** [comment] 2019-09-07 01:32
Yes, that seems to be the case. I'm not sure that this counts as a workaround (because you can't force users to connect via tcp, and tcp may be disabled for the SQL Server instance). However, it certainly reduces the severity of the issue, because SQL authentication is more likely to be used with tcp than with pipes.

**Comment by imranmomin** [comment] 2020-11-12 21:20
I'm facing a similar issue `A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The target principal name is incorrect.).`

I notice it fails on version` Microsoft.Data.SqlClient 2.0.0` or greater and works fine when selecting `Microsoft.Data.SqlClient 1.1.3`

On v2.0.0 it fails with error `A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: HTTP Provider, error: 0 - )
`
On v2.0.1 it fails with error `A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The target principal name is incorrect.)`

Note: It works fine when connecting to local SQL Server 15.0.2000.5 and fails when it tries to connect a remote SQL Server 12.0.6024.0

Connection string used - data source=xxx;initial catalog=xxx_db;user id=xxx;password=xxx;

**Comment by imranmomin** [comment] 2020-11-12 21:47
#795 solved the issue for me

**Comment by JRahnama** [comment] 2023-04-03 19:55
Closing the issue as this seems to be fixed with #795. Feel free to comment here or open a new issue.

**Closed by JRahnama** 2023-04-03 19:55 UTC
Labels: :bug: Bug!

**Comment by cheenamalhotra** [comment] 2023-04-05 09:17
@JRahnama is the original issue posted no longer reproducible with MDS?

**Comment by JRahnama** [comment] 2023-04-09 16:48
@cheenamalhotra the issue seems resolved in M.D.S in managed code as far as I have tested.
I will do more testing with netfx when I have addressed target principal name error in native code. The below sample is from latest  version.

![image](https://user-images.githubusercontent.com/32077152/230785409-6082ded2-9ca4-407b-9ad5-6ab3bbc3aaca.png)
