### ISSUE TITLE
CDATA Block is not formatter correctly in VS

### ISSUE THREAD

**Issue by YuryKomar** [dotnet/SqlClient#2013] opened 2023-04-20 11:10 UTC
The function descriprion includes a comment CDATA block is not completely formatted in Visual Studio. I mean the XREF hyperlink, it stil visible in popup...

Will it be fixed? 

see attached image
![Снимок](https://user-images.githubusercontent.com/12536828/233348792-8b2ca5ff-f54f-48f7-9644-83673945d894.PNG)
![SqlClient Info](https://user-images.githubusercontent.com/12536828/233348806-547bc107-50ce-46ac-b066-fefa9a8c988c.png)

**Comment by JRahnama** [comment] 2023-04-26 18:21
We will check this with VS team and will get back to you.

**Comment by arkalyanms** [comment] 2023-05-08 22:37
Moved to the right repo via https://github.com/dotnet/roslyn/issues/68134. Feel free to close this one.

**Comment by JRahnama** [comment] 2023-05-09 03:39
Thank you @arkalyanms. @YuryKomar you can follow this on [roslyn repo](https://github.com/dotnet/roslyn/issues/68134). Closing this as an external issue.

**Comment by sharwell** [comment] 2023-05-14 16:56
The rendering of this comment is an accurate reflection of the content provided here:

https://github.com/dotnet/SqlClient/blob/f478be5bf3597f5c0f0940ac471c6b481c38416f/doc/snippets/Microsoft.Data.SqlClient/SqlCommand.xml#L7-L47

Note that `<format type="text/markdown">` is not a recognized content for documentation comments, so the contents of this element will be rendered the same way as if the content was written inline (i.e. not surrounded by the `<format>` element).

**Closed** 2024-09-05 15:56 UTC

**Comment by JRahnama** [comment] 2024-09-05 16:29
This is to inform you that work is currently in progress to resolve the issue. The first [PR](https://github.com/dotnet/SqlClient/pull/2822) has been merged, and the remaining updates will follow shortly.

**Comment by benrr101** [comment] 2024-09-23 16:36
At long last, the batches have been completed, and the docs have been restructured into XML format. There are a couple follow up tasks, but the bulk of the work is complete.

**Comment by benrr101** [comment] 2024-09-23 16:37
(also I guess I messed up by linking the issue to the PR and it auto-closed it...)

**Comment by JRahnama** [comment] 2024-09-23 16:53
> (also I guess I messed up by linking the issue to the PR and it auto-closed it...)

I think this is fine/correct., as the issue is addressed/being addressed in several PRs.
