### ISSUE TITLE
Inconsistent behavior with multiple text readers

### ISSUE THREAD

**Issue by vonzshik** [dotnet/SqlClient#2087] opened 2023-07-11 15:28 UTC
Given an example:

```csharp
using var conn = new SqlConnection("...");
conn.Open();

using var cmd = conn.CreateCommand();
cmd.CommandText = "SELECT 'abcdefgh', 'ijklmnop'";
using var reader = cmd.ExecuteReader(CommandBehavior.SequentialAccess);
reader.Read();
using var tr1 = reader.GetTextReader(0);

reader.GetValue(1);

tr1.Read();
```

you get an `ObjectDisposedException` from `tr1.Read()`. It makes sense since SqlClient disposes open stream/textread while reading next column in sequential mode.

But if you change the example to instead open multiple text readers:

```csharp
using var tr1 = reader.GetTextReader(0);
using var tr2 = reader.GetTextReader(1);

tr2.Read();
tr1.Read();
```

you do not get an `ObjectDisposedException` from `tr1.Read()` since SqlClient didn't dispose the previous text reader,

### Expected behavior
Calling `GetStream`/`GetTextReader` should dispose previously open stream/textreader the same way as `GetValue` does.

### Further technical details
Microsoft.Data.SqlClient version: 5.1.1
.NET 6

**Comment by Kaur-Parminder** [comment] 2023-07-12 17:57
@vonzshik did try your repro and can see the issue occurring. will be investigating further after next targeted preview release. thanks for reporting.

**Comment by Wraith2** [comment] 2023-07-15 13:40
`using var tr1 = reader.GetTextReader(0);
using var tr2 = reader.GetTextReader(1);
`

I'm pretty sure this is unsupported and only works accidentally in the case where the entire contents of the first field will fit inside the current tds packet. Unless you're using MARS there can only be one reader per connection and there should only be one stream per reader since it'd effectively moving on the read head in the packet.

**Comment by roji** [comment] 2023-07-15 14:00
@Wraith2 unless CommandBehavior.SequentialAccess, isn't the entire row buffered, so there shouldn't be any problem with supporting multiple streams?

In any case, if this is unsupported it seems like it should at least through rather than have undefined behavior etc.

**Comment by arellegue** [comment] 2024-01-12 18:40
It was decided that this issue will not be fixed as the behavior reported is by design.  Not fixing the issue will not cause any harm to anyone. However, fixing the issue could potentially cause more issues.

**Closed by arellegue** 2024-01-12 18:40 UTC
Labels: :bug: Bug!
