### ISSUE TITLE
Enabling Long Paths Ignored (Filename or Extension is Too Long)

### ISSUE THREAD

**Issue by dattaei-eb** [dotnet/SqlClient#1698] opened 2022-08-09 00:03 UTC
### Describe the bug
When attempting to build my microservice I am getting a build error in the form of a dependency filename or extension being too long. This only appears to be happening the DLLs from SqlClient as after enabling "long path" support other issues caused by a long path went away.

In order to fix this issue I have attempted the following:

1. Setting git config --system core.longpaths true
2. Enabling the "long paths" Group Policy and confirming the proper change was made in the registry.
3. Including  "longPathAware" in the application manifest.

The last two suggested solutions from:
https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

For whatever reason, those settings seem to work for all DLLs except those coming from dotnet/SqlClient.

Exception message:
```
The type initializer for 'Microsoft.Data.SqlClient.SNILoadHandle' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Microsoft.Data.SqlClient.SNI.dll' or one of its dependencies: The filename or extension is too long. (0x800700CE)
```

### To reproduce
Simply create a dummy solution using SqlClient and nest it into a parent directory/directories causing a >260 character path.

### Expected behavior
After enabling long paths the solution should be able to build properly.

### Further technical details
Microsoft.Data.SqlClient version: (found on the nuget or Microsoft.Data.SqlClient.dll)
.NET target: net6.0
Operating system: Windows Server 2019 Standard

**Comment by lcheunglci** [comment] 2022-08-09 15:28
Thanks @dattaei-eb for bringing this path length issue to our attention, we'll do some investigation and get back to you soon.

**Comment by JRahnama** [comment] 2022-08-10 19:59
@dattaei-eb what version of VS are you using? I tried creating an application, but VS2022 prevented me from doing that indicating that the file name is too long. The length was initially 260 but I reduced it 250 but still no success.

![image](https://user-images.githubusercontent.com/32077152/184008656-efe16d0b-5fe4-4b3e-af0c-fc8bfb8d7f1a.png)

**Comment by dattaei-eb** [comment] 2022-08-10 20:22
Hi @JRahnama, thank you for reaching out!

We're using VS2022, however, it's part of a job being kicked off by a GitHub Action to our build server and it's using the CLI to compile and build.

**Comment by JRahnama** [comment] 2022-08-24 19:08
@dattaei-eb this looks like by design and there is nothing we can do about this.

**Comment by JRahnama** [comment] 2022-08-26 18:57
I am closing this issue as it seems by design. Feel free to open a new issue or comment here if you still think this should not happen and we can reopen this.

**Closed by JRahnama** 2022-08-26 18:57 UTC
Labels: By Design
