### ISSUE TITLE
SqlConnectionStringBuilder does not report ICustomTypeDescriptor properties properly

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/SqlClient#1275] opened 2021-09-22 16:42 UTC
### Describe the bug
`SqlConnectionStringBuilder` inherits from a base class that implements ICustomTypeDescriptor, which is supposed to report the class's properties to a property inspector and make them easy to edit.  Hooking one up to a `SqlConnectionStringBuilder` instance, however, shows several properties reported twice, where editing one of them works as expected and the other one raises data binding errors.

### To reproduce
[See attached project.](https://github.com/dotnet/SqlClient/files/7212457/SqlServer.Repro.zip)  Note that many properties are reported twice, including the all-important Data Source and Initial Catalog.

### Expected behavior
Every connection string property should be reported exactly once and be editable without errors.

### Further technical details
Microsoft.Data.SqlClient version: 4.8.3
.NET target: .NET 5
SQL Server version: n/a
Operating system: Windows 10

**Comment by JRahnama** [comment] 2021-09-22 21:55
@masonwheeler from the provided sample I can see System.Data.SqlClient is being used and the mentioned version also confirms that. Is that correct?

**Comment by JRahnama** [comment] 2021-09-22 22:26
How did you resolve `SoftFluent.Windows` to work for netcore? Can you test your project with Microsoft.Data.SqlClient latest preview release and see the results as well?

**Comment by masonwheeler** [comment] 2021-09-22 22:54
> @masonwheeler from the provided sample I can see System.Data.SqlClient is being used and the mentioned version also confirms that. Is that correct?

Yes.

> How did you resolve `SoftFluent.Windows` to work for netcore?

Not sure what you mean.  I grabbed it from NuGet and built the project and ran it.  Is it not building for you?

> Can you test your project with Microsoft.Data.SqlClient latest preview release and see the results as well?

Thanks for the heads-up!  I didn't even notice they were two different namespaces.  With *that* package, it appears to be working as expected.

**Comment by JRahnama** [comment] 2021-09-22 23:54
![image](https://user-images.githubusercontent.com/32077152/134436495-966a7560-6bcb-4f3d-89d2-3f8c83eab19c.png)


The entire message is this:
`Package 'SoftFluent.Windows 1.0.1.6' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.`

System.Data.SqlClient is in servicing mode and is not accepting any updates, but critical ones. Microsoft.Data.SqlClient is getting updates on regular basis and this issue was resolved I believe in [PR #1152](https://github.com/dotnet/SqlClient/pull/1152)

If the problem is solved please feel free to close the issue.

**Comment by masonwheeler** [comment] 2021-09-23 03:20
Yeah, that seems to be a nuisance warning that doesn't convey any useful information and can be safely ignored.  All it means is that the last time the NuGet package was built was before .NET 5 was around.

Having said that, I get that message multiple times in my project for `Microsoft.SqlServer.Types`.  Is there an up-to-date package anywhere that will provide the SQL Server types for a .NET 5 project?

**Comment by JRahnama** [comment] 2021-09-23 16:48
Not that I am aware of. What is the message? I am not getting that on my side on the provided sample.

**Comment by masonwheeler** [comment] 2021-09-23 16:49
It's not on the provided sample; it's on my *actual* project.

> Warning	NU1701	Package 'Microsoft.SqlServer.Types 14.0.1016.290' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

**Comment by ErikEJ** [comment] 2021-09-23 16:54
There is no Microsoft.SqlServer.Types package for .NET 5.

**Comment by JRahnama** [comment] 2021-09-23 16:57
I did not have that package referenced in the provided sample code. I manually installed it and got the same message. Can you test removing that reference from you project?

**Comment by masonwheeler** [comment] 2021-09-23 17:01
@ErikEJ So who do I need to ping about getting it updated?

**Comment by masonwheeler** [comment] 2021-09-23 17:02
@JRahnama no; then it wouldn't compile because I'm using those types.

**Comment by cheenamalhotra** [comment] 2021-09-23 17:15
@masonwheeler 

Microsoft.SqlServer.Types is not available for .NET 5 right now.
The team who owns it is aware and they are working on it as we know from internal discussions.

**Closed** 2021-09-24 01:41 UTC
