### ISSUE TITLE
SqlConnectionStringBuilder why does "Trust Server Certificate=True" have spaces?

### ISSUE THREAD

**Issue by MojoDK** [dotnet/SqlClient#1407] opened 2021-11-25 10:58 UTC
Setting `SqlConnectionStringBuilder.TrustServerCertificate = True` results in the string returned by  `SqlConnectionStringBuilder.ConnectionString` to be "Trust Server Certificate=True".

Why the spaces?

Why not return "TrustServerCertificate=True"?

Is TrustServerCertificate deprecated in favor of "Trust Server Certificate?

**Comment by roji** [comment] 2021-11-25 11:07
@MojoDK SqlConnectionStringBuilder.TrustServerCertificate is a .NET property - those can't have spaces. SqlConnectionStringBuilder.ConnectionString is a string representation of the connection string, the standard there is to have spaces. [See the docs on SqlClient's connection string](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=dotnet-plat-ext-6.0) for moer info.

**Comment by MojoDK** [comment] 2021-11-25 11:22
> @MojoDK SqlConnectionStringBuilder.TrustServerCertificate is a .NET property - those can't have spaces. SqlConnectionStringBuilder.ConnectionString is a string representation of the connection string, the standard there is to have spaces. [See the docs on SqlClient's connection string](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=dotnet-plat-ext-6.0) for moer info.

I think I'm not being clear (I'm not english)...

I wonder why the result of SqlConnectionStringBuilder.ConnectionString function is...

`"Data Source=x; Initial Catalog=x; Trust Server Certificate=True"`

and not ...

`"Data Source=x; Initial Catalog=x; TrustServerCertificate=True"`

?

**Comment by roji** [comment] 2021-11-25 12:27
Because as I wrote above, in the string representation of a connection string (what SqlConnectionStringBuilder.ConnectionString returns), that's the standard representation; the connection string doesn't contain the name of .NET properties on SqlConnectionStringBuilder (which have no spaces), but a more readable representation with spaces. Check out the docs I linked to above.

**Comment by Tornhoof** [comment] 2021-11-25 19:55
> Check out the docs I linked to above.

You mean the one with the large table?
The key for the string is listed in the left column right?
That one says ``TrustServerCertificate``. No spaces.

![Screenshot_2021-11-25-20-52-56-05_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/7989549/143494806-360cd987-2912-4a8a-b0de-4bb0c46f681f.jpg)


So are the docs wrong? Personally, I've never seen that key ``with`` spaces.

**Comment by JRahnama** [comment] 2021-11-25 21:01
@MojoDK if you print out `SqlConnectionStringBuilder.ConnectionString` as you mentioned you will see` Trust Server Certificate=True`. This is how driver keeps that internally for the `SqlConnectionStringBuilder` this is the value for property `TrustServerCertificate`, but both values are accepted when you define your connection string. As @roji mentioned when you use the property 

```C#
SqlConnectionStringBuilder builder = new ()
            {
                TrustServerCertificate=true
            };
```

and when you define it inside `SqlConnection` :
 you can either go with 

```C#
SqlConnection conn = new("Data Source=localhost;Integrated Security=true;TrustServerCertificate=true;");
```

or 

```C#
SqlConnection conn = new("Data Source=localhost;Integrated Security=true;Trust Server Certificate=true;");

```
same thing applies to `Multiple Active Result Sets` if you define the string for `SqlConnection` you can either enter them with space or without them.

```C#
SqlConnection conn = new("Data Source=localhost;Integrated Security=true;Trust Server Certificate=true;Multiple Active Result Sets=true;");
```

**Comment by MojoDK** [comment] 2021-11-25 21:17
@JRahnama Thanks for the explanation. 

As I see it, the library "System.Data.SqlClient" SqlConnection only accepts TrustServerCertificate (without spaces), so I just wondered why "Microsoft.Data.SqlClient" isn't consistent and let SqlConnectionStringBuilder print it out without spaces too - like in the docs roti refers too?

**Comment by JRahnama** [comment] 2021-11-25 22:16
`Microsoft.Data.SqlClient` starting from v2.0 standardized the `SqlConnection` properties for better user experience. It started with PR #534. Microsoft.Data.SqlClient API coud be browsed at [this location](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient?view=sqlclient-dotnet-standard-4.0). 

Just to mention that `System.Data.SqlClient` is in servicing mode and does not accept any PR or fix, but critical ones. MDS is the active library for `ADO.NET` and makes fixes and improvements on regular bases.   

I am closing the issue as it is by design. Feel free to reopen the issue if you find out the documentation needs to be updated.

**Closed by JRahnama** 2021-11-25 22:16 UTC
Labels: By Design

**Comment by danielscatigno-ncpc** [comment] 2023-08-01 17:12
This should be reopened
I'm having issues because Im setting the connection string of a SqlMembershipProvider using a SqlConnectionStringBuilder from Microsoft.Data.SqlClient and it's throwing the following error:

System.ArgumentException: 'An error occurred while attempting to initialize a System.Data.SqlClient.SqlConnection object. The value that was provided for the connection string may be wrong, or it may contain an invalid syntax.
ArgumentException: Keyword not supported: 'trust server certificate'.

The connection string is not accepted because of those spaces

**Comment by kmcclellan** [comment] 2023-11-21 16:55
To be clear (since I was still confused after reading this), the property _used to_ be named "TrustServerCertificate" and [was changed](https://github.com/dotnet/SqlClient/pull/534) to "Trust Server Certificate" (with backwards compatibility). The new client accepts either form for backwards compatibility. The old client does not support the newer name. If you want to use the newer name, you need to update to the newer client.

**Comment by Damglador** [comment] 2024-08-13 16:18
That's so stupid, designer creates connection with "trust server certificate", but it just breaks application, while editing connection string there is impossible and workarounds are obscure
