### ISSUE TITLE
Prepared query plans are never unprepared

### ISSUE THREAD

**Issue by Wraith2** [dotnet/SqlClient#214] opened 2019-09-24 18:37 UTC
In the netfx build BuildUnprepare() is present but never called. In core it has been removed. Once a query is prepared the query handle is discarded but is never used to unprepared. This will leave the query plan associated the connection until the real connection closes. This may not be a problem but it is a little surprising, i'd like to determine if this is intentional or whether it needs to be fixed.

**Comment by cheenamalhotra** [comment] 2019-09-25 16:40
That doesn't seem right to me, could you also verify if it's same behavior in `System.Data.SqlClient` drivers as well?

**Comment by Wraith2** [comment] 2019-09-25 17:47
I checked there too, it's the same as M.D.SqlClient. There are no references to either of TdsEnums.RPC_PROCID_UNPREPARE or TdsEnums.SP_UNPREPARE (r explicit use of sp_unprepasre). I'd noticed no unprepare while working on the rpc PR and thought there must be some way of releasing it that I wasn't aware of so I went looking and can't find one. I think Unprepare() should probably do an rpc call where currently it is deferring for some other thing that doesn't happen.

**Comment by saurabh500** [comment] 2019-10-25 20:47
This has been by design from the very beginning. Unprepare will need to be done via an API call. 
Also Prepare() is an explicit call, and to unprepare, the connection can be returned to the pool and then new operations can be done on a new connection.

I had a conversation a couple years ago about this with one of the old time SqlClient leads who is now retired and this is the information that I have. 

Yeah, there was a bunch of dead unused code in SqlClient as well which has been removed. I am not sure why, perhaps Unprepare was implemented but then it didn't make sense to include it as an API in favor of the pattern of putting the connection back in the pool and opening a new connection with no prepare context.

**Comment by Wraith2** [comment] 2019-10-25 21:25
Is unpreparng something which should be implemented? Or is it best to leave it as-is? If left alone it might be worth documenting that it is effectively useless.

**Comment by saurabh500** [comment] 2019-10-25 21:46
I would say leave as is. Not worth documenting in docs since the contracts don't expose it. 

If you want to document code, then write a comment on the method.

**Comment by yukiwongky** [comment] 2019-10-29 22:16
Closing as by design.

**Closed by yukiwongky** 2019-10-29 22:16 UTC
