### ISSUE TITLE
Microsoft.Data.SQLClient throws exception trying to access Azure SQL Database

### ISSUE THREAD

**Issue by sh4d0v1** [dotnet/SqlClient#1668] opened 2022-07-06 12:32 UTC
I am running two .NET6 apps on Linux Azure Web App containers, which need connections to a Azure SQL database.
The first one connects to the DB without problem, the second one, deployed on the same service plan with the same configuration, throws the following generic exception:
```
 Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: TCP Provider, error: 35 - An internal exception was caught)
  ---> System.IO.IOException: Unable to write data to the transport connection: Connection reset by peer.
  ---> System.Net.Sockets.SocketException (104): Connection reset by peer
    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
    --- End of inner exception stack trace ---
    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
    at System.IO.Stream.Write(ReadOnlySpan`1 buffer)
    at System.Net.Sockets.NetworkStream.Write(ReadOnlySpan`1 buffer)
    at Microsoft.Data.SqlClient.SNI.SslOverTdsStream.Write(ReadOnlySpan`1 buffer)
    at Microsoft.Data.SqlClient.SNI.SslOverTdsStream.Write(Byte[] buffer, Int32 offset, Int32 count)
    at System.Net.Security.SslStream.WriteSingleChunk[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
    at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
    at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
    at Microsoft.Data.SqlClient.SNI.SNIPacket.WriteToStream(Stream stream)
    at Microsoft.Data.SqlClient.SNI.SNITCPHandle.Send(SNIPacket packet)
    at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
    at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
    at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
    at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
    at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
    at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
    at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
    at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
    at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
    at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
    at Microsoft.Data.SqlClient.SqlConnection.Open()
    at BBB.Identity.Configuration.IdentityServerConfigurationProvider.Load() in D:\a\1\s\BBB.Identity\Configuration\IdentityServerConfigurationProvider.cs:line 26
    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
    at BBB.Identity.Configuration.IdentityServerConfigurationManager.SetIdentityConfigurationRoot() in D:\a\1\s\BBB.Identity\Configuration\IdentityServerConfigurationManager.cs:line 34
    at BBB.Identity.Configuration.IdentityServerConfigurationManager.InitializeIdentityServerConfiguration() in D:\a\1\s\BBB.Identity\Configuration\IdentityServerConfigurationManager.cs:line 17
    at Program.<Main>$(String[] args) in D:\a\1\s\BBB.Identity\Program.cs:line 15
```

### To reproduce
Not sure how to provide reproducibility as it is a private project.
I myself can't reproduce the issue somewhere else: When deploying the app locally and connecting it to the Azure SQL db it works.

### Expected behavior
A working connection to the Azure SQL database.

### Further technical details
Microsoft.Data.SqlClient version: 4.1.0
.NET target: .NET6(.0.301)
SQL Server version: Azure SQL database
Operating system: Azure App Service Plan Linux

Both apps are on the same service plan, have the same connection string, the same configuration and the same software versions. I can not imagine where the difference lies, which could produce the connection error.

**Comment by DavoudEshtehari** [comment] 2022-07-11 21:47
The exception shows that it's a network thing. So, I'd suggest playing with firewall.

**Comment by sh4d0v1** [comment] 2022-07-12 08:40
The firewall of the Azure SQL DB is open. The error message also says "**A connection was successfully established with the server**, but then an error occurred during the login process." so the TCP handshake has to have been successful at least, right?

**Comment by sh4d0v1** [comment] 2022-07-12 20:21
Yes, by now I figured there is not much you guys can do without more debug info. I am in contact with the Azure support for some days now, unfortunately yet unsuccessful though.

Maybe less general exceptions would be helpful, right?

**Comment by DavoudEshtehari** [comment] 2022-07-12 22:41
I don't get what you mean exactly. Generally, the first step is finding a way to reproduce an issue for further investigation. The stack trace is the least that we can just give you some guesses. In your case, since you could connect with one of them and the inner exception is a `SocketException` shows it's likely a connectivity issue and you should investigate the Azure logs.

**Comment by tpickard84** [comment] 2022-07-28 02:34
@sh4d0v1 - I'm experiencing this same error with your same specs.  Did Azure support ever back with you? I will try opening a ticket as well, just curious if they were able to resolve the issue for you. Thanks!

**Comment by sh4d0v1** [comment] 2022-07-28 13:28
So glad I am not the only one, proves I am not crazy ;)

The Azure Support was really trying once I got beyond the stages where they just recommend all the stuff from the docs which you mentioned already in the initial ticket as not working, but ultimately wasn't able to help.

Workaround was to just use the Windows based App Service containers and move on...

**Comment by tpickard84** [comment] 2022-07-28 15:00
@sh4d0v1  - wow that's unsettling.  

I'll report back here if my Azure support experience goes any differently.

**Comment by JRahnama** [comment] 2022-08-26 19:01
@tpickard84 and @sh4d0v1 any update on the issue with Azure support? Is the issue resolved?

**Comment by beginner1010** [comment] 2022-09-02 16:21
I am getting almost the same stack trace as @sh4d0v1 got. However, when I rerun it works fine for the whole day. So, in my case, the first try to connect to Azure SQL after a couple of hours of being idle is an issue.

I use a retry policy. I plan to increase the delay (between retries) to see if it resolves the issue 🤞. Also, I will increase the timeout in the SQL connection string from 30 secs to 60.

**Comment by beginner1010** [comment] 2022-09-04 01:21
Update: After changing my retry policy (which now will wait 1 * 6 seconds, 2 * 6 seconds, 4 * 6 seconds & retry, and so on instead of 1 second, 2 seconds, 4 seconds, etc. delays), it proceeds to work fine. Note that still I'm getting an exception error on the first try but this time, the retry policy is not getting trapped in the "pool blocking period".

**Comment by shalinisriram** [comment] 2022-12-13 09:02
Please Same error am getting what have to do any one reply

**Comment by k-koleda** [comment] 2023-05-03 09:44
Is there any update? it still actual for me :(

**Comment by jrichardsz** [comment] 2023-05-24 22:29
Same error :(

source > VPN > AWS

- Source: Old MS SQL Server in Windows On-Premise
- Target: 
  - Ubuntu & Centos latest version 2023
  - Netcore 3 & 7
  - `<PackageReference Include="System.Data.SqlClient" Version="4.8.5" />`

It works when a developer connects to the ms server using a vpn and his laptop

## attempts

- https://stackoverflow.com/questions/15488922/connection-to-sql-server-works-sometimes

**Comment by David-Engel** [comment] 2024-07-03 17:13
Closing as external / not repro.

**Closed by David-Engel** 2024-07-03 17:13 UTC
Labels: :link: External
