### ISSUE TITLE
Better diagnostic for connection issues - CRL Check timeout

### ISSUE THREAD

**Issue by vasicvuk** [dotnet/SqlClient#1627] opened 2022-05-27 09:52 UTC
### Describe the bug

In one of our client environments, we had odd behavior in terms that when we first run service it cannot connect to SQL Server with following errors for few times:

**Error 1**

```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
```

**Error 2**
```
System.InvalidOperationException: Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached.
at Microsoft.Data.Common.ADP.ExceptionWithStackTrace(Exception e)
--- End of stack trace from previous location ---
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
```

After a few connection attempts, it established the connection and the service regularly works until there is a need to extend the Pool of the connection with new ones. Then the same error appears and requests timeouts.

We lost a few days debugging what is the issue and we tried:
- Upgrading SQL Client version to the latest 4.X
- Upgrading of SQL Server to the latest patch version
- Checking disk space and resource utilization of SQL Server

Then we notice that SQL Server has a certificate with CRL (Certificate Revocation List) endpoint which is not available to call from the network the service was run from.

After changing firewall rules to allow access from SqlClient to CRL endpoint everything was working fine.

Days of debugging could be easier if there was a real exception message instead of what we got now.

Interesting thing is that services using .NET Core 3.1 and SqlClient 2.X didn't report any issues and worked correctly from the start.

### Expected behavior
Exception with information that CRL endpoint timeout so that we know from the start what the issue really is.

### Further technical details
Microsoft.Data.SqlClient version: 4.1.0
.NET target: 6.0
SQL Server version: SQL Server 2019
Operating system: Windows Server 2019

**Comment by JRahnama** [comment] 2022-05-27 18:05
@vasicvuk there was a bug in v4.x that forces the CRL check. It is included in the main branch and a it will be included in the next hotfix release.

**Comment by vasicvuk** [comment] 2022-05-27 18:11
@JRahnama That is great, But in general logging should be improved to know the reasons why connection cannot be obtained. Is the pool full, is connection to server timed out and similar

**Comment by JRahnama** [comment] 2022-06-01 19:02
@vasicvuk I think as an unforeseen case of issue proper logging/Exception catching was not provided.

**Comment by vasicvuk** [comment] 2022-06-02 06:59
@JRahnama I agree, but maybe now is the time to improve logs so next time we don't get generic message when something unforseen happens.

**Comment by JRahnama** [comment] 2022-06-15 19:04
@vasicvuk the issue is coming from an external library that we do not have any access to it. There is nothing we can do here.

**Comment by JRahnama** [comment] 2022-09-02 17:59
Closing the issue as there is nothing much could be done from this library. Feel free to make a PR for any suggested solution.

**Closed by JRahnama** 2022-09-02 17:59 UTC
