### ISSUE TITLE
Issue when connecting to azure sql over Virtual Network in App Service.

### ISSUE THREAD

**Issue by alandillon** [dotnet/SqlClient#487] opened 2020-03-24 23:08 UTC
### Describe the bug
 

- I can connect with the user via SSMS.

- If I run the code locally on my machine it works. 

- If I run it in an azure app service using IP whitelisting against azure sql it works. 

- If I use Virtual Network with the app service for whitelisting the virtual network against azure sql it no longer works.

I use the virtual network method with other apps that do not use entity framework core.

I am working on implementing this sample.

https://github.com/Azure/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK

Microsoft.Marketplace.SaaS.SDK.CustomerProvisioning 

```
Exception message:
Stack trace:

Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open server "xxxxxx" requested by the login.  The login failed.
   at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
ClientConnectionId:xxxxxxx
Error Number:40532,State:1,Class:14

```

![image](https://user-images.githubusercontent.com/3331097/77484875-11739980-6e02-11ea-871b-29bf39642d97.png)

![image](https://user-images.githubusercontent.com/3331097/77485249-0e2cdd80-6e03-11ea-869e-799ff28bef6b.png)

![image](https://user-images.githubusercontent.com/3331097/77485153-d1f97d00-6e02-11ea-80dd-29ecc43ca519.png)

**Comment by cheenamalhotra** [comment] 2020-03-24 23:23
Hi @kyurthich 

Have you contacted Azure support for this issue?
This looks like VNet issue to me, rather than SqlClient.

**Comment by kyurthich** [comment] 2020-03-24 23:28
I did. I redirected them to this request. I wanted to cover both sides because sometimes it takes a little bit to get responses.

**Comment by cheenamalhotra** [comment] 2020-03-24 23:40
We have usually noticed such issues when working with Azure environments due to port restrictions enforced in VNet. You may want to check for that.

You can also try to create some sample apps in any other languages (or using System.Data.SqlClient)  in the same VNet to verify if it's network related or a specific driver problem.

**Comment by kyurthich** [comment] 2020-03-24 23:45
Ok thanks! I will try some things out. And post back here if I reach a solution so it may help others.

**Comment by kyurthich** [comment] 2020-03-25 00:22
Adding on I also have other apps that communicate via vnet to this same database and have no issues. So it is a very odd scenario. The other apps use .net framework and the Function app I use has refs to Microsoft.Data.SqlClient .

**Comment by cheenamalhotra** [comment] 2020-07-23 21:55
@alandillon 

Do you still have this issue or have some updates to share?

**Comment by cheenamalhotra** [comment] 2020-10-21 01:55
Closing due to non reproducible and non active.

**Closed by cheenamalhotra** 2020-10-21 01:55 UTC
